// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/payment_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	dto "passenger_service_backend/internal/dto"
	models "passenger_service_backend/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockPaymentService is a mock of PaymentService interface.
type MockPaymentService struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentServiceMockRecorder
}

// MockPaymentServiceMockRecorder is the mock recorder for MockPaymentService.
type MockPaymentServiceMockRecorder struct {
	mock *MockPaymentService
}

// NewMockPaymentService creates a new mock instance.
func NewMockPaymentService(ctrl *gomock.Controller) *MockPaymentService {
	mock := &MockPaymentService{ctrl: ctrl}
	mock.recorder = &MockPaymentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentService) EXPECT() *MockPaymentServiceMockRecorder {
	return m.recorder
}

// Confirm mocks base method.
func (m *MockPaymentService) Confirm(ctx context.Context, paymentID uuid.UUID, success bool) (*models.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Confirm", ctx, paymentID, success)
	ret0, _ := ret[0].(*models.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Confirm indicates an expected call of Confirm.
func (mr *MockPaymentServiceMockRecorder) Confirm(ctx, paymentID, success interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Confirm", reflect.TypeOf((*MockPaymentService)(nil).Confirm), ctx, paymentID, success)
}

// GetByPNR mocks base method.
func (m *MockPaymentService) GetByPNR(ctx context.Context, pnrID uuid.UUID) ([]models.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPNR", ctx, pnrID)
	ret0, _ := ret[0].([]models.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPNR indicates an expected call of GetByPNR.
func (mr *MockPaymentServiceMockRecorder) GetByPNR(ctx, pnrID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPNR", reflect.TypeOf((*MockPaymentService)(nil).GetByPNR), ctx, pnrID)
}

// GetByStatus mocks base method.
func (m *MockPaymentService) GetByStatus(ctx context.Context, status models.PaymentStatus, page, limit int) ([]models.Payment, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByStatus", ctx, status, page, limit)
	ret0, _ := ret[0].([]models.Payment)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByStatus indicates an expected call of GetByStatus.
func (mr *MockPaymentServiceMockRecorder) GetByStatus(ctx, status, page, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByStatus", reflect.TypeOf((*MockPaymentService)(nil).GetByStatus), ctx, status, page, limit)
}

// Initiate mocks base method.
func (m *MockPaymentService) Initiate(ctx context.Context, req dto.InitiatePaymentRequest) (*models.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initiate", ctx, req)
	ret0, _ := ret[0].(*models.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Initiate indicates an expected call of Initiate.
func (mr *MockPaymentServiceMockRecorder) Initiate(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initiate", reflect.TypeOf((*MockPaymentService)(nil).Initiate), ctx, req)
}

// Refund mocks base method.
func (m *MockPaymentService) Refund(ctx context.Context, paymentID uuid.UUID) (*models.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refund", ctx, paymentID)
	ret0, _ := ret[0].(*models.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refund indicates an expected call of Refund.
func (mr *MockPaymentServiceMockRecorder) Refund(ctx, paymentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refund", reflect.TypeOf((*MockPaymentService)(nil).Refund), ctx, paymentID)
}
