// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/ticket_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "passenger_service_backend/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockTicketService is a mock of TicketService interface.
type MockTicketService struct {
	ctrl     *gomock.Controller
	recorder *MockTicketServiceMockRecorder
}

// MockTicketServiceMockRecorder is the mock recorder for MockTicketService.
type MockTicketServiceMockRecorder struct {
	mock *MockTicketService
}

// NewMockTicketService creates a new mock instance.
func NewMockTicketService(ctrl *gomock.Controller) *MockTicketService {
	mock := &MockTicketService{ctrl: ctrl}
	mock.recorder = &MockTicketServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTicketService) EXPECT() *MockTicketServiceMockRecorder {
	return m.recorder
}

// GetByPassenger mocks base method.
func (m *MockTicketService) GetByPassenger(ctx context.Context, passengerID uuid.UUID) (*models.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPassenger", ctx, passengerID)
	ret0, _ := ret[0].(*models.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPassenger indicates an expected call of GetByPassenger.
func (mr *MockTicketServiceMockRecorder) GetByPassenger(ctx, passengerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPassenger", reflect.TypeOf((*MockTicketService)(nil).GetByPassenger), ctx, passengerID)
}

// GetByTicketNumber mocks base method.
func (m *MockTicketService) GetByTicketNumber(ctx context.Context, number string) (*models.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTicketNumber", ctx, number)
	ret0, _ := ret[0].(*models.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTicketNumber indicates an expected call of GetByTicketNumber.
func (mr *MockTicketServiceMockRecorder) GetByTicketNumber(ctx, number interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTicketNumber", reflect.TypeOf((*MockTicketService)(nil).GetByTicketNumber), ctx, number)
}

// IssueForPNR mocks base method.
func (m *MockTicketService) IssueForPNR(ctx context.Context, pnrID uuid.UUID) ([]models.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueForPNR", ctx, pnrID)
	ret0, _ := ret[0].([]models.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueForPNR indicates an expected call of IssueForPNR.
func (mr *MockTicketServiceMockRecorder) IssueForPNR(ctx, pnrID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueForPNR", reflect.TypeOf((*MockTicketService)(nil).IssueForPNR), ctx, pnrID)
}
