// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/seat_lock_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "passenger_service_backend/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockSeatLockRepository is a mock of SeatLockRepository interface.
type MockSeatLockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSeatLockRepositoryMockRecorder
}

// MockSeatLockRepositoryMockRecorder is the mock recorder for MockSeatLockRepository.
type MockSeatLockRepositoryMockRecorder struct {
	mock *MockSeatLockRepository
}

// NewMockSeatLockRepository creates a new mock instance.
func NewMockSeatLockRepository(ctrl *gomock.Controller) *MockSeatLockRepository {
	mock := &MockSeatLockRepository{ctrl: ctrl}
	mock.recorder = &MockSeatLockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeatLockRepository) EXPECT() *MockSeatLockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSeatLockRepository) Create(ctx context.Context, lock *models.SeatLock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, lock)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSeatLockRepositoryMockRecorder) Create(ctx, lock interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSeatLockRepository)(nil).Create), ctx, lock)
}

// FindByFlightSeatID mocks base method.
func (m *MockSeatLockRepository) FindByFlightSeatID(ctx context.Context, flightSeatID uuid.UUID) (*models.SeatLock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFlightSeatID", ctx, flightSeatID)
	ret0, _ := ret[0].(*models.SeatLock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFlightSeatID indicates an expected call of FindByFlightSeatID.
func (mr *MockSeatLockRepositoryMockRecorder) FindByFlightSeatID(ctx, flightSeatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFlightSeatID", reflect.TypeOf((*MockSeatLockRepository)(nil).FindByFlightSeatID), ctx, flightSeatID)
}

// FindByPNRID mocks base method.
func (m *MockSeatLockRepository) FindByPNRID(ctx context.Context, pnrID uuid.UUID) ([]models.SeatLock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByPNRID", ctx, pnrID)
	ret0, _ := ret[0].([]models.SeatLock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByPNRID indicates an expected call of FindByPNRID.
func (mr *MockSeatLockRepositoryMockRecorder) FindByPNRID(ctx, pnrID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByPNRID", reflect.TypeOf((*MockSeatLockRepository)(nil).FindByPNRID), ctx, pnrID)
}

// FindExpired mocks base method.
func (m *MockSeatLockRepository) FindExpired(ctx context.Context) ([]models.SeatLock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindExpired", ctx)
	ret0, _ := ret[0].([]models.SeatLock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindExpired indicates an expected call of FindExpired.
func (mr *MockSeatLockRepositoryMockRecorder) FindExpired(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindExpired", reflect.TypeOf((*MockSeatLockRepository)(nil).FindExpired), ctx)
}

// Release mocks base method.
func (m *MockSeatLockRepository) Release(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockSeatLockRepositoryMockRecorder) Release(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockSeatLockRepository)(nil).Release), ctx, id)
}

// ReleaseByPNR mocks base method.
func (m *MockSeatLockRepository) ReleaseByPNR(ctx context.Context, pnrID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseByPNR", ctx, pnrID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseByPNR indicates an expected call of ReleaseByPNR.
func (mr *MockSeatLockRepositoryMockRecorder) ReleaseByPNR(ctx, pnrID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseByPNR", reflect.TypeOf((*MockSeatLockRepository)(nil).ReleaseByPNR), ctx, pnrID)
}
