// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/flight_schedule_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "passenger_service_backend/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockFlightScheduleRepository is a mock of FlightScheduleRepository interface.
type MockFlightScheduleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFlightScheduleRepositoryMockRecorder
}

// MockFlightScheduleRepositoryMockRecorder is the mock recorder for MockFlightScheduleRepository.
type MockFlightScheduleRepositoryMockRecorder struct {
	mock *MockFlightScheduleRepository
}

// NewMockFlightScheduleRepository creates a new mock instance.
func NewMockFlightScheduleRepository(ctrl *gomock.Controller) *MockFlightScheduleRepository {
	mock := &MockFlightScheduleRepository{ctrl: ctrl}
	mock.recorder = &MockFlightScheduleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlightScheduleRepository) EXPECT() *MockFlightScheduleRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFlightScheduleRepository) Create(ctx context.Context, schedule *models.FlightSchedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, schedule)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFlightScheduleRepositoryMockRecorder) Create(ctx, schedule interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFlightScheduleRepository)(nil).Create), ctx, schedule)
}

// Delete mocks base method.
func (m *MockFlightScheduleRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFlightScheduleRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFlightScheduleRepository)(nil).Delete), ctx, id)
}

// FindAll mocks base method.
func (m *MockFlightScheduleRepository) FindAll(ctx context.Context) ([]models.FlightSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]models.FlightSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockFlightScheduleRepositoryMockRecorder) FindAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockFlightScheduleRepository)(nil).FindAll), ctx)
}

// FindByFlightNumber mocks base method.
func (m *MockFlightScheduleRepository) FindByFlightNumber(ctx context.Context, flightNumber string) (*models.FlightSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFlightNumber", ctx, flightNumber)
	ret0, _ := ret[0].(*models.FlightSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFlightNumber indicates an expected call of FindByFlightNumber.
func (mr *MockFlightScheduleRepositoryMockRecorder) FindByFlightNumber(ctx, flightNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFlightNumber", reflect.TypeOf((*MockFlightScheduleRepository)(nil).FindByFlightNumber), ctx, flightNumber)
}

// FindByID mocks base method.
func (m *MockFlightScheduleRepository) FindByID(ctx context.Context, id uuid.UUID) (*models.FlightSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*models.FlightSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockFlightScheduleRepositoryMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockFlightScheduleRepository)(nil).FindByID), ctx, id)
}

// FindByRoute mocks base method.
func (m *MockFlightScheduleRepository) FindByRoute(ctx context.Context, depAirportID, arrAirportID uuid.UUID) ([]models.FlightSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRoute", ctx, depAirportID, arrAirportID)
	ret0, _ := ret[0].([]models.FlightSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRoute indicates an expected call of FindByRoute.
func (mr *MockFlightScheduleRepositoryMockRecorder) FindByRoute(ctx, depAirportID, arrAirportID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRoute", reflect.TypeOf((*MockFlightScheduleRepository)(nil).FindByRoute), ctx, depAirportID, arrAirportID)
}

// Update mocks base method.
func (m *MockFlightScheduleRepository) Update(ctx context.Context, schedule *models.FlightSchedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, schedule)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockFlightScheduleRepositoryMockRecorder) Update(ctx, schedule interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFlightScheduleRepository)(nil).Update), ctx, schedule)
}
