// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/flight_seat_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "passenger_service_backend/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockFlightSeatRepository is a mock of FlightSeatRepository interface.
type MockFlightSeatRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFlightSeatRepositoryMockRecorder
}

// MockFlightSeatRepositoryMockRecorder is the mock recorder for MockFlightSeatRepository.
type MockFlightSeatRepositoryMockRecorder struct {
	mock *MockFlightSeatRepository
}

// NewMockFlightSeatRepository creates a new mock instance.
func NewMockFlightSeatRepository(ctrl *gomock.Controller) *MockFlightSeatRepository {
	mock := &MockFlightSeatRepository{ctrl: ctrl}
	mock.recorder = &MockFlightSeatRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlightSeatRepository) EXPECT() *MockFlightSeatRepositoryMockRecorder {
	return m.recorder
}

// BulkCreate mocks base method.
func (m *MockFlightSeatRepository) BulkCreate(ctx context.Context, seats []models.FlightSeat) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkCreate", ctx, seats)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkCreate indicates an expected call of BulkCreate.
func (mr *MockFlightSeatRepositoryMockRecorder) BulkCreate(ctx, seats interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkCreate", reflect.TypeOf((*MockFlightSeatRepository)(nil).BulkCreate), ctx, seats)
}

// CountAvailable mocks base method.
func (m *MockFlightSeatRepository) CountAvailable(ctx context.Context, flightID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAvailable", ctx, flightID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAvailable indicates an expected call of CountAvailable.
func (mr *MockFlightSeatRepositoryMockRecorder) CountAvailable(ctx, flightID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAvailable", reflect.TypeOf((*MockFlightSeatRepository)(nil).CountAvailable), ctx, flightID)
}

// FindAvailableByFlight mocks base method.
func (m *MockFlightSeatRepository) FindAvailableByFlight(ctx context.Context, flightID uuid.UUID) ([]models.FlightSeat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAvailableByFlight", ctx, flightID)
	ret0, _ := ret[0].([]models.FlightSeat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAvailableByFlight indicates an expected call of FindAvailableByFlight.
func (mr *MockFlightSeatRepositoryMockRecorder) FindAvailableByFlight(ctx, flightID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAvailableByFlight", reflect.TypeOf((*MockFlightSeatRepository)(nil).FindAvailableByFlight), ctx, flightID)
}

// FindAvailableByFlightAndClass mocks base method.
func (m *MockFlightSeatRepository) FindAvailableByFlightAndClass(ctx context.Context, flightID uuid.UUID, classCode string) ([]models.FlightSeat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAvailableByFlightAndClass", ctx, flightID, classCode)
	ret0, _ := ret[0].([]models.FlightSeat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAvailableByFlightAndClass indicates an expected call of FindAvailableByFlightAndClass.
func (mr *MockFlightSeatRepositoryMockRecorder) FindAvailableByFlightAndClass(ctx, flightID, classCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAvailableByFlightAndClass", reflect.TypeOf((*MockFlightSeatRepository)(nil).FindAvailableByFlightAndClass), ctx, flightID, classCode)
}

// FindByFlight mocks base method.
func (m *MockFlightSeatRepository) FindByFlight(ctx context.Context, flightID uuid.UUID) ([]models.FlightSeat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFlight", ctx, flightID)
	ret0, _ := ret[0].([]models.FlightSeat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFlight indicates an expected call of FindByFlight.
func (mr *MockFlightSeatRepositoryMockRecorder) FindByFlight(ctx, flightID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFlight", reflect.TypeOf((*MockFlightSeatRepository)(nil).FindByFlight), ctx, flightID)
}

// FindByID mocks base method.
func (m *MockFlightSeatRepository) FindByID(ctx context.Context, id uuid.UUID) (*models.FlightSeat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*models.FlightSeat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockFlightSeatRepositoryMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockFlightSeatRepository)(nil).FindByID), ctx, id)
}

// FindWithSeatDetail mocks base method.
func (m *MockFlightSeatRepository) FindWithSeatDetail(ctx context.Context, id uuid.UUID) (*models.FlightSeat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWithSeatDetail", ctx, id)
	ret0, _ := ret[0].(*models.FlightSeat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWithSeatDetail indicates an expected call of FindWithSeatDetail.
func (mr *MockFlightSeatRepositoryMockRecorder) FindWithSeatDetail(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWithSeatDetail", reflect.TypeOf((*MockFlightSeatRepository)(nil).FindWithSeatDetail), ctx, id)
}

// UpdateStatus mocks base method.
func (m *MockFlightSeatRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status models.FlightSeatStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockFlightSeatRepositoryMockRecorder) UpdateStatus(ctx, id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockFlightSeatRepository)(nil).UpdateStatus), ctx, id, status)
}
