// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/aircraft_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "passenger_service_backend/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	gorm "gorm.io/gorm"
)

// MockAircraftRepository is a mock of AircraftRepository interface.
type MockAircraftRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAircraftRepositoryMockRecorder
}

// MockAircraftRepositoryMockRecorder is the mock recorder for MockAircraftRepository.
type MockAircraftRepositoryMockRecorder struct {
	mock *MockAircraftRepository
}

// NewMockAircraftRepository creates a new mock instance.
func NewMockAircraftRepository(ctrl *gomock.Controller) *MockAircraftRepository {
	mock := &MockAircraftRepository{ctrl: ctrl}
	mock.recorder = &MockAircraftRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAircraftRepository) EXPECT() *MockAircraftRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAircraftRepository) Create(ctx context.Context, aircraft *models.Aircraft) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, aircraft)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAircraftRepositoryMockRecorder) Create(ctx, aircraft interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAircraftRepository)(nil).Create), ctx, aircraft)
}

// Delete mocks base method.
func (m *MockAircraftRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAircraftRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAircraftRepository)(nil).Delete), ctx, id)
}

// FindAll mocks base method.
func (m *MockAircraftRepository) FindAll(ctx context.Context) ([]models.Aircraft, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]models.Aircraft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockAircraftRepositoryMockRecorder) FindAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockAircraftRepository)(nil).FindAll), ctx)
}

// FindByID mocks base method.
func (m *MockAircraftRepository) FindByID(ctx context.Context, tx *gorm.DB, id uuid.UUID) (*models.Aircraft, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, tx, id)
	ret0, _ := ret[0].(*models.Aircraft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockAircraftRepositoryMockRecorder) FindByID(ctx, tx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockAircraftRepository)(nil).FindByID), ctx, tx, id)
}

// FindWithSeats mocks base method.
func (m *MockAircraftRepository) FindWithSeats(ctx context.Context, id uuid.UUID) (*models.Aircraft, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWithSeats", ctx, id)
	ret0, _ := ret[0].(*models.Aircraft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWithSeats indicates an expected call of FindWithSeats.
func (mr *MockAircraftRepositoryMockRecorder) FindWithSeats(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWithSeats", reflect.TypeOf((*MockAircraftRepository)(nil).FindWithSeats), ctx, id)
}

// Update mocks base method.
func (m *MockAircraftRepository) Update(ctx context.Context, tx *gorm.DB, aircraft *models.Aircraft) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, tx, aircraft)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAircraftRepositoryMockRecorder) Update(ctx, tx, aircraft interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAircraftRepository)(nil).Update), ctx, tx, aircraft)
}
