// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/passenger_meal_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "passenger_service_backend/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockPassengerMealRepository is a mock of PassengerMealRepository interface.
type MockPassengerMealRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPassengerMealRepositoryMockRecorder
}

// MockPassengerMealRepositoryMockRecorder is the mock recorder for MockPassengerMealRepository.
type MockPassengerMealRepositoryMockRecorder struct {
	mock *MockPassengerMealRepository
}

// NewMockPassengerMealRepository creates a new mock instance.
func NewMockPassengerMealRepository(ctrl *gomock.Controller) *MockPassengerMealRepository {
	mock := &MockPassengerMealRepository{ctrl: ctrl}
	mock.recorder = &MockPassengerMealRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPassengerMealRepository) EXPECT() *MockPassengerMealRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPassengerMealRepository) Create(ctx context.Context, meal *models.PassengerMeal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, meal)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPassengerMealRepositoryMockRecorder) Create(ctx, meal interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPassengerMealRepository)(nil).Create), ctx, meal)
}

// Delete mocks base method.
func (m *MockPassengerMealRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPassengerMealRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPassengerMealRepository)(nil).Delete), ctx, id)
}

// FindByPassengerID mocks base method.
func (m *MockPassengerMealRepository) FindByPassengerID(ctx context.Context, passengerID uuid.UUID) ([]models.PassengerMeal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByPassengerID", ctx, passengerID)
	ret0, _ := ret[0].([]models.PassengerMeal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByPassengerID indicates an expected call of FindByPassengerID.
func (mr *MockPassengerMealRepositoryMockRecorder) FindByPassengerID(ctx, passengerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByPassengerID", reflect.TypeOf((*MockPassengerMealRepository)(nil).FindByPassengerID), ctx, passengerID)
}
