// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/passenger_ssr_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "passenger_service_backend/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockPassengerSSRRepository is a mock of PassengerSSRRepository interface.
type MockPassengerSSRRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPassengerSSRRepositoryMockRecorder
}

// MockPassengerSSRRepositoryMockRecorder is the mock recorder for MockPassengerSSRRepository.
type MockPassengerSSRRepositoryMockRecorder struct {
	mock *MockPassengerSSRRepository
}

// NewMockPassengerSSRRepository creates a new mock instance.
func NewMockPassengerSSRRepository(ctrl *gomock.Controller) *MockPassengerSSRRepository {
	mock := &MockPassengerSSRRepository{ctrl: ctrl}
	mock.recorder = &MockPassengerSSRRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPassengerSSRRepository) EXPECT() *MockPassengerSSRRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPassengerSSRRepository) Create(ctx context.Context, ssr *models.PassengerSSR) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, ssr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPassengerSSRRepositoryMockRecorder) Create(ctx, ssr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPassengerSSRRepository)(nil).Create), ctx, ssr)
}

// Delete mocks base method.
func (m *MockPassengerSSRRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPassengerSSRRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPassengerSSRRepository)(nil).Delete), ctx, id)
}

// FindByPassengerID mocks base method.
func (m *MockPassengerSSRRepository) FindByPassengerID(ctx context.Context, passengerID uuid.UUID) ([]models.PassengerSSR, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByPassengerID", ctx, passengerID)
	ret0, _ := ret[0].([]models.PassengerSSR)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByPassengerID indicates an expected call of FindByPassengerID.
func (mr *MockPassengerSSRRepositoryMockRecorder) FindByPassengerID(ctx, passengerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByPassengerID", reflect.TypeOf((*MockPassengerSSRRepository)(nil).FindByPassengerID), ctx, passengerID)
}
