// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/permission_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "passenger_service_backend/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPermissionRepository is a mock of PermissionRepository interface.
type MockPermissionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionRepositoryMockRecorder
}

// MockPermissionRepositoryMockRecorder is the mock recorder for MockPermissionRepository.
type MockPermissionRepositoryMockRecorder struct {
	mock *MockPermissionRepository
}

// NewMockPermissionRepository creates a new mock instance.
func NewMockPermissionRepository(ctrl *gomock.Controller) *MockPermissionRepository {
	mock := &MockPermissionRepository{ctrl: ctrl}
	mock.recorder = &MockPermissionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionRepository) EXPECT() *MockPermissionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPermissionRepository) Create(param models.Permission) (models.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", param)
	ret0, _ := ret[0].(models.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPermissionRepositoryMockRecorder) Create(param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPermissionRepository)(nil).Create), param)
}

// Delete mocks base method.
func (m *MockPermissionRepository) Delete(param models.Permission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", param)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPermissionRepositoryMockRecorder) Delete(param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPermissionRepository)(nil).Delete), param)
}

// FindAll mocks base method.
func (m *MockPermissionRepository) FindAll() ([]models.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]models.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockPermissionRepositoryMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockPermissionRepository)(nil).FindAll))
}

// FindAllById mocks base method.
func (m *MockPermissionRepository) FindAllById(listId []uint) (*[]models.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllById", listId)
	ret0, _ := ret[0].(*[]models.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllById indicates an expected call of FindAllById.
func (mr *MockPermissionRepositoryMockRecorder) FindAllById(listId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllById", reflect.TypeOf((*MockPermissionRepository)(nil).FindAllById), listId)
}

// FindById mocks base method.
func (m *MockPermissionRepository) FindById(paramId uint) (models.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", paramId)
	ret0, _ := ret[0].(models.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockPermissionRepositoryMockRecorder) FindById(paramId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockPermissionRepository)(nil).FindById), paramId)
}

// Update mocks base method.
func (m *MockPermissionRepository) Update(param models.Permission) (models.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", param)
	ret0, _ := ret[0].(models.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPermissionRepositoryMockRecorder) Update(param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPermissionRepository)(nil).Update), param)
}
