// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/flight_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	dto "passenger_service_backend/internal/dto"
	models "passenger_service_backend/internal/models"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockFlightService is a mock of FlightService interface.
type MockFlightService struct {
	ctrl     *gomock.Controller
	recorder *MockFlightServiceMockRecorder
}

// MockFlightServiceMockRecorder is the mock recorder for MockFlightService.
type MockFlightServiceMockRecorder struct {
	mock *MockFlightService
}

// NewMockFlightService creates a new mock instance.
func NewMockFlightService(ctrl *gomock.Controller) *MockFlightService {
	mock := &MockFlightService{ctrl: ctrl}
	mock.recorder = &MockFlightServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlightService) EXPECT() *MockFlightServiceMockRecorder {
	return m.recorder
}

// GenerateFromSchedule mocks base method.
func (m *MockFlightService) GenerateFromSchedule(ctx context.Context, scheduleID uuid.UUID, from, to time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateFromSchedule", ctx, scheduleID, from, to)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateFromSchedule indicates an expected call of GenerateFromSchedule.
func (mr *MockFlightServiceMockRecorder) GenerateFromSchedule(ctx, scheduleID, from, to interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateFromSchedule", reflect.TypeOf((*MockFlightService)(nil).GenerateFromSchedule), ctx, scheduleID, from, to)
}

// GetByID mocks base method.
func (m *MockFlightService) GetByID(ctx context.Context, id uuid.UUID) (*models.Flight, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Flight)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockFlightServiceMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockFlightService)(nil).GetByID), ctx, id)
}

// GetByStatus mocks base method.
func (m *MockFlightService) GetByStatus(ctx context.Context, status models.FlightStatus) ([]models.Flight, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByStatus", ctx, status)
	ret0, _ := ret[0].([]models.Flight)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByStatus indicates an expected call of GetByStatus.
func (mr *MockFlightServiceMockRecorder) GetByStatus(ctx, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByStatus", reflect.TypeOf((*MockFlightService)(nil).GetByStatus), ctx, status)
}

// GetSeatMap mocks base method.
func (m *MockFlightService) GetSeatMap(ctx context.Context, flightID uuid.UUID) ([]dto.FlightSeatResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSeatMap", ctx, flightID)
	ret0, _ := ret[0].([]dto.FlightSeatResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSeatMap indicates an expected call of GetSeatMap.
func (mr *MockFlightServiceMockRecorder) GetSeatMap(ctx, flightID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeatMap", reflect.TypeOf((*MockFlightService)(nil).GetSeatMap), ctx, flightID)
}

// Search mocks base method.
func (m *MockFlightService) Search(ctx context.Context, req dto.SearchFlightRequest) ([]dto.FlightResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, req)
	ret0, _ := ret[0].([]dto.FlightResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockFlightServiceMockRecorder) Search(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockFlightService)(nil).Search), ctx, req)
}

// UpdateStatus mocks base method.
func (m *MockFlightService) UpdateStatus(ctx context.Context, id uuid.UUID, status models.FlightStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockFlightServiceMockRecorder) UpdateStatus(ctx, id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockFlightService)(nil).UpdateStatus), ctx, id, status)
}
