// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/seat_class_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "passenger_service_backend/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	gorm "gorm.io/gorm"
)

// MockSeatClassRepository is a mock of SeatClassRepository interface.
type MockSeatClassRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSeatClassRepositoryMockRecorder
}

// MockSeatClassRepositoryMockRecorder is the mock recorder for MockSeatClassRepository.
type MockSeatClassRepositoryMockRecorder struct {
	mock *MockSeatClassRepository
}

// NewMockSeatClassRepository creates a new mock instance.
func NewMockSeatClassRepository(ctrl *gomock.Controller) *MockSeatClassRepository {
	mock := &MockSeatClassRepository{ctrl: ctrl}
	mock.recorder = &MockSeatClassRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeatClassRepository) EXPECT() *MockSeatClassRepositoryMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockSeatClassRepository) FindAll(ctx context.Context) ([]models.SeatClass, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]models.SeatClass)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockSeatClassRepositoryMockRecorder) FindAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockSeatClassRepository)(nil).FindAll), ctx)
}

// FindByCode mocks base method.
func (m *MockSeatClassRepository) FindByCode(ctx context.Context, tx *gorm.DB, code string) (*models.SeatClass, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCode", ctx, tx, code)
	ret0, _ := ret[0].(*models.SeatClass)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCode indicates an expected call of FindByCode.
func (mr *MockSeatClassRepositoryMockRecorder) FindByCode(ctx, tx, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCode", reflect.TypeOf((*MockSeatClassRepository)(nil).FindByCode), ctx, tx, code)
}

// FindByID mocks base method.
func (m *MockSeatClassRepository) FindByID(ctx context.Context, id uuid.UUID) (*models.SeatClass, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*models.SeatClass)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockSeatClassRepositoryMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockSeatClassRepository)(nil).FindByID), ctx, id)
}
