// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/airport_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "passenger_service_backend/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockAirportRepository is a mock of AirportRepository interface.
type MockAirportRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAirportRepositoryMockRecorder
}

// MockAirportRepositoryMockRecorder is the mock recorder for MockAirportRepository.
type MockAirportRepositoryMockRecorder struct {
	mock *MockAirportRepository
}

// NewMockAirportRepository creates a new mock instance.
func NewMockAirportRepository(ctrl *gomock.Controller) *MockAirportRepository {
	mock := &MockAirportRepository{ctrl: ctrl}
	mock.recorder = &MockAirportRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAirportRepository) EXPECT() *MockAirportRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAirportRepository) Create(ctx context.Context, airport *models.Airport) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, airport)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAirportRepositoryMockRecorder) Create(ctx, airport interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAirportRepository)(nil).Create), ctx, airport)
}

// Delete mocks base method.
func (m *MockAirportRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAirportRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAirportRepository)(nil).Delete), ctx, id)
}

// FindAll mocks base method.
func (m *MockAirportRepository) FindAll(ctx context.Context) ([]models.Airport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]models.Airport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockAirportRepositoryMockRecorder) FindAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockAirportRepository)(nil).FindAll), ctx)
}

// FindByCode mocks base method.
func (m *MockAirportRepository) FindByCode(ctx context.Context, code string) (*models.Airport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCode", ctx, code)
	ret0, _ := ret[0].(*models.Airport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCode indicates an expected call of FindByCode.
func (mr *MockAirportRepositoryMockRecorder) FindByCode(ctx, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCode", reflect.TypeOf((*MockAirportRepository)(nil).FindByCode), ctx, code)
}

// FindByID mocks base method.
func (m *MockAirportRepository) FindByID(ctx context.Context, id uuid.UUID) (*models.Airport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*models.Airport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockAirportRepositoryMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockAirportRepository)(nil).FindByID), ctx, id)
}

// Search mocks base method.
func (m *MockAirportRepository) Search(ctx context.Context, query string) ([]models.Airport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, query)
	ret0, _ := ret[0].([]models.Airport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockAirportRepositoryMockRecorder) Search(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockAirportRepository)(nil).Search), ctx, query)
}

// Update mocks base method.
func (m *MockAirportRepository) Update(ctx context.Context, airport *models.Airport) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, airport)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAirportRepositoryMockRecorder) Update(ctx, airport interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAirportRepository)(nil).Update), ctx, airport)
}
