// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/ssr_type_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "passenger_service_backend/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSSRTypeRepository is a mock of SSRTypeRepository interface.
type MockSSRTypeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSSRTypeRepositoryMockRecorder
}

// MockSSRTypeRepositoryMockRecorder is the mock recorder for MockSSRTypeRepository.
type MockSSRTypeRepositoryMockRecorder struct {
	mock *MockSSRTypeRepository
}

// NewMockSSRTypeRepository creates a new mock instance.
func NewMockSSRTypeRepository(ctrl *gomock.Controller) *MockSSRTypeRepository {
	mock := &MockSSRTypeRepository{ctrl: ctrl}
	mock.recorder = &MockSSRTypeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSSRTypeRepository) EXPECT() *MockSSRTypeRepositoryMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockSSRTypeRepository) FindAll(ctx context.Context) ([]models.SSRType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]models.SSRType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockSSRTypeRepositoryMockRecorder) FindAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockSSRTypeRepository)(nil).FindAll), ctx)
}

// FindByCode mocks base method.
func (m *MockSSRTypeRepository) FindByCode(ctx context.Context, code string) (*models.SSRType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCode", ctx, code)
	ret0, _ := ret[0].(*models.SSRType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCode indicates an expected call of FindByCode.
func (mr *MockSSRTypeRepositoryMockRecorder) FindByCode(ctx, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCode", reflect.TypeOf((*MockSSRTypeRepository)(nil).FindByCode), ctx, code)
}
