// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/flight_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "passenger_service_backend/internal/models"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockFlightRepository is a mock of FlightRepository interface.
type MockFlightRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFlightRepositoryMockRecorder
}

// MockFlightRepositoryMockRecorder is the mock recorder for MockFlightRepository.
type MockFlightRepositoryMockRecorder struct {
	mock *MockFlightRepository
}

// NewMockFlightRepository creates a new mock instance.
func NewMockFlightRepository(ctrl *gomock.Controller) *MockFlightRepository {
	mock := &MockFlightRepository{ctrl: ctrl}
	mock.recorder = &MockFlightRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlightRepository) EXPECT() *MockFlightRepositoryMockRecorder {
	return m.recorder
}

// BulkCreate mocks base method.
func (m *MockFlightRepository) BulkCreate(ctx context.Context, flights []models.Flight) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkCreate", ctx, flights)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkCreate indicates an expected call of BulkCreate.
func (mr *MockFlightRepositoryMockRecorder) BulkCreate(ctx, flights interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkCreate", reflect.TypeOf((*MockFlightRepository)(nil).BulkCreate), ctx, flights)
}

// Create mocks base method.
func (m *MockFlightRepository) Create(ctx context.Context, flight *models.Flight) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, flight)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFlightRepositoryMockRecorder) Create(ctx, flight interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFlightRepository)(nil).Create), ctx, flight)
}

// Delete mocks base method.
func (m *MockFlightRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFlightRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFlightRepository)(nil).Delete), ctx, id)
}

// FindAvailable mocks base method.
func (m *MockFlightRepository) FindAvailable(ctx context.Context, depAirportID, arrAirportID uuid.UUID, date time.Time) ([]models.Flight, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAvailable", ctx, depAirportID, arrAirportID, date)
	ret0, _ := ret[0].([]models.Flight)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAvailable indicates an expected call of FindAvailable.
func (mr *MockFlightRepositoryMockRecorder) FindAvailable(ctx, depAirportID, arrAirportID, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAvailable", reflect.TypeOf((*MockFlightRepository)(nil).FindAvailable), ctx, depAirportID, arrAirportID, date)
}

// FindByID mocks base method.
func (m *MockFlightRepository) FindByID(ctx context.Context, id uuid.UUID) (*models.Flight, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*models.Flight)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockFlightRepositoryMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockFlightRepository)(nil).FindByID), ctx, id)
}

// FindBySchedule mocks base method.
func (m *MockFlightRepository) FindBySchedule(ctx context.Context, scheduleID uuid.UUID) ([]models.Flight, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySchedule", ctx, scheduleID)
	ret0, _ := ret[0].([]models.Flight)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySchedule indicates an expected call of FindBySchedule.
func (mr *MockFlightRepositoryMockRecorder) FindBySchedule(ctx, scheduleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySchedule", reflect.TypeOf((*MockFlightRepository)(nil).FindBySchedule), ctx, scheduleID)
}

// FindByStatus mocks base method.
func (m *MockFlightRepository) FindByStatus(ctx context.Context, status models.FlightStatus) ([]models.Flight, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByStatus", ctx, status)
	ret0, _ := ret[0].([]models.Flight)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByStatus indicates an expected call of FindByStatus.
func (mr *MockFlightRepositoryMockRecorder) FindByStatus(ctx, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByStatus", reflect.TypeOf((*MockFlightRepository)(nil).FindByStatus), ctx, status)
}

// FindWithDetails mocks base method.
func (m *MockFlightRepository) FindWithDetails(ctx context.Context, id uuid.UUID) (*models.Flight, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWithDetails", ctx, id)
	ret0, _ := ret[0].(*models.Flight)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWithDetails indicates an expected call of FindWithDetails.
func (mr *MockFlightRepositoryMockRecorder) FindWithDetails(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWithDetails", reflect.TypeOf((*MockFlightRepository)(nil).FindWithDetails), ctx, id)
}

// Update mocks base method.
func (m *MockFlightRepository) Update(ctx context.Context, flight *models.Flight) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, flight)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockFlightRepositoryMockRecorder) Update(ctx, flight interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFlightRepository)(nil).Update), ctx, flight)
}

// UpdateStatus mocks base method.
func (m *MockFlightRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status models.FlightStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockFlightRepositoryMockRecorder) UpdateStatus(ctx, id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockFlightRepository)(nil).UpdateStatus), ctx, id, status)
}
