// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/boarding_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "passenger_service_backend/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockBoardingPassRepository is a mock of BoardingPassRepository interface.
type MockBoardingPassRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBoardingPassRepositoryMockRecorder
}

// MockBoardingPassRepositoryMockRecorder is the mock recorder for MockBoardingPassRepository.
type MockBoardingPassRepositoryMockRecorder struct {
	mock *MockBoardingPassRepository
}

// NewMockBoardingPassRepository creates a new mock instance.
func NewMockBoardingPassRepository(ctrl *gomock.Controller) *MockBoardingPassRepository {
	mock := &MockBoardingPassRepository{ctrl: ctrl}
	mock.recorder = &MockBoardingPassRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBoardingPassRepository) EXPECT() *MockBoardingPassRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBoardingPassRepository) Create(ctx context.Context, bp *models.BoardingPass) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, bp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBoardingPassRepositoryMockRecorder) Create(ctx, bp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBoardingPassRepository)(nil).Create), ctx, bp)
}

// FindByID mocks base method.
func (m *MockBoardingPassRepository) FindByID(ctx context.Context, id uuid.UUID) (*models.BoardingPass, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*models.BoardingPass)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockBoardingPassRepositoryMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockBoardingPassRepository)(nil).FindByID), ctx, id)
}

// FindByPassengerAndSegment mocks base method.
func (m *MockBoardingPassRepository) FindByPassengerAndSegment(ctx context.Context, passengerID, segmentID uuid.UUID) (*models.BoardingPass, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByPassengerAndSegment", ctx, passengerID, segmentID)
	ret0, _ := ret[0].(*models.BoardingPass)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByPassengerAndSegment indicates an expected call of FindByPassengerAndSegment.
func (mr *MockBoardingPassRepositoryMockRecorder) FindByPassengerAndSegment(ctx, passengerID, segmentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByPassengerAndSegment", reflect.TypeOf((*MockBoardingPassRepository)(nil).FindByPassengerAndSegment), ctx, passengerID, segmentID)
}

// FindByPassengerID mocks base method.
func (m *MockBoardingPassRepository) FindByPassengerID(ctx context.Context, passengerID uuid.UUID) ([]models.BoardingPass, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByPassengerID", ctx, passengerID)
	ret0, _ := ret[0].([]models.BoardingPass)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByPassengerID indicates an expected call of FindByPassengerID.
func (mr *MockBoardingPassRepositoryMockRecorder) FindByPassengerID(ctx, passengerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByPassengerID", reflect.TypeOf((*MockBoardingPassRepository)(nil).FindByPassengerID), ctx, passengerID)
}

// FindBySegmentID mocks base method.
func (m *MockBoardingPassRepository) FindBySegmentID(ctx context.Context, segmentID uuid.UUID) ([]models.BoardingPass, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySegmentID", ctx, segmentID)
	ret0, _ := ret[0].([]models.BoardingPass)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySegmentID indicates an expected call of FindBySegmentID.
func (mr *MockBoardingPassRepositoryMockRecorder) FindBySegmentID(ctx, segmentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySegmentID", reflect.TypeOf((*MockBoardingPassRepository)(nil).FindBySegmentID), ctx, segmentID)
}
