// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/ticket_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "passenger_service_backend/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockTicketRepository is a mock of TicketRepository interface.
type MockTicketRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTicketRepositoryMockRecorder
}

// MockTicketRepositoryMockRecorder is the mock recorder for MockTicketRepository.
type MockTicketRepositoryMockRecorder struct {
	mock *MockTicketRepository
}

// NewMockTicketRepository creates a new mock instance.
func NewMockTicketRepository(ctrl *gomock.Controller) *MockTicketRepository {
	mock := &MockTicketRepository{ctrl: ctrl}
	mock.recorder = &MockTicketRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTicketRepository) EXPECT() *MockTicketRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTicketRepository) Create(ctx context.Context, ticket *models.Ticket) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, ticket)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTicketRepositoryMockRecorder) Create(ctx, ticket interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTicketRepository)(nil).Create), ctx, ticket)
}

// FindByID mocks base method.
func (m *MockTicketRepository) FindByID(ctx context.Context, id uuid.UUID) (*models.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*models.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockTicketRepositoryMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockTicketRepository)(nil).FindByID), ctx, id)
}

// FindByPassengerID mocks base method.
func (m *MockTicketRepository) FindByPassengerID(ctx context.Context, passengerID uuid.UUID) (*models.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByPassengerID", ctx, passengerID)
	ret0, _ := ret[0].(*models.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByPassengerID indicates an expected call of FindByPassengerID.
func (mr *MockTicketRepositoryMockRecorder) FindByPassengerID(ctx, passengerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByPassengerID", reflect.TypeOf((*MockTicketRepository)(nil).FindByPassengerID), ctx, passengerID)
}

// FindByTicketNumber mocks base method.
func (m *MockTicketRepository) FindByTicketNumber(ctx context.Context, number string) (*models.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTicketNumber", ctx, number)
	ret0, _ := ret[0].(*models.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTicketNumber indicates an expected call of FindByTicketNumber.
func (mr *MockTicketRepositoryMockRecorder) FindByTicketNumber(ctx, number interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTicketNumber", reflect.TypeOf((*MockTicketRepository)(nil).FindByTicketNumber), ctx, number)
}

// FindWithSegments mocks base method.
func (m *MockTicketRepository) FindWithSegments(ctx context.Context, id uuid.UUID) (*models.Ticket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWithSegments", ctx, id)
	ret0, _ := ret[0].(*models.Ticket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWithSegments indicates an expected call of FindWithSegments.
func (mr *MockTicketRepositoryMockRecorder) FindWithSegments(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWithSegments", reflect.TypeOf((*MockTicketRepository)(nil).FindWithSegments), ctx, id)
}
