// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/check_in_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "passenger_service_backend/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockCheckinRepository is a mock of CheckinRepository interface.
type MockCheckinRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCheckinRepositoryMockRecorder
}

// MockCheckinRepositoryMockRecorder is the mock recorder for MockCheckinRepository.
type MockCheckinRepositoryMockRecorder struct {
	mock *MockCheckinRepository
}

// NewMockCheckinRepository creates a new mock instance.
func NewMockCheckinRepository(ctrl *gomock.Controller) *MockCheckinRepository {
	mock := &MockCheckinRepository{ctrl: ctrl}
	mock.recorder = &MockCheckinRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCheckinRepository) EXPECT() *MockCheckinRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCheckinRepository) Create(ctx context.Context, checkin *models.Checkin) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, checkin)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCheckinRepositoryMockRecorder) Create(ctx, checkin interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCheckinRepository)(nil).Create), ctx, checkin)
}

// FindByID mocks base method.
func (m *MockCheckinRepository) FindByID(ctx context.Context, id uuid.UUID) (*models.Checkin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*models.Checkin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockCheckinRepositoryMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCheckinRepository)(nil).FindByID), ctx, id)
}

// FindByPassengerID mocks base method.
func (m *MockCheckinRepository) FindByPassengerID(ctx context.Context, passengerID uuid.UUID) ([]models.Checkin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByPassengerID", ctx, passengerID)
	ret0, _ := ret[0].([]models.Checkin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByPassengerID indicates an expected call of FindByPassengerID.
func (mr *MockCheckinRepositoryMockRecorder) FindByPassengerID(ctx, passengerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByPassengerID", reflect.TypeOf((*MockCheckinRepository)(nil).FindByPassengerID), ctx, passengerID)
}

// FindBySegmentID mocks base method.
func (m *MockCheckinRepository) FindBySegmentID(ctx context.Context, segmentID uuid.UUID) ([]models.Checkin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySegmentID", ctx, segmentID)
	ret0, _ := ret[0].([]models.Checkin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySegmentID indicates an expected call of FindBySegmentID.
func (mr *MockCheckinRepositoryMockRecorder) FindBySegmentID(ctx, segmentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySegmentID", reflect.TypeOf((*MockCheckinRepository)(nil).FindBySegmentID), ctx, segmentID)
}

// IsCheckedIn mocks base method.
func (m *MockCheckinRepository) IsCheckedIn(ctx context.Context, passengerID, segmentID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCheckedIn", ctx, passengerID, segmentID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsCheckedIn indicates an expected call of IsCheckedIn.
func (mr *MockCheckinRepositoryMockRecorder) IsCheckedIn(ctx, passengerID, segmentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCheckedIn", reflect.TypeOf((*MockCheckinRepository)(nil).IsCheckedIn), ctx, passengerID, segmentID)
}
