// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/rbac_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "passenger_service_backend/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockRBACService is a mock of RBACService interface.
type MockRBACService struct {
	ctrl     *gomock.Controller
	recorder *MockRBACServiceMockRecorder
}

// MockRBACServiceMockRecorder is the mock recorder for MockRBACService.
type MockRBACServiceMockRecorder struct {
	mock *MockRBACService
}

// NewMockRBACService creates a new mock instance.
func NewMockRBACService(ctrl *gomock.Controller) *MockRBACService {
	mock := &MockRBACService{ctrl: ctrl}
	mock.recorder = &MockRBACServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRBACService) EXPECT() *MockRBACServiceMockRecorder {
	return m.recorder
}

// CanManageUser mocks base method.
func (m *MockRBACService) CanManageUser(managerID, targetUserID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanManageUser", managerID, targetUserID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanManageUser indicates an expected call of CanManageUser.
func (mr *MockRBACServiceMockRecorder) CanManageUser(managerID, targetUserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanManageUser", reflect.TypeOf((*MockRBACService)(nil).CanManageUser), managerID, targetUserID)
}

// CheckPermission mocks base method.
func (m *MockRBACService) CheckPermission(uid uuid.UUID, resource, action string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPermission", uid, resource, action)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckPermission indicates an expected call of CheckPermission.
func (mr *MockRBACServiceMockRecorder) CheckPermission(uid, resource, action interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPermission", reflect.TypeOf((*MockRBACService)(nil).CheckPermission), uid, resource, action)
}

// CheckPermissionOrOwn mocks base method.
func (m *MockRBACService) CheckPermissionOrOwn(uid uuid.UUID, resource, action string, resourceID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPermissionOrOwn", uid, resource, action, resourceID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckPermissionOrOwn indicates an expected call of CheckPermissionOrOwn.
func (mr *MockRBACServiceMockRecorder) CheckPermissionOrOwn(uid, resource, action, resourceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPermissionOrOwn", reflect.TypeOf((*MockRBACService)(nil).CheckPermissionOrOwn), uid, resource, action, resourceID)
}

// GetUserRole mocks base method.
func (m *MockRBACService) GetUserRole(uid uuid.UUID) (*models.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRole", uid)
	ret0, _ := ret[0].(*models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRole indicates an expected call of GetUserRole.
func (mr *MockRBACServiceMockRecorder) GetUserRole(uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRole", reflect.TypeOf((*MockRBACService)(nil).GetUserRole), uid)
}

// HasExactRole mocks base method.
func (m *MockRBACService) HasExactRole(uid uuid.UUID, roleName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasExactRole", uid, roleName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasExactRole indicates an expected call of HasExactRole.
func (mr *MockRBACServiceMockRecorder) HasExactRole(uid, roleName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasExactRole", reflect.TypeOf((*MockRBACService)(nil).HasExactRole), uid, roleName)
}

// HasRole mocks base method.
func (m *MockRBACService) HasRole(uid uuid.UUID, roleName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasRole", uid, roleName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasRole indicates an expected call of HasRole.
func (mr *MockRBACServiceMockRecorder) HasRole(uid, roleName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasRole", reflect.TypeOf((*MockRBACService)(nil).HasRole), uid, roleName)
}
