// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/aircraft_seat_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "passenger_service_backend/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	gorm "gorm.io/gorm"
)

// MockAircraftSeatRepository is a mock of AircraftSeatRepository interface.
type MockAircraftSeatRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAircraftSeatRepositoryMockRecorder
}

// MockAircraftSeatRepositoryMockRecorder is the mock recorder for MockAircraftSeatRepository.
type MockAircraftSeatRepositoryMockRecorder struct {
	mock *MockAircraftSeatRepository
}

// NewMockAircraftSeatRepository creates a new mock instance.
func NewMockAircraftSeatRepository(ctrl *gomock.Controller) *MockAircraftSeatRepository {
	mock := &MockAircraftSeatRepository{ctrl: ctrl}
	mock.recorder = &MockAircraftSeatRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAircraftSeatRepository) EXPECT() *MockAircraftSeatRepositoryMockRecorder {
	return m.recorder
}

// BulkCreate mocks base method.
func (m *MockAircraftSeatRepository) BulkCreate(ctx context.Context, tx *gorm.DB, seats []models.AircraftSeat) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkCreate", ctx, tx, seats)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkCreate indicates an expected call of BulkCreate.
func (mr *MockAircraftSeatRepositoryMockRecorder) BulkCreate(ctx, tx, seats interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkCreate", reflect.TypeOf((*MockAircraftSeatRepository)(nil).BulkCreate), ctx, tx, seats)
}

// Delete mocks base method.
func (m *MockAircraftSeatRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAircraftSeatRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAircraftSeatRepository)(nil).Delete), ctx, id)
}

// FindByAircraftAndClass mocks base method.
func (m *MockAircraftSeatRepository) FindByAircraftAndClass(ctx context.Context, aircraftID uuid.UUID, classCode string) ([]models.AircraftSeat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByAircraftAndClass", ctx, aircraftID, classCode)
	ret0, _ := ret[0].([]models.AircraftSeat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByAircraftAndClass indicates an expected call of FindByAircraftAndClass.
func (mr *MockAircraftSeatRepositoryMockRecorder) FindByAircraftAndClass(ctx, aircraftID, classCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByAircraftAndClass", reflect.TypeOf((*MockAircraftSeatRepository)(nil).FindByAircraftAndClass), ctx, aircraftID, classCode)
}

// FindByAircraftID mocks base method.
func (m *MockAircraftSeatRepository) FindByAircraftID(ctx context.Context, aircraftID uuid.UUID) ([]models.AircraftSeat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByAircraftID", ctx, aircraftID)
	ret0, _ := ret[0].([]models.AircraftSeat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByAircraftID indicates an expected call of FindByAircraftID.
func (mr *MockAircraftSeatRepositoryMockRecorder) FindByAircraftID(ctx, aircraftID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByAircraftID", reflect.TypeOf((*MockAircraftSeatRepository)(nil).FindByAircraftID), ctx, aircraftID)
}

// FindByID mocks base method.
func (m *MockAircraftSeatRepository) FindByID(ctx context.Context, id uuid.UUID) (*models.AircraftSeat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*models.AircraftSeat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockAircraftSeatRepositoryMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockAircraftSeatRepository)(nil).FindByID), ctx, id)
}

// Update mocks base method.
func (m *MockAircraftSeatRepository) Update(ctx context.Context, seat *models.AircraftSeat) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, seat)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAircraftSeatRepositoryMockRecorder) Update(ctx, seat interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAircraftSeatRepository)(nil).Update), ctx, seat)
}
