// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/flight_schedule.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	dto "passenger_service_backend/internal/dto"
	models "passenger_service_backend/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockFlightScheduleService is a mock of FlightScheduleService interface.
type MockFlightScheduleService struct {
	ctrl     *gomock.Controller
	recorder *MockFlightScheduleServiceMockRecorder
}

// MockFlightScheduleServiceMockRecorder is the mock recorder for MockFlightScheduleService.
type MockFlightScheduleServiceMockRecorder struct {
	mock *MockFlightScheduleService
}

// NewMockFlightScheduleService creates a new mock instance.
func NewMockFlightScheduleService(ctrl *gomock.Controller) *MockFlightScheduleService {
	mock := &MockFlightScheduleService{ctrl: ctrl}
	mock.recorder = &MockFlightScheduleServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlightScheduleService) EXPECT() *MockFlightScheduleServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFlightScheduleService) Create(ctx context.Context, req dto.CreateFlightScheduleRequest) (*models.FlightSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*models.FlightSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockFlightScheduleServiceMockRecorder) Create(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFlightScheduleService)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockFlightScheduleService) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFlightScheduleServiceMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFlightScheduleService)(nil).Delete), ctx, id)
}

// GetAll mocks base method.
func (m *MockFlightScheduleService) GetAll(ctx context.Context) ([]models.FlightSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]models.FlightSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockFlightScheduleServiceMockRecorder) GetAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockFlightScheduleService)(nil).GetAll), ctx)
}

// GetByID mocks base method.
func (m *MockFlightScheduleService) GetByID(ctx context.Context, id uuid.UUID) (*models.FlightSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.FlightSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockFlightScheduleServiceMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockFlightScheduleService)(nil).GetByID), ctx, id)
}

// GetByRoute mocks base method.
func (m *MockFlightScheduleService) GetByRoute(ctx context.Context, depCode, arrCode string) ([]models.FlightSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRoute", ctx, depCode, arrCode)
	ret0, _ := ret[0].([]models.FlightSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRoute indicates an expected call of GetByRoute.
func (mr *MockFlightScheduleServiceMockRecorder) GetByRoute(ctx, depCode, arrCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRoute", reflect.TypeOf((*MockFlightScheduleService)(nil).GetByRoute), ctx, depCode, arrCode)
}

// Update mocks base method.
func (m *MockFlightScheduleService) Update(ctx context.Context, id uuid.UUID, req dto.UpdateFlightScheduleRequest) (*models.FlightSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(*models.FlightSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockFlightScheduleServiceMockRecorder) Update(ctx, id, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFlightScheduleService)(nil).Update), ctx, id, req)
}
