// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/baggage_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	dto "passenger_service_backend/internal/dto"
	models "passenger_service_backend/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockBaggageService is a mock of BaggageService interface.
type MockBaggageService struct {
	ctrl     *gomock.Controller
	recorder *MockBaggageServiceMockRecorder
}

// MockBaggageServiceMockRecorder is the mock recorder for MockBaggageService.
type MockBaggageServiceMockRecorder struct {
	mock *MockBaggageService
}

// NewMockBaggageService creates a new mock instance.
func NewMockBaggageService(ctrl *gomock.Controller) *MockBaggageService {
	mock := &MockBaggageService{ctrl: ctrl}
	mock.recorder = &MockBaggageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBaggageService) EXPECT() *MockBaggageServiceMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockBaggageService) Add(ctx context.Context, req dto.AddBaggageRequest) (*models.Baggage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, req)
	ret0, _ := ret[0].(*models.Baggage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockBaggageServiceMockRecorder) Add(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockBaggageService)(nil).Add), ctx, req)
}

// GetByPassenger mocks base method.
func (m *MockBaggageService) GetByPassenger(ctx context.Context, passengerID uuid.UUID) ([]models.Baggage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPassenger", ctx, passengerID)
	ret0, _ := ret[0].([]models.Baggage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPassenger indicates an expected call of GetByPassenger.
func (mr *MockBaggageServiceMockRecorder) GetByPassenger(ctx, passengerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPassenger", reflect.TypeOf((*MockBaggageService)(nil).GetByPassenger), ctx, passengerID)
}

// GetBySegment mocks base method.
func (m *MockBaggageService) GetBySegment(ctx context.Context, segmentID uuid.UUID) ([]models.Baggage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySegment", ctx, segmentID)
	ret0, _ := ret[0].([]models.Baggage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySegment indicates an expected call of GetBySegment.
func (mr *MockBaggageServiceMockRecorder) GetBySegment(ctx, segmentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySegment", reflect.TypeOf((*MockBaggageService)(nil).GetBySegment), ctx, segmentID)
}

// UpdateStatus mocks base method.
func (m *MockBaggageService) UpdateStatus(ctx context.Context, baggageID uuid.UUID, status models.BaggageStatus) (*models.Baggage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, baggageID, status)
	ret0, _ := ret[0].(*models.Baggage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockBaggageServiceMockRecorder) UpdateStatus(ctx, baggageID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockBaggageService)(nil).UpdateStatus), ctx, baggageID, status)
}
