// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/pnr_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "passenger_service_backend/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockPNRRepository is a mock of PNRRepository interface.
type MockPNRRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPNRRepositoryMockRecorder
}

// MockPNRRepositoryMockRecorder is the mock recorder for MockPNRRepository.
type MockPNRRepositoryMockRecorder struct {
	mock *MockPNRRepository
}

// NewMockPNRRepository creates a new mock instance.
func NewMockPNRRepository(ctrl *gomock.Controller) *MockPNRRepository {
	mock := &MockPNRRepository{ctrl: ctrl}
	mock.recorder = &MockPNRRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPNRRepository) EXPECT() *MockPNRRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPNRRepository) Create(ctx context.Context, pnr *models.PNR) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, pnr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPNRRepositoryMockRecorder) Create(ctx, pnr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPNRRepository)(nil).Create), ctx, pnr)
}

// FindAll mocks base method.
func (m *MockPNRRepository) FindAll(ctx context.Context, page, limit int) ([]models.PNR, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, page, limit)
	ret0, _ := ret[0].([]models.PNR)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAll indicates an expected call of FindAll.
func (mr *MockPNRRepositoryMockRecorder) FindAll(ctx, page, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockPNRRepository)(nil).FindAll), ctx, page, limit)
}

// FindByID mocks base method.
func (m *MockPNRRepository) FindByID(ctx context.Context, id uuid.UUID) (*models.PNR, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*models.PNR)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPNRRepositoryMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPNRRepository)(nil).FindByID), ctx, id)
}

// FindByLocator mocks base method.
func (m *MockPNRRepository) FindByLocator(ctx context.Context, locator string) (*models.PNR, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByLocator", ctx, locator)
	ret0, _ := ret[0].(*models.PNR)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByLocator indicates an expected call of FindByLocator.
func (mr *MockPNRRepositoryMockRecorder) FindByLocator(ctx, locator interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByLocator", reflect.TypeOf((*MockPNRRepository)(nil).FindByLocator), ctx, locator)
}

// FindWithFull mocks base method.
func (m *MockPNRRepository) FindWithFull(ctx context.Context, id uuid.UUID) (*models.PNR, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWithFull", ctx, id)
	ret0, _ := ret[0].(*models.PNR)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWithFull indicates an expected call of FindWithFull.
func (mr *MockPNRRepositoryMockRecorder) FindWithFull(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWithFull", reflect.TypeOf((*MockPNRRepository)(nil).FindWithFull), ctx, id)
}

// Update mocks base method.
func (m *MockPNRRepository) Update(ctx context.Context, pnr *models.PNR) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, pnr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPNRRepositoryMockRecorder) Update(ctx, pnr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPNRRepository)(nil).Update), ctx, pnr)
}

// UpdateStatus mocks base method.
func (m *MockPNRRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status models.PNRStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockPNRRepositoryMockRecorder) UpdateStatus(ctx, id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockPNRRepository)(nil).UpdateStatus), ctx, id, status)
}
