// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/meal_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "passenger_service_backend/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMealRepository is a mock of MealRepository interface.
type MockMealRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMealRepositoryMockRecorder
}

// MockMealRepositoryMockRecorder is the mock recorder for MockMealRepository.
type MockMealRepositoryMockRecorder struct {
	mock *MockMealRepository
}

// NewMockMealRepository creates a new mock instance.
func NewMockMealRepository(ctrl *gomock.Controller) *MockMealRepository {
	mock := &MockMealRepository{ctrl: ctrl}
	mock.recorder = &MockMealRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMealRepository) EXPECT() *MockMealRepositoryMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockMealRepository) FindAll(ctx context.Context) ([]models.Meal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]models.Meal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockMealRepositoryMockRecorder) FindAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockMealRepository)(nil).FindAll), ctx)
}

// FindByCode mocks base method.
func (m *MockMealRepository) FindByCode(ctx context.Context, code string) (*models.Meal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCode", ctx, code)
	ret0, _ := ret[0].(*models.Meal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCode indicates an expected call of FindByCode.
func (mr *MockMealRepositoryMockRecorder) FindByCode(ctx, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCode", reflect.TypeOf((*MockMealRepository)(nil).FindByCode), ctx, code)
}
