// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injection

import (
	"context"
	"github.com/google/wire"
	"gorm.io/gorm"
	"passenger_service_backend/internal/cache"
	"passenger_service_backend/internal/config"
	"passenger_service_backend/internal/db"
	"passenger_service_backend/internal/handler"
	"passenger_service_backend/internal/repository"
	"passenger_service_backend/internal/services"
	"passenger_service_backend/internal/utils"
)

// Injectors from wire.go:

func InitializeAllHandler(cfg *config.Config, ctx context.Context) (*Handler, error) {
	db := ProvideDB()
	aircraftRepositoryImpl := repository.NewAircraftRepository(db)
	client, err := ProvideCache(cfg)
	if err != nil {
		return nil, err
	}
	cachedAircraftRepository := repository.NewCachedAircraftRepository(aircraftRepositoryImpl, client)
	aircraftSeatRepository := repository.NewAircraftSeatRepository(db)
	seatClassRepository := repository.NewSeatClassRepository(db)
	aircraftService := services.NewAircraftService(cachedAircraftRepository, aircraftSeatRepository, seatClassRepository)
	aircraftHandler := handler.NewAircraftHandler(aircraftService)
	airportRepositoryImpl := repository.NewAirportRepository(db)
	cachedAirportRepository := repository.NewCachedAirportRepository(airportRepositoryImpl, client)
	airportService := services.NewAirportService(cachedAirportRepository)
	airportHandler := handler.NewAirportHandler(airportService)
	userRepository := repository.NewUserReposiory(db)
	roleRepository := repository.NewRoleRepository(db)
	jwtService := ProvideJWTService(cfg)
	authService := services.NewAuthService(userRepository, roleRepository, jwtService)
	authHandler := handler.NewAuthHandler(authService, ctx)
	baggageRepository := repository.NewBaggageRepository(db)
	checkinRepository := repository.NewCheckinRepository(db)
	pnrPassengerRepository := repository.NewPNRPassengerRepository(db)
	baggageService := services.NewBaggageService(baggageRepository, checkinRepository, pnrPassengerRepository)
	baggageHandler := handler.NewBaggageHandler(baggageService)
	boardingPassRepository := repository.NewBoardingPassRepository(db)
	pnrSegmentRepository := repository.NewPNRSegmentRepository(db)
	seatAssignmentRepository := repository.NewSeatAssignmentRepository(db)
	boardingPassService := services.NewBoardingPassService(boardingPassRepository, checkinRepository, pnrPassengerRepository, pnrSegmentRepository, seatAssignmentRepository)
	boardingPassHandler := handler.NewBoardingPassHandler(boardingPassService)
	pnrRepositoryImpl := repository.NewPNRRepository(db)
	cachedPNRRepository := repository.NewCachedPNRRepository(pnrRepositoryImpl, client)
	pnrContactRepository := repository.NewPNRContactRepository(db)
	flightRepositoryImpl := repository.NewFlightRepository(db)
	cachedFlightRepository := repository.NewCachedFlightRepository(flightRepositoryImpl, client)
	flightSeatRepositoryImpl := repository.NewFlightSeatRepository(db)
	cachedFlightSeatRepository := repository.NewCachedFlightSeatRepository(flightSeatRepositoryImpl, client)
	seatLockRepository := repository.NewSeatLockRepository(db)
	ssrTypeRepository := repository.NewSSRTypeRepository(db)
	passengerSSRRepository := repository.NewPassengerSSRRepository(db)
	mealRepository := repository.NewMealRepository(db)
	passengerMealRepository := repository.NewPassengerMealRepository(db)
	bookingService := services.NewBookingService(db, cachedPNRRepository, pnrContactRepository, pnrPassengerRepository, pnrSegmentRepository, cachedFlightRepository, cachedFlightSeatRepository, seatLockRepository, seatAssignmentRepository, ssrTypeRepository, passengerSSRRepository, mealRepository, passengerMealRepository)
	bookingHandler := handler.NewBookingHandler(bookingService)
	ticketRepository := repository.NewTicketRepository(db)
	checkinService := services.NewCheckinService(checkinRepository, pnrPassengerRepository, pnrSegmentRepository, ticketRepository, cachedFlightRepository, seatAssignmentRepository)
	checkinHandler := handler.NewCheckinHandler(checkinService)
	flightScheduleRepositoryImpl := repository.NewFlightScheduleRepository(db)
	cachedFlightScheduleRepository := repository.NewCachedFlightScheduleRepository(flightScheduleRepositoryImpl, client)
	flightService := services.NewFlightService(cachedFlightRepository, cachedFlightSeatRepository, cachedFlightScheduleRepository, cachedAirportRepository, cachedAircraftRepository, aircraftSeatRepository)
	flightHandler := handler.NewFlightHandler(flightService)
	flightScheduleService := services.NewFlightScheduleService(cachedFlightScheduleRepository, cachedAirportRepository)
	flightScheduleHandler := handler.NewFlightScheduleHandler(flightScheduleService)
	paymentRepository := repository.NewPaymentRepository(db)
	ticketSegmentRepository := repository.NewTicketSegmentRepository(db)
	ticketService := services.NewTicketService(ticketRepository, ticketSegmentRepository, cachedPNRRepository, pnrPassengerRepository, pnrSegmentRepository, cachedFlightSeatRepository)
	paymentService := services.NewPaymentService(paymentRepository, cachedPNRRepository, cachedFlightSeatRepository, ticketService)
	paymentHandler := handler.NewPaymentHandler(paymentService)
	permissionRepository := repository.NewPermissionRepository(db)
	roleService := services.NewRoleService(roleRepository, permissionRepository)
	roleHandler := handler.NewRoleHandler(roleService)
	userService := services.NewUserService(userRepository, roleRepository)
	userHandler := handler.NewUserHandler(userService)
	dashboardRepository := repository.NewDashboardRepository(db)
	dashboardService := services.NewDashboardService(dashboardRepository)
	dashboardHandler := handler.NewDashboardHandler(dashboardService)
	rbacRepositoryImpl := repository.NewRBACRepository(db)
	cachedRBACRepository := repository.NewCachedRBACRepository(rbacRepositoryImpl, client)
	rbacService := services.NewRBACService(cachedRBACRepository)
	injectionHandler := NewHandler(aircraftHandler, airportHandler, authHandler, baggageHandler, boardingPassHandler, bookingHandler, checkinHandler, flightHandler, flightScheduleHandler, paymentHandler, roleHandler, userHandler, dashboardHandler, rbacService, userService, jwtService)
	return injectionHandler, nil
}

// wire.go:

func ProvideDB() *gorm.DB {
	return db.DB
}

func ProvideJWTService(cfg *config.Config) *utils.JWTService {
	return utils.NewJWTService(cfg)
}

func ProvideCache(cfg *config.Config) (*cache.Client, error) {
	return cache.New(cache.Config{
		Host:     cfg.Redis.Host,
		Port:     cfg.Redis.Port,
		Password: cfg.Redis.Password,
		DB:       cfg.Redis.DB,
	})
}

var repositorySet = wire.NewSet(
	ProvideDB, repository.NewAircraftRepository, repository.NewAirportRepository, repository.NewAircraftSeatRepository, repository.NewBaggageRepository, repository.NewBoardingPassRepository, repository.NewCheckinRepository, repository.NewPaymentRepository, repository.NewPermissionRepository, repository.NewRBACRepository, repository.NewFlightRepository, repository.NewFlightSeatRepository, repository.NewFlightScheduleRepository, repository.NewMealRepository, repository.NewUserReposiory, repository.NewPassengerMealRepository, repository.NewPassengerSSRRepository, repository.NewRoleRepository, repository.NewPNRContactRepository, repository.NewPNRPassengerRepository, repository.NewPNRRepository, repository.NewPNRSegmentRepository, repository.NewSeatAssignmentRepository, repository.NewSeatClassRepository, repository.NewSeatLockRepository, repository.NewSSRTypeRepository, repository.NewTicketRepository, repository.NewTicketSegmentRepository, repository.NewDashboardRepository, repository.NewCachedAircraftRepository, repository.NewCachedAirportRepository, repository.NewCachedRBACRepository, repository.NewCachedFlightRepository, repository.NewCachedFlightSeatRepository, repository.NewCachedFlightScheduleRepository, repository.NewCachedPNRRepository, wire.Bind(new(repository.AircraftRepository), new(*repository.CachedAircraftRepository)), wire.Bind(new(repository.AirportRepository), new(*repository.CachedAirportRepository)), wire.Bind(new(repository.RBACRepository), new(*repository.CachedRBACRepository)), wire.Bind(new(repository.FlightRepository), new(*repository.CachedFlightRepository)), wire.Bind(new(repository.FlightSeatRepository), new(*repository.CachedFlightSeatRepository)), wire.Bind(new(repository.FlightScheduleRepository), new(*repository.CachedFlightScheduleRepository)), wire.Bind(new(repository.PNRRepository), new(*repository.CachedPNRRepository)),
)

var utilsSet = wire.NewSet(
	ProvideJWTService,
	ProvideCache,
)

var serviceSet = wire.NewSet(services.NewAircraftService, services.NewAirportService, services.NewAuthService, services.NewBaggageService, services.NewBoardingPassService, services.NewBookingService, services.NewCheckinService, services.NewFlightScheduleService, services.NewFlightService, services.NewPaymentService, services.NewRBACService, services.NewRoleService, services.NewSeatLockService, services.NewTicketService, services.NewUserService, services.NewDashboardService)

var handlerSet = wire.NewSet(handler.NewAircraftHandler, handler.NewAirportHandler, handler.NewAuthHandler, handler.NewBaggageHandler, handler.NewBoardingPassHandler, handler.NewBookingHandler, handler.NewCheckinHandler, handler.NewFlightHandler, handler.NewFlightScheduleHandler, handler.NewPaymentHandler, handler.NewUserHandler, handler.NewRoleHandler, handler.NewDashboardHandler)

type Handler struct {
	AircraftHandler       *handler.AircraftHandler
	AirportHandler        *handler.AirportHandler
	AuthHandler           *handler.AuthHandler
	BaggageHandler        *handler.BaggageHandler
	BoardingPassHandler   *handler.BoardingPassHandler
	BookingHandler        *handler.BookingHandler
	CheckinHandler        *handler.CheckinHandler
	FlightHandler         *handler.FlightHandler
	FlightScheduleHandler *handler.FlightScheduleHandler
	PaymentHandler        *handler.PaymentHandler
	RoleHandler           *handler.RoleHandler
	UserHandler           *handler.UserHandler
	DashboardHandler      *handler.DashboardHandler

	RBACService services.RBACService
	UserService services.UserService
	JWTService  *utils.JWTService
}

func NewHandler(
	aircraftHandler *handler.AircraftHandler,
	airportHandler *handler.AirportHandler,
	authHandler *handler.AuthHandler,
	baggageHandler *handler.BaggageHandler,
	boardingPassHandler *handler.BoardingPassHandler,
	bookingHandler *handler.BookingHandler,
	checkinHandler *handler.CheckinHandler,
	flightHandler *handler.FlightHandler,
	flightScheduleHandler *handler.FlightScheduleHandler,
	paymentHandler *handler.PaymentHandler,
	roleHandler *handler.RoleHandler,
	userHandler *handler.UserHandler,
	dashboardHandler *handler.DashboardHandler,
	rbacService services.RBACService,
	userService services.UserService,
	jwtService *utils.JWTService,
) *Handler {
	return &Handler{
		AircraftHandler:       aircraftHandler,
		AirportHandler:        airportHandler,
		AuthHandler:           authHandler,
		BaggageHandler:        baggageHandler,
		BoardingPassHandler:   boardingPassHandler,
		BookingHandler:        bookingHandler,
		CheckinHandler:        checkinHandler,
		FlightHandler:         flightHandler,
		FlightScheduleHandler: flightScheduleHandler,
		PaymentHandler:        paymentHandler,
		UserHandler:           userHandler,
		RoleHandler:           roleHandler,
		DashboardHandler:      dashboardHandler,
		RBACService:           rbacService,
		UserService:           userService,
		JWTService:            jwtService,
	}
}
