// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injection

import (
	"context"
	"github.com/google/wire"
	"gorm.io/gorm"
	"passenger_service_backend/internal/config"
	"passenger_service_backend/internal/db"
	"passenger_service_backend/internal/handler"
	"passenger_service_backend/internal/repository"
	"passenger_service_backend/internal/services"
	"passenger_service_backend/internal/utils"
)

// Injectors from wire.go:

// InitializeAllHandler initializes all handler with config
func InitializeAllHandler(config2 *config.Config, ctx context.Context) *Handler {
	aircraftRepository := repository.NewAircraftRepository()
	aircraftSeatRepository := repository.NewAircraftSeatRepository()
	db := ProvideDB()
	seatClassRepository := repository.NewSeatClassRepository(db)
	aircraftService := services.NewAircraftService(aircraftRepository, aircraftSeatRepository, seatClassRepository)
	aircraftHandler := handler.NewAircraftHandler(aircraftService)
	airportRepository := repository.NewAirportRepository()
	airportService := services.NewAirportService(airportRepository)
	airportHandler := handler.NewAirportHandler(airportService)
	userRepository := repository.NewUserReposiory()
	jwtService := ProvideJWTService(config2)
	authService := services.NewAuthService(userRepository, jwtService)
	authHandler := handler.NewAuthHandler(authService, ctx)
	baggageRepository := repository.NewBaggageRepository()
	checkinRepository := repository.NewCheckinRepository()
	pnrPassengerRepository := repository.NewPNRPassengerRepository()
	baggageService := services.NewBaggageService(baggageRepository, checkinRepository, pnrPassengerRepository)
	baggageHandler := handler.NewBaggageHandler(baggageService)
	boardingPassRepository := repository.NewBoardingPassRepository()
	pnrSegmentRepository := repository.NewPNRSegmentRepository()
	seatAssignmentRepository := repository.NewSeatAssignmentRepository()
	boardingPassService := services.NewBoardingPassService(boardingPassRepository, checkinRepository, pnrPassengerRepository, pnrSegmentRepository, seatAssignmentRepository)
	boardingPassHandler := handler.NewBoardingPassHandler(boardingPassService)
	pnrRepository := repository.NewPNRRepository()
	pnrContactRepository := repository.NewPNRContactRepository()
	flightRepository := repository.NewFlightRepository()
	flightSeatRepository := repository.NewFlightSeatRepository()
	seatLockRepository := repository.NewSeatLockRepository()
	ssrTypeRepository := repository.NewSSRTypeRepository()
	passengerSSRRepository := repository.NewPassengerSSRRepository()
	mealRepository := repository.NewMealRepository()
	passengerMealRepository := repository.NewPassengerMealRepository()
	bookingService := services.NewBookingService(db, pnrRepository, pnrContactRepository, pnrPassengerRepository, pnrSegmentRepository, flightRepository, flightSeatRepository, seatLockRepository, seatAssignmentRepository, ssrTypeRepository, passengerSSRRepository, mealRepository, passengerMealRepository)
	bookingHandler := handler.NewBookingHandler(bookingService)
	ticketRepository := repository.NewTicketRepository()
	checkinService := services.NewCheckinService(checkinRepository, pnrPassengerRepository, pnrSegmentRepository, ticketRepository, flightRepository, seatAssignmentRepository)
	checkinHandler := handler.NewCheckinHandler(checkinService)
	flightScheduleRepository := repository.NewFlightScheduleRepository()
	flightService := services.NewFlightService(flightRepository, flightSeatRepository, flightScheduleRepository, airportRepository, aircraftRepository, aircraftSeatRepository)
	flightHandler := handler.NewFlightHandler(flightService)
	flightScheduleService := services.NewFlightScheduleService(flightScheduleRepository, airportRepository)
	flightScheduleHandler := handler.NewFlightScheduleHandler(flightScheduleService)
	paymentRepository := repository.NewPaymentRepository()
	ticketSegmentRepository := repository.NewTicketSegmentRepository()
	ticketService := services.NewTicketService(ticketRepository, ticketSegmentRepository, pnrRepository, pnrPassengerRepository, pnrSegmentRepository, flightSeatRepository)
	paymentService := services.NewPaymentService(paymentRepository, pnrRepository, flightSeatRepository, ticketService)
	paymentHandler := handler.NewPaymentHandler(paymentService)
	roleRepository := repository.NewRoleRepository()
	permissionRepository := repository.NewPermissionRepository()
	roleService := services.NewRoleService(roleRepository, permissionRepository)
	roleHandler := handler.NewRoleHandler(roleService)
	userService := services.NewUserService(userRepository, roleRepository)
	userHandler := handler.NewUserHandler(userService)
	rbacRepository := repository.NewRBACRepository(db)
	rbacService := services.NewRBACService(rbacRepository)
	injectionHandler := NewHandler(aircraftHandler, airportHandler, authHandler, baggageHandler, boardingPassHandler, bookingHandler, checkinHandler, flightHandler, flightScheduleHandler, paymentHandler, roleHandler, userHandler, rbacService, userService, jwtService)
	return injectionHandler
}

// wire.go:

// ProvideDB provides database connection
func ProvideDB() *gorm.DB {
	return db.DB
}

// ProvideJWTService provides JWT service instance with config
func ProvideJWTService(config2 *config.Config) *utils.JWTService {
	return utils.NewJWTService(config2)
}

// Repository Providers
var repositorySet = wire.NewSet(
	ProvideDB, repository.NewAircraftRepository, repository.NewAirportRepository, repository.NewAircraftSeatRepository, repository.NewBaggageRepository, repository.NewBoardingPassRepository, repository.NewCheckinRepository, repository.NewPaymentRepository, repository.NewPermissionRepository, repository.NewRBACRepository, repository.NewFlightRepository, repository.NewFlightSeatRepository, repository.NewFlightScheduleRepository, repository.NewMealRepository, repository.NewUserReposiory, repository.NewPassengerMealRepository, repository.NewPassengerSSRRepository, repository.NewRoleRepository, repository.NewPNRContactRepository, repository.NewPNRPassengerRepository, repository.NewPNRRepository, repository.NewPNRSegmentRepository, repository.NewSeatAssignmentRepository, repository.NewSeatClassRepository, repository.NewSeatLockRepository, repository.NewSSRTypeRepository, repository.NewTicketRepository, repository.NewTicketSegmentRepository,
)

// Service Providers
var serviceSet = wire.NewSet(services.NewAircraftService, services.NewAirportService, services.NewAuthService, services.NewBaggageService, services.NewBoardingPassService, services.NewBookingService, services.NewCheckinService, services.NewFlightScheduleService, services.NewFlightService, services.NewPaymentService, services.NewRBACService, services.NewRoleService, services.NewSeatLockService, services.NewTicketService, services.NewUserService)

// Utils Providers
var utilsSet = wire.NewSet(
	ProvideJWTService,
)

// Handler Providers
var handlerSet = wire.NewSet(handler.NewAircraftHandler, handler.NewAirportHandler, handler.NewAuthHandler, handler.NewBaggageHandler, handler.NewBoardingPassHandler, handler.NewBookingHandler, handler.NewCheckinHandler, handler.NewFlightHandler, handler.NewFlightScheduleHandler, handler.NewPaymentHandler, handler.NewUserHandler, handler.NewRoleHandler)

// Handler struct contains all handler and services
type Handler struct {
	AircraftHandler       *handler.AircraftHandler
	AirportHandler        *handler.AirportHandler
	AuthHandler           *handler.AuthHandler
	BaggageHandler        *handler.BaggageHandler
	BoardingPassHandler   *handler.BoardingPassHandler
	BookingHandler        *handler.BookingHandler
	CheckinHandler        *handler.CheckinHandler
	FlightHandler         *handler.FlightHandler
	FlightScheduleHandler *handler.FlightScheduleHandler
	PaymentHandler        *handler.PaymentHandler
	RoleHandler           *handler.RoleHandler
	UserHandler           *handler.UserHandler

	RBACService services.RBACService
	UserService services.UserService
	JWTService  *utils.JWTService
}

// NewHandler creates new Handler instance
func NewHandler(
	aircraftHandler *handler.AircraftHandler,
	airportHandler *handler.AirportHandler,
	authHandler *handler.AuthHandler,
	baggageHandler *handler.BaggageHandler,
	boardingPassHandler *handler.BoardingPassHandler,
	bookingHandler *handler.BookingHandler,
	checkinHandler *handler.CheckinHandler,
	flightHandler *handler.FlightHandler,
	flightScheduleHandler *handler.FlightScheduleHandler,
	paymentHandler *handler.PaymentHandler,
	roleHandler *handler.RoleHandler,
	userHandler *handler.UserHandler,
	rbacService services.RBACService,
	userService services.UserService,
	jwtService *utils.JWTService,
) *Handler {
	return &Handler{
		AircraftHandler:       aircraftHandler,
		AirportHandler:        airportHandler,
		AuthHandler:           authHandler,
		BaggageHandler:        baggageHandler,
		BoardingPassHandler:   boardingPassHandler,
		BookingHandler:        bookingHandler,
		CheckinHandler:        checkinHandler,
		FlightHandler:         flightHandler,
		FlightScheduleHandler: flightScheduleHandler,
		PaymentHandler:        paymentHandler,
		UserHandler:           userHandler,
		RoleHandler:           roleHandler,
		RBACService:           rbacService,
		UserService:           userService,
		JWTService:            jwtService,
	}
}
