// Code generated by ent, DO NOT EDIT.

package seats

import (
	"pasengger_service/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Seats {
	return predicate.Seats(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Seats {
	return predicate.Seats(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Seats {
	return predicate.Seats(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Seats {
	return predicate.Seats(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Seats {
	return predicate.Seats(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Seats {
	return predicate.Seats(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Seats {
	return predicate.Seats(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Seats {
	return predicate.Seats(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Seats {
	return predicate.Seats(sql.FieldLTE(FieldID, id))
}

// SeatNumber applies equality check predicate on the "seat_number" field. It's identical to SeatNumberEQ.
func SeatNumber(v string) predicate.Seats {
	return predicate.Seats(sql.FieldEQ(FieldSeatNumber, v))
}

// SeatClass applies equality check predicate on the "seat_class" field. It's identical to SeatClassEQ.
func SeatClass(v string) predicate.Seats {
	return predicate.Seats(sql.FieldEQ(FieldSeatClass, v))
}

// SeatNumberEQ applies the EQ predicate on the "seat_number" field.
func SeatNumberEQ(v string) predicate.Seats {
	return predicate.Seats(sql.FieldEQ(FieldSeatNumber, v))
}

// SeatNumberNEQ applies the NEQ predicate on the "seat_number" field.
func SeatNumberNEQ(v string) predicate.Seats {
	return predicate.Seats(sql.FieldNEQ(FieldSeatNumber, v))
}

// SeatNumberIn applies the In predicate on the "seat_number" field.
func SeatNumberIn(vs ...string) predicate.Seats {
	return predicate.Seats(sql.FieldIn(FieldSeatNumber, vs...))
}

// SeatNumberNotIn applies the NotIn predicate on the "seat_number" field.
func SeatNumberNotIn(vs ...string) predicate.Seats {
	return predicate.Seats(sql.FieldNotIn(FieldSeatNumber, vs...))
}

// SeatNumberGT applies the GT predicate on the "seat_number" field.
func SeatNumberGT(v string) predicate.Seats {
	return predicate.Seats(sql.FieldGT(FieldSeatNumber, v))
}

// SeatNumberGTE applies the GTE predicate on the "seat_number" field.
func SeatNumberGTE(v string) predicate.Seats {
	return predicate.Seats(sql.FieldGTE(FieldSeatNumber, v))
}

// SeatNumberLT applies the LT predicate on the "seat_number" field.
func SeatNumberLT(v string) predicate.Seats {
	return predicate.Seats(sql.FieldLT(FieldSeatNumber, v))
}

// SeatNumberLTE applies the LTE predicate on the "seat_number" field.
func SeatNumberLTE(v string) predicate.Seats {
	return predicate.Seats(sql.FieldLTE(FieldSeatNumber, v))
}

// SeatNumberContains applies the Contains predicate on the "seat_number" field.
func SeatNumberContains(v string) predicate.Seats {
	return predicate.Seats(sql.FieldContains(FieldSeatNumber, v))
}

// SeatNumberHasPrefix applies the HasPrefix predicate on the "seat_number" field.
func SeatNumberHasPrefix(v string) predicate.Seats {
	return predicate.Seats(sql.FieldHasPrefix(FieldSeatNumber, v))
}

// SeatNumberHasSuffix applies the HasSuffix predicate on the "seat_number" field.
func SeatNumberHasSuffix(v string) predicate.Seats {
	return predicate.Seats(sql.FieldHasSuffix(FieldSeatNumber, v))
}

// SeatNumberEqualFold applies the EqualFold predicate on the "seat_number" field.
func SeatNumberEqualFold(v string) predicate.Seats {
	return predicate.Seats(sql.FieldEqualFold(FieldSeatNumber, v))
}

// SeatNumberContainsFold applies the ContainsFold predicate on the "seat_number" field.
func SeatNumberContainsFold(v string) predicate.Seats {
	return predicate.Seats(sql.FieldContainsFold(FieldSeatNumber, v))
}

// SeatClassEQ applies the EQ predicate on the "seat_class" field.
func SeatClassEQ(v string) predicate.Seats {
	return predicate.Seats(sql.FieldEQ(FieldSeatClass, v))
}

// SeatClassNEQ applies the NEQ predicate on the "seat_class" field.
func SeatClassNEQ(v string) predicate.Seats {
	return predicate.Seats(sql.FieldNEQ(FieldSeatClass, v))
}

// SeatClassIn applies the In predicate on the "seat_class" field.
func SeatClassIn(vs ...string) predicate.Seats {
	return predicate.Seats(sql.FieldIn(FieldSeatClass, vs...))
}

// SeatClassNotIn applies the NotIn predicate on the "seat_class" field.
func SeatClassNotIn(vs ...string) predicate.Seats {
	return predicate.Seats(sql.FieldNotIn(FieldSeatClass, vs...))
}

// SeatClassGT applies the GT predicate on the "seat_class" field.
func SeatClassGT(v string) predicate.Seats {
	return predicate.Seats(sql.FieldGT(FieldSeatClass, v))
}

// SeatClassGTE applies the GTE predicate on the "seat_class" field.
func SeatClassGTE(v string) predicate.Seats {
	return predicate.Seats(sql.FieldGTE(FieldSeatClass, v))
}

// SeatClassLT applies the LT predicate on the "seat_class" field.
func SeatClassLT(v string) predicate.Seats {
	return predicate.Seats(sql.FieldLT(FieldSeatClass, v))
}

// SeatClassLTE applies the LTE predicate on the "seat_class" field.
func SeatClassLTE(v string) predicate.Seats {
	return predicate.Seats(sql.FieldLTE(FieldSeatClass, v))
}

// SeatClassContains applies the Contains predicate on the "seat_class" field.
func SeatClassContains(v string) predicate.Seats {
	return predicate.Seats(sql.FieldContains(FieldSeatClass, v))
}

// SeatClassHasPrefix applies the HasPrefix predicate on the "seat_class" field.
func SeatClassHasPrefix(v string) predicate.Seats {
	return predicate.Seats(sql.FieldHasPrefix(FieldSeatClass, v))
}

// SeatClassHasSuffix applies the HasSuffix predicate on the "seat_class" field.
func SeatClassHasSuffix(v string) predicate.Seats {
	return predicate.Seats(sql.FieldHasSuffix(FieldSeatClass, v))
}

// SeatClassEqualFold applies the EqualFold predicate on the "seat_class" field.
func SeatClassEqualFold(v string) predicate.Seats {
	return predicate.Seats(sql.FieldEqualFold(FieldSeatClass, v))
}

// SeatClassContainsFold applies the ContainsFold predicate on the "seat_class" field.
func SeatClassContainsFold(v string) predicate.Seats {
	return predicate.Seats(sql.FieldContainsFold(FieldSeatClass, v))
}

// HasAircraft applies the HasEdge predicate on the "aircraft" edge.
func HasAircraft() predicate.Seats {
	return predicate.Seats(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AircraftTable, AircraftColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAircraftWith applies the HasEdge predicate on the "aircraft" edge with a given conditions (other predicates).
func HasAircraftWith(preds ...predicate.Aircraft) predicate.Seats {
	return predicate.Seats(func(s *sql.Selector) {
		step := newAircraftStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasFlightInstances applies the HasEdge predicate on the "flight_instances" edge.
func HasFlightInstances() predicate.Seats {
	return predicate.Seats(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, FlightInstancesTable, FlightInstancesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFlightInstancesWith applies the HasEdge predicate on the "flight_instances" edge with a given conditions (other predicates).
func HasFlightInstancesWith(preds ...predicate.FlightSeat) predicate.Seats {
	return predicate.Seats(func(s *sql.Selector) {
		step := newFlightInstancesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Seats) predicate.Seats {
	return predicate.Seats(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Seats) predicate.Seats {
	return predicate.Seats(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Seats) predicate.Seats {
	return predicate.Seats(sql.NotPredicates(p))
}
