// Code generated by ent, DO NOT EDIT.

package passenger

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the passenger type in the database.
	Label = "passenger"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFirstName holds the string denoting the first_name field in the database.
	FieldFirstName = "first_name"
	// FieldLastName holds the string denoting the last_name field in the database.
	FieldLastName = "last_name"
	// FieldDateOfBirth holds the string denoting the date_of_birth field in the database.
	FieldDateOfBirth = "date_of_birth"
	// FieldPassportNumber holds the string denoting the passport_number field in the database.
	FieldPassportNumber = "passport_number"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeBookingEntries holds the string denoting the booking_entries edge name in mutations.
	EdgeBookingEntries = "booking_entries"
	// Table holds the table name of the passenger in the database.
	Table = "passengers"
	// BookingEntriesTable is the table that holds the booking_entries relation/edge.
	BookingEntriesTable = "booking_passengers"
	// BookingEntriesInverseTable is the table name for the BookingPassenger entity.
	// It exists in this package in order to avoid circular dependency with the "bookingpassenger" package.
	BookingEntriesInverseTable = "booking_passengers"
	// BookingEntriesColumn is the table column denoting the booking_entries relation/edge.
	BookingEntriesColumn = "passenger_booking_entries"
)

// Columns holds all SQL columns for passenger fields.
var Columns = []string{
	FieldID,
	FieldFirstName,
	FieldLastName,
	FieldDateOfBirth,
	FieldPassportNumber,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Passenger queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByFirstName orders the results by the first_name field.
func ByFirstName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstName, opts...).ToFunc()
}

// ByLastName orders the results by the last_name field.
func ByLastName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastName, opts...).ToFunc()
}

// ByDateOfBirth orders the results by the date_of_birth field.
func ByDateOfBirth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateOfBirth, opts...).ToFunc()
}

// ByPassportNumber orders the results by the passport_number field.
func ByPassportNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassportNumber, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByBookingEntriesCount orders the results by booking_entries count.
func ByBookingEntriesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBookingEntriesStep(), opts...)
	}
}

// ByBookingEntries orders the results by booking_entries terms.
func ByBookingEntries(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBookingEntriesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newBookingEntriesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BookingEntriesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BookingEntriesTable, BookingEntriesColumn),
	)
}
