// Code generated by ent, DO NOT EDIT.

package flight

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the flight type in the database.
	Label = "flight"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFlightNumber holds the string denoting the flight_number field in the database.
	FieldFlightNumber = "flight_number"
	// FieldDepartureTime holds the string denoting the departure_time field in the database.
	FieldDepartureTime = "departure_time"
	// FieldArrivalTime holds the string denoting the arrival_time field in the database.
	FieldArrivalTime = "arrival_time"
	// FieldBasePrice holds the string denoting the base_price field in the database.
	FieldBasePrice = "base_price"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeAircraft holds the string denoting the aircraft edge name in mutations.
	EdgeAircraft = "aircraft"
	// EdgeDepartureAirport holds the string denoting the departure_airport edge name in mutations.
	EdgeDepartureAirport = "departure_airport"
	// EdgeArrivalAirport holds the string denoting the arrival_airport edge name in mutations.
	EdgeArrivalAirport = "arrival_airport"
	// EdgeFlightSeats holds the string denoting the flight_seats edge name in mutations.
	EdgeFlightSeats = "flight_seats"
	// EdgeBookings holds the string denoting the bookings edge name in mutations.
	EdgeBookings = "bookings"
	// Table holds the table name of the flight in the database.
	Table = "flights"
	// AircraftTable is the table that holds the aircraft relation/edge.
	AircraftTable = "flights"
	// AircraftInverseTable is the table name for the Aircraft entity.
	// It exists in this package in order to avoid circular dependency with the "aircraft" package.
	AircraftInverseTable = "aircrafts"
	// AircraftColumn is the table column denoting the aircraft relation/edge.
	AircraftColumn = "aircraft_flights"
	// DepartureAirportTable is the table that holds the departure_airport relation/edge.
	DepartureAirportTable = "flights"
	// DepartureAirportInverseTable is the table name for the Airport entity.
	// It exists in this package in order to avoid circular dependency with the "airport" package.
	DepartureAirportInverseTable = "airports"
	// DepartureAirportColumn is the table column denoting the departure_airport relation/edge.
	DepartureAirportColumn = "airport_departures"
	// ArrivalAirportTable is the table that holds the arrival_airport relation/edge.
	ArrivalAirportTable = "flights"
	// ArrivalAirportInverseTable is the table name for the Airport entity.
	// It exists in this package in order to avoid circular dependency with the "airport" package.
	ArrivalAirportInverseTable = "airports"
	// ArrivalAirportColumn is the table column denoting the arrival_airport relation/edge.
	ArrivalAirportColumn = "airport_arrivals"
	// FlightSeatsTable is the table that holds the flight_seats relation/edge.
	FlightSeatsTable = "flight_seats"
	// FlightSeatsInverseTable is the table name for the FlightSeat entity.
	// It exists in this package in order to avoid circular dependency with the "flightseat" package.
	FlightSeatsInverseTable = "flight_seats"
	// FlightSeatsColumn is the table column denoting the flight_seats relation/edge.
	FlightSeatsColumn = "flight_flight_seats"
	// BookingsTable is the table that holds the bookings relation/edge.
	BookingsTable = "bookings"
	// BookingsInverseTable is the table name for the Booking entity.
	// It exists in this package in order to avoid circular dependency with the "booking" package.
	BookingsInverseTable = "bookings"
	// BookingsColumn is the table column denoting the bookings relation/edge.
	BookingsColumn = "flight_bookings"
)

// Columns holds all SQL columns for flight fields.
var Columns = []string{
	FieldID,
	FieldFlightNumber,
	FieldDepartureTime,
	FieldArrivalTime,
	FieldBasePrice,
	FieldStatus,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "flights"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"aircraft_flights",
	"airport_departures",
	"airport_arrivals",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Flight queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByFlightNumber orders the results by the flight_number field.
func ByFlightNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFlightNumber, opts...).ToFunc()
}

// ByDepartureTime orders the results by the departure_time field.
func ByDepartureTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDepartureTime, opts...).ToFunc()
}

// ByArrivalTime orders the results by the arrival_time field.
func ByArrivalTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArrivalTime, opts...).ToFunc()
}

// ByBasePrice orders the results by the base_price field.
func ByBasePrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBasePrice, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByAircraftField orders the results by aircraft field.
func ByAircraftField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAircraftStep(), sql.OrderByField(field, opts...))
	}
}

// ByDepartureAirportField orders the results by departure_airport field.
func ByDepartureAirportField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDepartureAirportStep(), sql.OrderByField(field, opts...))
	}
}

// ByArrivalAirportField orders the results by arrival_airport field.
func ByArrivalAirportField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newArrivalAirportStep(), sql.OrderByField(field, opts...))
	}
}

// ByFlightSeatsCount orders the results by flight_seats count.
func ByFlightSeatsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFlightSeatsStep(), opts...)
	}
}

// ByFlightSeats orders the results by flight_seats terms.
func ByFlightSeats(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFlightSeatsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByBookingsCount orders the results by bookings count.
func ByBookingsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBookingsStep(), opts...)
	}
}

// ByBookings orders the results by bookings terms.
func ByBookings(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBookingsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newAircraftStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AircraftInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AircraftTable, AircraftColumn),
	)
}
func newDepartureAirportStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DepartureAirportInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DepartureAirportTable, DepartureAirportColumn),
	)
}
func newArrivalAirportStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ArrivalAirportInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ArrivalAirportTable, ArrivalAirportColumn),
	)
}
func newFlightSeatsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FlightSeatsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, FlightSeatsTable, FlightSeatsColumn),
	)
}
func newBookingsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BookingsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BookingsTable, BookingsColumn),
	)
}
