// Code generated by ent, DO NOT EDIT.

package aircraft

import (
	"pasengger_service/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldLTE(FieldID, id))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldEQ(FieldModel, v))
}

// RegistrationNo applies equality check predicate on the "registration_no" field. It's identical to RegistrationNoEQ.
func RegistrationNo(v string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldEQ(FieldRegistrationNo, v))
}

// TotalSeats applies equality check predicate on the "total_seats" field. It's identical to TotalSeatsEQ.
func TotalSeats(v int) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldEQ(FieldTotalSeats, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldEQ(FieldCreatedAt, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldContainsFold(FieldModel, v))
}

// RegistrationNoEQ applies the EQ predicate on the "registration_no" field.
func RegistrationNoEQ(v string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldEQ(FieldRegistrationNo, v))
}

// RegistrationNoNEQ applies the NEQ predicate on the "registration_no" field.
func RegistrationNoNEQ(v string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldNEQ(FieldRegistrationNo, v))
}

// RegistrationNoIn applies the In predicate on the "registration_no" field.
func RegistrationNoIn(vs ...string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldIn(FieldRegistrationNo, vs...))
}

// RegistrationNoNotIn applies the NotIn predicate on the "registration_no" field.
func RegistrationNoNotIn(vs ...string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldNotIn(FieldRegistrationNo, vs...))
}

// RegistrationNoGT applies the GT predicate on the "registration_no" field.
func RegistrationNoGT(v string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldGT(FieldRegistrationNo, v))
}

// RegistrationNoGTE applies the GTE predicate on the "registration_no" field.
func RegistrationNoGTE(v string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldGTE(FieldRegistrationNo, v))
}

// RegistrationNoLT applies the LT predicate on the "registration_no" field.
func RegistrationNoLT(v string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldLT(FieldRegistrationNo, v))
}

// RegistrationNoLTE applies the LTE predicate on the "registration_no" field.
func RegistrationNoLTE(v string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldLTE(FieldRegistrationNo, v))
}

// RegistrationNoContains applies the Contains predicate on the "registration_no" field.
func RegistrationNoContains(v string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldContains(FieldRegistrationNo, v))
}

// RegistrationNoHasPrefix applies the HasPrefix predicate on the "registration_no" field.
func RegistrationNoHasPrefix(v string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldHasPrefix(FieldRegistrationNo, v))
}

// RegistrationNoHasSuffix applies the HasSuffix predicate on the "registration_no" field.
func RegistrationNoHasSuffix(v string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldHasSuffix(FieldRegistrationNo, v))
}

// RegistrationNoEqualFold applies the EqualFold predicate on the "registration_no" field.
func RegistrationNoEqualFold(v string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldEqualFold(FieldRegistrationNo, v))
}

// RegistrationNoContainsFold applies the ContainsFold predicate on the "registration_no" field.
func RegistrationNoContainsFold(v string) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldContainsFold(FieldRegistrationNo, v))
}

// TotalSeatsEQ applies the EQ predicate on the "total_seats" field.
func TotalSeatsEQ(v int) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldEQ(FieldTotalSeats, v))
}

// TotalSeatsNEQ applies the NEQ predicate on the "total_seats" field.
func TotalSeatsNEQ(v int) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldNEQ(FieldTotalSeats, v))
}

// TotalSeatsIn applies the In predicate on the "total_seats" field.
func TotalSeatsIn(vs ...int) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldIn(FieldTotalSeats, vs...))
}

// TotalSeatsNotIn applies the NotIn predicate on the "total_seats" field.
func TotalSeatsNotIn(vs ...int) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldNotIn(FieldTotalSeats, vs...))
}

// TotalSeatsGT applies the GT predicate on the "total_seats" field.
func TotalSeatsGT(v int) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldGT(FieldTotalSeats, v))
}

// TotalSeatsGTE applies the GTE predicate on the "total_seats" field.
func TotalSeatsGTE(v int) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldGTE(FieldTotalSeats, v))
}

// TotalSeatsLT applies the LT predicate on the "total_seats" field.
func TotalSeatsLT(v int) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldLT(FieldTotalSeats, v))
}

// TotalSeatsLTE applies the LTE predicate on the "total_seats" field.
func TotalSeatsLTE(v int) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldLTE(FieldTotalSeats, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Aircraft {
	return predicate.Aircraft(sql.FieldLTE(FieldCreatedAt, v))
}

// HasFlights applies the HasEdge predicate on the "flights" edge.
func HasFlights() predicate.Aircraft {
	return predicate.Aircraft(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, FlightsTable, FlightsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFlightsWith applies the HasEdge predicate on the "flights" edge with a given conditions (other predicates).
func HasFlightsWith(preds ...predicate.Flight) predicate.Aircraft {
	return predicate.Aircraft(func(s *sql.Selector) {
		step := newFlightsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSeats applies the HasEdge predicate on the "seats" edge.
func HasSeats() predicate.Aircraft {
	return predicate.Aircraft(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SeatsTable, SeatsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSeatsWith applies the HasEdge predicate on the "seats" edge with a given conditions (other predicates).
func HasSeatsWith(preds ...predicate.Seats) predicate.Aircraft {
	return predicate.Aircraft(func(s *sql.Selector) {
		step := newSeatsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Aircraft) predicate.Aircraft {
	return predicate.Aircraft(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Aircraft) predicate.Aircraft {
	return predicate.Aircraft(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Aircraft) predicate.Aircraft {
	return predicate.Aircraft(sql.NotPredicates(p))
}
