// Code generated by ent, DO NOT EDIT.

package airport

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the airport type in the database.
	Label = "airport"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCity holds the string denoting the city field in the database.
	FieldCity = "city"
	// FieldCountry holds the string denoting the country field in the database.
	FieldCountry = "country"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeDepartures holds the string denoting the departures edge name in mutations.
	EdgeDepartures = "departures"
	// EdgeArrivals holds the string denoting the arrivals edge name in mutations.
	EdgeArrivals = "arrivals"
	// Table holds the table name of the airport in the database.
	Table = "airports"
	// DeparturesTable is the table that holds the departures relation/edge.
	DeparturesTable = "flights"
	// DeparturesInverseTable is the table name for the Flight entity.
	// It exists in this package in order to avoid circular dependency with the "flight" package.
	DeparturesInverseTable = "flights"
	// DeparturesColumn is the table column denoting the departures relation/edge.
	DeparturesColumn = "airport_departures"
	// ArrivalsTable is the table that holds the arrivals relation/edge.
	ArrivalsTable = "flights"
	// ArrivalsInverseTable is the table name for the Flight entity.
	// It exists in this package in order to avoid circular dependency with the "flight" package.
	ArrivalsInverseTable = "flights"
	// ArrivalsColumn is the table column denoting the arrivals relation/edge.
	ArrivalsColumn = "airport_arrivals"
)

// Columns holds all SQL columns for airport fields.
var Columns = []string{
	FieldID,
	FieldCode,
	FieldName,
	FieldCity,
	FieldCountry,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Airport queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCity orders the results by the city field.
func ByCity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCity, opts...).ToFunc()
}

// ByCountry orders the results by the country field.
func ByCountry(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCountry, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByDeparturesCount orders the results by departures count.
func ByDeparturesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDeparturesStep(), opts...)
	}
}

// ByDepartures orders the results by departures terms.
func ByDepartures(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDeparturesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByArrivalsCount orders the results by arrivals count.
func ByArrivalsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newArrivalsStep(), opts...)
	}
}

// ByArrivals orders the results by arrivals terms.
func ByArrivals(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newArrivalsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newDeparturesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DeparturesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DeparturesTable, DeparturesColumn),
	)
}
func newArrivalsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ArrivalsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ArrivalsTable, ArrivalsColumn),
	)
}
