// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"pasengger_service/ent/aircraft"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Aircraft is the model entity for the Aircraft schema.
type Aircraft struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// RegistrationNo holds the value of the "registration_no" field.
	RegistrationNo string `json:"registration_no,omitempty"`
	// TotalSeats holds the value of the "total_seats" field.
	TotalSeats int `json:"total_seats,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AircraftQuery when eager-loading is set.
	Edges        AircraftEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AircraftEdges holds the relations/edges for other nodes in the graph.
type AircraftEdges struct {
	// Flights holds the value of the flights edge.
	Flights []*Flight `json:"flights,omitempty"`
	// Seats holds the value of the seats edge.
	Seats []*Seats `json:"seats,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// FlightsOrErr returns the Flights value or an error if the edge
// was not loaded in eager-loading.
func (e AircraftEdges) FlightsOrErr() ([]*Flight, error) {
	if e.loadedTypes[0] {
		return e.Flights, nil
	}
	return nil, &NotLoadedError{edge: "flights"}
}

// SeatsOrErr returns the Seats value or an error if the edge
// was not loaded in eager-loading.
func (e AircraftEdges) SeatsOrErr() ([]*Seats, error) {
	if e.loadedTypes[1] {
		return e.Seats, nil
	}
	return nil, &NotLoadedError{edge: "seats"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Aircraft) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case aircraft.FieldTotalSeats:
			values[i] = new(sql.NullInt64)
		case aircraft.FieldModel, aircraft.FieldRegistrationNo:
			values[i] = new(sql.NullString)
		case aircraft.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case aircraft.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Aircraft fields.
func (_m *Aircraft) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case aircraft.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case aircraft.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case aircraft.FieldRegistrationNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field registration_no", values[i])
			} else if value.Valid {
				_m.RegistrationNo = value.String
			}
		case aircraft.FieldTotalSeats:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_seats", values[i])
			} else if value.Valid {
				_m.TotalSeats = int(value.Int64)
			}
		case aircraft.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Aircraft.
// This includes values selected through modifiers, order, etc.
func (_m *Aircraft) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryFlights queries the "flights" edge of the Aircraft entity.
func (_m *Aircraft) QueryFlights() *FlightQuery {
	return NewAircraftClient(_m.config).QueryFlights(_m)
}

// QuerySeats queries the "seats" edge of the Aircraft entity.
func (_m *Aircraft) QuerySeats() *SeatsQuery {
	return NewAircraftClient(_m.config).QuerySeats(_m)
}

// Update returns a builder for updating this Aircraft.
// Note that you need to call Aircraft.Unwrap() before calling this method if this Aircraft
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Aircraft) Update() *AircraftUpdateOne {
	return NewAircraftClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Aircraft entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Aircraft) Unwrap() *Aircraft {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Aircraft is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Aircraft) String() string {
	var builder strings.Builder
	builder.WriteString("Aircraft(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("registration_no=")
	builder.WriteString(_m.RegistrationNo)
	builder.WriteString(", ")
	builder.WriteString("total_seats=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalSeats))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Aircrafts is a parsable slice of Aircraft.
type Aircrafts []*Aircraft
