// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"pasengger_service/ent/aircraft"
	"pasengger_service/ent/flight"
	"pasengger_service/ent/seats"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AircraftCreate is the builder for creating a Aircraft entity.
type AircraftCreate struct {
	config
	mutation *AircraftMutation
	hooks    []Hook
}

// SetModel sets the "model" field.
func (_c *AircraftCreate) SetModel(v string) *AircraftCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetRegistrationNo sets the "registration_no" field.
func (_c *AircraftCreate) SetRegistrationNo(v string) *AircraftCreate {
	_c.mutation.SetRegistrationNo(v)
	return _c
}

// SetTotalSeats sets the "total_seats" field.
func (_c *AircraftCreate) SetTotalSeats(v int) *AircraftCreate {
	_c.mutation.SetTotalSeats(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AircraftCreate) SetCreatedAt(v time.Time) *AircraftCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AircraftCreate) SetNillableCreatedAt(v *time.Time) *AircraftCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AircraftCreate) SetID(v uuid.UUID) *AircraftCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AircraftCreate) SetNillableID(v *uuid.UUID) *AircraftCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddFlightIDs adds the "flights" edge to the Flight entity by IDs.
func (_c *AircraftCreate) AddFlightIDs(ids ...uuid.UUID) *AircraftCreate {
	_c.mutation.AddFlightIDs(ids...)
	return _c
}

// AddFlights adds the "flights" edges to the Flight entity.
func (_c *AircraftCreate) AddFlights(v ...*Flight) *AircraftCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddFlightIDs(ids...)
}

// AddSeatIDs adds the "seats" edge to the Seats entity by IDs.
func (_c *AircraftCreate) AddSeatIDs(ids ...uuid.UUID) *AircraftCreate {
	_c.mutation.AddSeatIDs(ids...)
	return _c
}

// AddSeats adds the "seats" edges to the Seats entity.
func (_c *AircraftCreate) AddSeats(v ...*Seats) *AircraftCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSeatIDs(ids...)
}

// Mutation returns the AircraftMutation object of the builder.
func (_c *AircraftCreate) Mutation() *AircraftMutation {
	return _c.mutation
}

// Save creates the Aircraft in the database.
func (_c *AircraftCreate) Save(ctx context.Context) (*Aircraft, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AircraftCreate) SaveX(ctx context.Context) *Aircraft {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AircraftCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AircraftCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AircraftCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := aircraft.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := aircraft.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AircraftCreate) check() error {
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "Aircraft.model"`)}
	}
	if _, ok := _c.mutation.RegistrationNo(); !ok {
		return &ValidationError{Name: "registration_no", err: errors.New(`ent: missing required field "Aircraft.registration_no"`)}
	}
	if _, ok := _c.mutation.TotalSeats(); !ok {
		return &ValidationError{Name: "total_seats", err: errors.New(`ent: missing required field "Aircraft.total_seats"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Aircraft.created_at"`)}
	}
	return nil
}

func (_c *AircraftCreate) sqlSave(ctx context.Context) (*Aircraft, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AircraftCreate) createSpec() (*Aircraft, *sqlgraph.CreateSpec) {
	var (
		_node = &Aircraft{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(aircraft.Table, sqlgraph.NewFieldSpec(aircraft.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(aircraft.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.RegistrationNo(); ok {
		_spec.SetField(aircraft.FieldRegistrationNo, field.TypeString, value)
		_node.RegistrationNo = value
	}
	if value, ok := _c.mutation.TotalSeats(); ok {
		_spec.SetField(aircraft.FieldTotalSeats, field.TypeInt, value)
		_node.TotalSeats = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(aircraft.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.FlightsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aircraft.FlightsTable,
			Columns: []string{aircraft.FlightsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flight.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SeatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aircraft.SeatsTable,
			Columns: []string{aircraft.SeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seats.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AircraftCreateBulk is the builder for creating many Aircraft entities in bulk.
type AircraftCreateBulk struct {
	config
	err      error
	builders []*AircraftCreate
}

// Save creates the Aircraft entities in the database.
func (_c *AircraftCreateBulk) Save(ctx context.Context) ([]*Aircraft, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Aircraft, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AircraftMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AircraftCreateBulk) SaveX(ctx context.Context) []*Aircraft {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AircraftCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AircraftCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
