// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"pasengger_service/ent/aircraft"
	"pasengger_service/ent/flight"
	"pasengger_service/ent/predicate"
	"pasengger_service/ent/seats"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AircraftUpdate is the builder for updating Aircraft entities.
type AircraftUpdate struct {
	config
	hooks    []Hook
	mutation *AircraftMutation
}

// Where appends a list predicates to the AircraftUpdate builder.
func (_u *AircraftUpdate) Where(ps ...predicate.Aircraft) *AircraftUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetModel sets the "model" field.
func (_u *AircraftUpdate) SetModel(v string) *AircraftUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *AircraftUpdate) SetNillableModel(v *string) *AircraftUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetRegistrationNo sets the "registration_no" field.
func (_u *AircraftUpdate) SetRegistrationNo(v string) *AircraftUpdate {
	_u.mutation.SetRegistrationNo(v)
	return _u
}

// SetNillableRegistrationNo sets the "registration_no" field if the given value is not nil.
func (_u *AircraftUpdate) SetNillableRegistrationNo(v *string) *AircraftUpdate {
	if v != nil {
		_u.SetRegistrationNo(*v)
	}
	return _u
}

// SetTotalSeats sets the "total_seats" field.
func (_u *AircraftUpdate) SetTotalSeats(v int) *AircraftUpdate {
	_u.mutation.ResetTotalSeats()
	_u.mutation.SetTotalSeats(v)
	return _u
}

// SetNillableTotalSeats sets the "total_seats" field if the given value is not nil.
func (_u *AircraftUpdate) SetNillableTotalSeats(v *int) *AircraftUpdate {
	if v != nil {
		_u.SetTotalSeats(*v)
	}
	return _u
}

// AddTotalSeats adds value to the "total_seats" field.
func (_u *AircraftUpdate) AddTotalSeats(v int) *AircraftUpdate {
	_u.mutation.AddTotalSeats(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AircraftUpdate) SetCreatedAt(v time.Time) *AircraftUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AircraftUpdate) SetNillableCreatedAt(v *time.Time) *AircraftUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddFlightIDs adds the "flights" edge to the Flight entity by IDs.
func (_u *AircraftUpdate) AddFlightIDs(ids ...uuid.UUID) *AircraftUpdate {
	_u.mutation.AddFlightIDs(ids...)
	return _u
}

// AddFlights adds the "flights" edges to the Flight entity.
func (_u *AircraftUpdate) AddFlights(v ...*Flight) *AircraftUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFlightIDs(ids...)
}

// AddSeatIDs adds the "seats" edge to the Seats entity by IDs.
func (_u *AircraftUpdate) AddSeatIDs(ids ...uuid.UUID) *AircraftUpdate {
	_u.mutation.AddSeatIDs(ids...)
	return _u
}

// AddSeats adds the "seats" edges to the Seats entity.
func (_u *AircraftUpdate) AddSeats(v ...*Seats) *AircraftUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSeatIDs(ids...)
}

// Mutation returns the AircraftMutation object of the builder.
func (_u *AircraftUpdate) Mutation() *AircraftMutation {
	return _u.mutation
}

// ClearFlights clears all "flights" edges to the Flight entity.
func (_u *AircraftUpdate) ClearFlights() *AircraftUpdate {
	_u.mutation.ClearFlights()
	return _u
}

// RemoveFlightIDs removes the "flights" edge to Flight entities by IDs.
func (_u *AircraftUpdate) RemoveFlightIDs(ids ...uuid.UUID) *AircraftUpdate {
	_u.mutation.RemoveFlightIDs(ids...)
	return _u
}

// RemoveFlights removes "flights" edges to Flight entities.
func (_u *AircraftUpdate) RemoveFlights(v ...*Flight) *AircraftUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFlightIDs(ids...)
}

// ClearSeats clears all "seats" edges to the Seats entity.
func (_u *AircraftUpdate) ClearSeats() *AircraftUpdate {
	_u.mutation.ClearSeats()
	return _u
}

// RemoveSeatIDs removes the "seats" edge to Seats entities by IDs.
func (_u *AircraftUpdate) RemoveSeatIDs(ids ...uuid.UUID) *AircraftUpdate {
	_u.mutation.RemoveSeatIDs(ids...)
	return _u
}

// RemoveSeats removes "seats" edges to Seats entities.
func (_u *AircraftUpdate) RemoveSeats(v ...*Seats) *AircraftUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSeatIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AircraftUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AircraftUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AircraftUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AircraftUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AircraftUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(aircraft.Table, aircraft.Columns, sqlgraph.NewFieldSpec(aircraft.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(aircraft.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.RegistrationNo(); ok {
		_spec.SetField(aircraft.FieldRegistrationNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalSeats(); ok {
		_spec.SetField(aircraft.FieldTotalSeats, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalSeats(); ok {
		_spec.AddField(aircraft.FieldTotalSeats, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(aircraft.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.FlightsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aircraft.FlightsTable,
			Columns: []string{aircraft.FlightsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flight.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFlightsIDs(); len(nodes) > 0 && !_u.mutation.FlightsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aircraft.FlightsTable,
			Columns: []string{aircraft.FlightsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flight.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FlightsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aircraft.FlightsTable,
			Columns: []string{aircraft.FlightsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flight.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SeatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aircraft.SeatsTable,
			Columns: []string{aircraft.SeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seats.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSeatsIDs(); len(nodes) > 0 && !_u.mutation.SeatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aircraft.SeatsTable,
			Columns: []string{aircraft.SeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seats.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SeatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aircraft.SeatsTable,
			Columns: []string{aircraft.SeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seats.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aircraft.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AircraftUpdateOne is the builder for updating a single Aircraft entity.
type AircraftUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AircraftMutation
}

// SetModel sets the "model" field.
func (_u *AircraftUpdateOne) SetModel(v string) *AircraftUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *AircraftUpdateOne) SetNillableModel(v *string) *AircraftUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetRegistrationNo sets the "registration_no" field.
func (_u *AircraftUpdateOne) SetRegistrationNo(v string) *AircraftUpdateOne {
	_u.mutation.SetRegistrationNo(v)
	return _u
}

// SetNillableRegistrationNo sets the "registration_no" field if the given value is not nil.
func (_u *AircraftUpdateOne) SetNillableRegistrationNo(v *string) *AircraftUpdateOne {
	if v != nil {
		_u.SetRegistrationNo(*v)
	}
	return _u
}

// SetTotalSeats sets the "total_seats" field.
func (_u *AircraftUpdateOne) SetTotalSeats(v int) *AircraftUpdateOne {
	_u.mutation.ResetTotalSeats()
	_u.mutation.SetTotalSeats(v)
	return _u
}

// SetNillableTotalSeats sets the "total_seats" field if the given value is not nil.
func (_u *AircraftUpdateOne) SetNillableTotalSeats(v *int) *AircraftUpdateOne {
	if v != nil {
		_u.SetTotalSeats(*v)
	}
	return _u
}

// AddTotalSeats adds value to the "total_seats" field.
func (_u *AircraftUpdateOne) AddTotalSeats(v int) *AircraftUpdateOne {
	_u.mutation.AddTotalSeats(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AircraftUpdateOne) SetCreatedAt(v time.Time) *AircraftUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AircraftUpdateOne) SetNillableCreatedAt(v *time.Time) *AircraftUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddFlightIDs adds the "flights" edge to the Flight entity by IDs.
func (_u *AircraftUpdateOne) AddFlightIDs(ids ...uuid.UUID) *AircraftUpdateOne {
	_u.mutation.AddFlightIDs(ids...)
	return _u
}

// AddFlights adds the "flights" edges to the Flight entity.
func (_u *AircraftUpdateOne) AddFlights(v ...*Flight) *AircraftUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFlightIDs(ids...)
}

// AddSeatIDs adds the "seats" edge to the Seats entity by IDs.
func (_u *AircraftUpdateOne) AddSeatIDs(ids ...uuid.UUID) *AircraftUpdateOne {
	_u.mutation.AddSeatIDs(ids...)
	return _u
}

// AddSeats adds the "seats" edges to the Seats entity.
func (_u *AircraftUpdateOne) AddSeats(v ...*Seats) *AircraftUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSeatIDs(ids...)
}

// Mutation returns the AircraftMutation object of the builder.
func (_u *AircraftUpdateOne) Mutation() *AircraftMutation {
	return _u.mutation
}

// ClearFlights clears all "flights" edges to the Flight entity.
func (_u *AircraftUpdateOne) ClearFlights() *AircraftUpdateOne {
	_u.mutation.ClearFlights()
	return _u
}

// RemoveFlightIDs removes the "flights" edge to Flight entities by IDs.
func (_u *AircraftUpdateOne) RemoveFlightIDs(ids ...uuid.UUID) *AircraftUpdateOne {
	_u.mutation.RemoveFlightIDs(ids...)
	return _u
}

// RemoveFlights removes "flights" edges to Flight entities.
func (_u *AircraftUpdateOne) RemoveFlights(v ...*Flight) *AircraftUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFlightIDs(ids...)
}

// ClearSeats clears all "seats" edges to the Seats entity.
func (_u *AircraftUpdateOne) ClearSeats() *AircraftUpdateOne {
	_u.mutation.ClearSeats()
	return _u
}

// RemoveSeatIDs removes the "seats" edge to Seats entities by IDs.
func (_u *AircraftUpdateOne) RemoveSeatIDs(ids ...uuid.UUID) *AircraftUpdateOne {
	_u.mutation.RemoveSeatIDs(ids...)
	return _u
}

// RemoveSeats removes "seats" edges to Seats entities.
func (_u *AircraftUpdateOne) RemoveSeats(v ...*Seats) *AircraftUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSeatIDs(ids...)
}

// Where appends a list predicates to the AircraftUpdate builder.
func (_u *AircraftUpdateOne) Where(ps ...predicate.Aircraft) *AircraftUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AircraftUpdateOne) Select(field string, fields ...string) *AircraftUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Aircraft entity.
func (_u *AircraftUpdateOne) Save(ctx context.Context) (*Aircraft, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AircraftUpdateOne) SaveX(ctx context.Context) *Aircraft {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AircraftUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AircraftUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AircraftUpdateOne) sqlSave(ctx context.Context) (_node *Aircraft, err error) {
	_spec := sqlgraph.NewUpdateSpec(aircraft.Table, aircraft.Columns, sqlgraph.NewFieldSpec(aircraft.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Aircraft.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, aircraft.FieldID)
		for _, f := range fields {
			if !aircraft.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != aircraft.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(aircraft.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.RegistrationNo(); ok {
		_spec.SetField(aircraft.FieldRegistrationNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalSeats(); ok {
		_spec.SetField(aircraft.FieldTotalSeats, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalSeats(); ok {
		_spec.AddField(aircraft.FieldTotalSeats, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(aircraft.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.FlightsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aircraft.FlightsTable,
			Columns: []string{aircraft.FlightsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flight.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFlightsIDs(); len(nodes) > 0 && !_u.mutation.FlightsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aircraft.FlightsTable,
			Columns: []string{aircraft.FlightsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flight.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FlightsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aircraft.FlightsTable,
			Columns: []string{aircraft.FlightsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flight.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SeatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aircraft.SeatsTable,
			Columns: []string{aircraft.SeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seats.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSeatsIDs(); len(nodes) > 0 && !_u.mutation.SeatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aircraft.SeatsTable,
			Columns: []string{aircraft.SeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seats.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SeatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   aircraft.SeatsTable,
			Columns: []string{aircraft.SeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seats.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Aircraft{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aircraft.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
