// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"pasengger_service/ent/bookingpassenger"
	"pasengger_service/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BookingPassengerDelete is the builder for deleting a BookingPassenger entity.
type BookingPassengerDelete struct {
	config
	hooks    []Hook
	mutation *BookingPassengerMutation
}

// Where appends a list predicates to the BookingPassengerDelete builder.
func (_d *BookingPassengerDelete) Where(ps ...predicate.BookingPassenger) *BookingPassengerDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BookingPassengerDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BookingPassengerDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BookingPassengerDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(bookingpassenger.Table, sqlgraph.NewFieldSpec(bookingpassenger.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BookingPassengerDeleteOne is the builder for deleting a single BookingPassenger entity.
type BookingPassengerDeleteOne struct {
	_d *BookingPassengerDelete
}

// Where appends a list predicates to the BookingPassengerDelete builder.
func (_d *BookingPassengerDeleteOne) Where(ps ...predicate.BookingPassenger) *BookingPassengerDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BookingPassengerDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{bookingpassenger.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BookingPassengerDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
