// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"pasengger_service/ent/booking"
	"pasengger_service/ent/flight"
	"pasengger_service/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Booking is the model entity for the Booking schema.
type Booking struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// BookingCode holds the value of the "booking_code" field.
	BookingCode string `json:"booking_code,omitempty"`
	// TotalAmount holds the value of the "total_amount" field.
	TotalAmount float64 `json:"total_amount,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BookingQuery when eager-loading is set.
	Edges           BookingEdges `json:"edges"`
	flight_bookings *uuid.UUID
	user_bookings   *uuid.UUID
	selectValues    sql.SelectValues
}

// BookingEdges holds the relations/edges for other nodes in the graph.
type BookingEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Flight holds the value of the flight edge.
	Flight *Flight `json:"flight,omitempty"`
	// BookingPassengers holds the value of the booking_passengers edge.
	BookingPassengers []*BookingPassenger `json:"booking_passengers,omitempty"`
	// Payments holds the value of the payments edge.
	Payments []*Payment `json:"payments,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BookingEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// FlightOrErr returns the Flight value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BookingEdges) FlightOrErr() (*Flight, error) {
	if e.Flight != nil {
		return e.Flight, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: flight.Label}
	}
	return nil, &NotLoadedError{edge: "flight"}
}

// BookingPassengersOrErr returns the BookingPassengers value or an error if the edge
// was not loaded in eager-loading.
func (e BookingEdges) BookingPassengersOrErr() ([]*BookingPassenger, error) {
	if e.loadedTypes[2] {
		return e.BookingPassengers, nil
	}
	return nil, &NotLoadedError{edge: "booking_passengers"}
}

// PaymentsOrErr returns the Payments value or an error if the edge
// was not loaded in eager-loading.
func (e BookingEdges) PaymentsOrErr() ([]*Payment, error) {
	if e.loadedTypes[3] {
		return e.Payments, nil
	}
	return nil, &NotLoadedError{edge: "payments"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Booking) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case booking.FieldTotalAmount:
			values[i] = new(sql.NullFloat64)
		case booking.FieldBookingCode, booking.FieldStatus:
			values[i] = new(sql.NullString)
		case booking.FieldExpiresAt, booking.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case booking.FieldID:
			values[i] = new(uuid.UUID)
		case booking.ForeignKeys[0]: // flight_bookings
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case booking.ForeignKeys[1]: // user_bookings
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Booking fields.
func (_m *Booking) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case booking.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case booking.FieldBookingCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field booking_code", values[i])
			} else if value.Valid {
				_m.BookingCode = value.String
			}
		case booking.FieldTotalAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_amount", values[i])
			} else if value.Valid {
				_m.TotalAmount = value.Float64
			}
		case booking.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case booking.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case booking.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case booking.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field flight_bookings", values[i])
			} else if value.Valid {
				_m.flight_bookings = new(uuid.UUID)
				*_m.flight_bookings = *value.S.(*uuid.UUID)
			}
		case booking.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_bookings", values[i])
			} else if value.Valid {
				_m.user_bookings = new(uuid.UUID)
				*_m.user_bookings = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Booking.
// This includes values selected through modifiers, order, etc.
func (_m *Booking) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Booking entity.
func (_m *Booking) QueryUser() *UserQuery {
	return NewBookingClient(_m.config).QueryUser(_m)
}

// QueryFlight queries the "flight" edge of the Booking entity.
func (_m *Booking) QueryFlight() *FlightQuery {
	return NewBookingClient(_m.config).QueryFlight(_m)
}

// QueryBookingPassengers queries the "booking_passengers" edge of the Booking entity.
func (_m *Booking) QueryBookingPassengers() *BookingPassengerQuery {
	return NewBookingClient(_m.config).QueryBookingPassengers(_m)
}

// QueryPayments queries the "payments" edge of the Booking entity.
func (_m *Booking) QueryPayments() *PaymentQuery {
	return NewBookingClient(_m.config).QueryPayments(_m)
}

// Update returns a builder for updating this Booking.
// Note that you need to call Booking.Unwrap() before calling this method if this Booking
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Booking) Update() *BookingUpdateOne {
	return NewBookingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Booking entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Booking) Unwrap() *Booking {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Booking is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Booking) String() string {
	var builder strings.Builder
	builder.WriteString("Booking(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("booking_code=")
	builder.WriteString(_m.BookingCode)
	builder.WriteString(", ")
	builder.WriteString("total_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalAmount))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Bookings is a parsable slice of Booking.
type Bookings []*Booking
