// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"pasengger_service/ent/booking"
	"pasengger_service/ent/bookingpassenger"
	"pasengger_service/ent/flightseat"
	"pasengger_service/ent/passenger"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// BookingPassenger is the model entity for the BookingPassenger schema.
type BookingPassenger struct {
	config
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BookingPassengerQuery when eager-loading is set.
	Edges                      BookingPassengerEdges `json:"edges"`
	booking_booking_passengers *uuid.UUID
	flight_seat_assigned       *uuid.UUID
	passenger_booking_entries  *uuid.UUID
	selectValues               sql.SelectValues
}

// BookingPassengerEdges holds the relations/edges for other nodes in the graph.
type BookingPassengerEdges struct {
	// Booking holds the value of the booking edge.
	Booking *Booking `json:"booking,omitempty"`
	// Passenger holds the value of the passenger edge.
	Passenger *Passenger `json:"passenger,omitempty"`
	// FlightSeat holds the value of the flight_seat edge.
	FlightSeat *FlightSeat `json:"flight_seat,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// BookingOrErr returns the Booking value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BookingPassengerEdges) BookingOrErr() (*Booking, error) {
	if e.Booking != nil {
		return e.Booking, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: booking.Label}
	}
	return nil, &NotLoadedError{edge: "booking"}
}

// PassengerOrErr returns the Passenger value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BookingPassengerEdges) PassengerOrErr() (*Passenger, error) {
	if e.Passenger != nil {
		return e.Passenger, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: passenger.Label}
	}
	return nil, &NotLoadedError{edge: "passenger"}
}

// FlightSeatOrErr returns the FlightSeat value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BookingPassengerEdges) FlightSeatOrErr() (*FlightSeat, error) {
	if e.FlightSeat != nil {
		return e.FlightSeat, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: flightseat.Label}
	}
	return nil, &NotLoadedError{edge: "flight_seat"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BookingPassenger) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case bookingpassenger.FieldID:
			values[i] = new(uuid.UUID)
		case bookingpassenger.ForeignKeys[0]: // booking_booking_passengers
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case bookingpassenger.ForeignKeys[1]: // flight_seat_assigned
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case bookingpassenger.ForeignKeys[2]: // passenger_booking_entries
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BookingPassenger fields.
func (_m *BookingPassenger) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case bookingpassenger.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case bookingpassenger.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field booking_booking_passengers", values[i])
			} else if value.Valid {
				_m.booking_booking_passengers = new(uuid.UUID)
				*_m.booking_booking_passengers = *value.S.(*uuid.UUID)
			}
		case bookingpassenger.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field flight_seat_assigned", values[i])
			} else if value.Valid {
				_m.flight_seat_assigned = new(uuid.UUID)
				*_m.flight_seat_assigned = *value.S.(*uuid.UUID)
			}
		case bookingpassenger.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field passenger_booking_entries", values[i])
			} else if value.Valid {
				_m.passenger_booking_entries = new(uuid.UUID)
				*_m.passenger_booking_entries = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BookingPassenger.
// This includes values selected through modifiers, order, etc.
func (_m *BookingPassenger) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryBooking queries the "booking" edge of the BookingPassenger entity.
func (_m *BookingPassenger) QueryBooking() *BookingQuery {
	return NewBookingPassengerClient(_m.config).QueryBooking(_m)
}

// QueryPassenger queries the "passenger" edge of the BookingPassenger entity.
func (_m *BookingPassenger) QueryPassenger() *PassengerQuery {
	return NewBookingPassengerClient(_m.config).QueryPassenger(_m)
}

// QueryFlightSeat queries the "flight_seat" edge of the BookingPassenger entity.
func (_m *BookingPassenger) QueryFlightSeat() *FlightSeatQuery {
	return NewBookingPassengerClient(_m.config).QueryFlightSeat(_m)
}

// Update returns a builder for updating this BookingPassenger.
// Note that you need to call BookingPassenger.Unwrap() before calling this method if this BookingPassenger
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BookingPassenger) Update() *BookingPassengerUpdateOne {
	return NewBookingPassengerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BookingPassenger entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BookingPassenger) Unwrap() *BookingPassenger {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BookingPassenger is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BookingPassenger) String() string {
	var builder strings.Builder
	builder.WriteString("BookingPassenger(")
	builder.WriteString(fmt.Sprintf("id=%v", _m.ID))
	builder.WriteByte(')')
	return builder.String()
}

// BookingPassengers is a parsable slice of BookingPassenger.
type BookingPassengers []*BookingPassenger
