// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"pasengger_service/ent/aircraft"
	"pasengger_service/ent/airport"
	"pasengger_service/ent/booking"
	"pasengger_service/ent/flight"
	"pasengger_service/ent/flightseat"
	"pasengger_service/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// FlightUpdate is the builder for updating Flight entities.
type FlightUpdate struct {
	config
	hooks    []Hook
	mutation *FlightMutation
}

// Where appends a list predicates to the FlightUpdate builder.
func (_u *FlightUpdate) Where(ps ...predicate.Flight) *FlightUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetFlightNumber sets the "flight_number" field.
func (_u *FlightUpdate) SetFlightNumber(v string) *FlightUpdate {
	_u.mutation.SetFlightNumber(v)
	return _u
}

// SetNillableFlightNumber sets the "flight_number" field if the given value is not nil.
func (_u *FlightUpdate) SetNillableFlightNumber(v *string) *FlightUpdate {
	if v != nil {
		_u.SetFlightNumber(*v)
	}
	return _u
}

// SetDepartureTime sets the "departure_time" field.
func (_u *FlightUpdate) SetDepartureTime(v time.Time) *FlightUpdate {
	_u.mutation.SetDepartureTime(v)
	return _u
}

// SetNillableDepartureTime sets the "departure_time" field if the given value is not nil.
func (_u *FlightUpdate) SetNillableDepartureTime(v *time.Time) *FlightUpdate {
	if v != nil {
		_u.SetDepartureTime(*v)
	}
	return _u
}

// SetArrivalTime sets the "arrival_time" field.
func (_u *FlightUpdate) SetArrivalTime(v time.Time) *FlightUpdate {
	_u.mutation.SetArrivalTime(v)
	return _u
}

// SetNillableArrivalTime sets the "arrival_time" field if the given value is not nil.
func (_u *FlightUpdate) SetNillableArrivalTime(v *time.Time) *FlightUpdate {
	if v != nil {
		_u.SetArrivalTime(*v)
	}
	return _u
}

// SetBasePrice sets the "base_price" field.
func (_u *FlightUpdate) SetBasePrice(v float64) *FlightUpdate {
	_u.mutation.ResetBasePrice()
	_u.mutation.SetBasePrice(v)
	return _u
}

// SetNillableBasePrice sets the "base_price" field if the given value is not nil.
func (_u *FlightUpdate) SetNillableBasePrice(v *float64) *FlightUpdate {
	if v != nil {
		_u.SetBasePrice(*v)
	}
	return _u
}

// AddBasePrice adds value to the "base_price" field.
func (_u *FlightUpdate) AddBasePrice(v float64) *FlightUpdate {
	_u.mutation.AddBasePrice(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *FlightUpdate) SetStatus(v string) *FlightUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FlightUpdate) SetNillableStatus(v *string) *FlightUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *FlightUpdate) SetCreatedAt(v time.Time) *FlightUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *FlightUpdate) SetNillableCreatedAt(v *time.Time) *FlightUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetAircraftID sets the "aircraft" edge to the Aircraft entity by ID.
func (_u *FlightUpdate) SetAircraftID(id uuid.UUID) *FlightUpdate {
	_u.mutation.SetAircraftID(id)
	return _u
}

// SetAircraft sets the "aircraft" edge to the Aircraft entity.
func (_u *FlightUpdate) SetAircraft(v *Aircraft) *FlightUpdate {
	return _u.SetAircraftID(v.ID)
}

// SetDepartureAirportID sets the "departure_airport" edge to the Airport entity by ID.
func (_u *FlightUpdate) SetDepartureAirportID(id uuid.UUID) *FlightUpdate {
	_u.mutation.SetDepartureAirportID(id)
	return _u
}

// SetDepartureAirport sets the "departure_airport" edge to the Airport entity.
func (_u *FlightUpdate) SetDepartureAirport(v *Airport) *FlightUpdate {
	return _u.SetDepartureAirportID(v.ID)
}

// SetArrivalAirportID sets the "arrival_airport" edge to the Airport entity by ID.
func (_u *FlightUpdate) SetArrivalAirportID(id uuid.UUID) *FlightUpdate {
	_u.mutation.SetArrivalAirportID(id)
	return _u
}

// SetArrivalAirport sets the "arrival_airport" edge to the Airport entity.
func (_u *FlightUpdate) SetArrivalAirport(v *Airport) *FlightUpdate {
	return _u.SetArrivalAirportID(v.ID)
}

// AddFlightSeatIDs adds the "flight_seats" edge to the FlightSeat entity by IDs.
func (_u *FlightUpdate) AddFlightSeatIDs(ids ...uuid.UUID) *FlightUpdate {
	_u.mutation.AddFlightSeatIDs(ids...)
	return _u
}

// AddFlightSeats adds the "flight_seats" edges to the FlightSeat entity.
func (_u *FlightUpdate) AddFlightSeats(v ...*FlightSeat) *FlightUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFlightSeatIDs(ids...)
}

// AddBookingIDs adds the "bookings" edge to the Booking entity by IDs.
func (_u *FlightUpdate) AddBookingIDs(ids ...uuid.UUID) *FlightUpdate {
	_u.mutation.AddBookingIDs(ids...)
	return _u
}

// AddBookings adds the "bookings" edges to the Booking entity.
func (_u *FlightUpdate) AddBookings(v ...*Booking) *FlightUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBookingIDs(ids...)
}

// Mutation returns the FlightMutation object of the builder.
func (_u *FlightUpdate) Mutation() *FlightMutation {
	return _u.mutation
}

// ClearAircraft clears the "aircraft" edge to the Aircraft entity.
func (_u *FlightUpdate) ClearAircraft() *FlightUpdate {
	_u.mutation.ClearAircraft()
	return _u
}

// ClearDepartureAirport clears the "departure_airport" edge to the Airport entity.
func (_u *FlightUpdate) ClearDepartureAirport() *FlightUpdate {
	_u.mutation.ClearDepartureAirport()
	return _u
}

// ClearArrivalAirport clears the "arrival_airport" edge to the Airport entity.
func (_u *FlightUpdate) ClearArrivalAirport() *FlightUpdate {
	_u.mutation.ClearArrivalAirport()
	return _u
}

// ClearFlightSeats clears all "flight_seats" edges to the FlightSeat entity.
func (_u *FlightUpdate) ClearFlightSeats() *FlightUpdate {
	_u.mutation.ClearFlightSeats()
	return _u
}

// RemoveFlightSeatIDs removes the "flight_seats" edge to FlightSeat entities by IDs.
func (_u *FlightUpdate) RemoveFlightSeatIDs(ids ...uuid.UUID) *FlightUpdate {
	_u.mutation.RemoveFlightSeatIDs(ids...)
	return _u
}

// RemoveFlightSeats removes "flight_seats" edges to FlightSeat entities.
func (_u *FlightUpdate) RemoveFlightSeats(v ...*FlightSeat) *FlightUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFlightSeatIDs(ids...)
}

// ClearBookings clears all "bookings" edges to the Booking entity.
func (_u *FlightUpdate) ClearBookings() *FlightUpdate {
	_u.mutation.ClearBookings()
	return _u
}

// RemoveBookingIDs removes the "bookings" edge to Booking entities by IDs.
func (_u *FlightUpdate) RemoveBookingIDs(ids ...uuid.UUID) *FlightUpdate {
	_u.mutation.RemoveBookingIDs(ids...)
	return _u
}

// RemoveBookings removes "bookings" edges to Booking entities.
func (_u *FlightUpdate) RemoveBookings(v ...*Booking) *FlightUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBookingIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FlightUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FlightUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FlightUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FlightUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FlightUpdate) check() error {
	if _u.mutation.AircraftCleared() && len(_u.mutation.AircraftIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Flight.aircraft"`)
	}
	if _u.mutation.DepartureAirportCleared() && len(_u.mutation.DepartureAirportIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Flight.departure_airport"`)
	}
	if _u.mutation.ArrivalAirportCleared() && len(_u.mutation.ArrivalAirportIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Flight.arrival_airport"`)
	}
	return nil
}

func (_u *FlightUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(flight.Table, flight.Columns, sqlgraph.NewFieldSpec(flight.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FlightNumber(); ok {
		_spec.SetField(flight.FieldFlightNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.DepartureTime(); ok {
		_spec.SetField(flight.FieldDepartureTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ArrivalTime(); ok {
		_spec.SetField(flight.FieldArrivalTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.BasePrice(); ok {
		_spec.SetField(flight.FieldBasePrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBasePrice(); ok {
		_spec.AddField(flight.FieldBasePrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(flight.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(flight.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.AircraftCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flight.AircraftTable,
			Columns: []string{flight.AircraftColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aircraft.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AircraftIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flight.AircraftTable,
			Columns: []string{flight.AircraftColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aircraft.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DepartureAirportCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flight.DepartureAirportTable,
			Columns: []string{flight.DepartureAirportColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(airport.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DepartureAirportIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flight.DepartureAirportTable,
			Columns: []string{flight.DepartureAirportColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(airport.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ArrivalAirportCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flight.ArrivalAirportTable,
			Columns: []string{flight.ArrivalAirportColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(airport.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArrivalAirportIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flight.ArrivalAirportTable,
			Columns: []string{flight.ArrivalAirportColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(airport.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FlightSeatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flight.FlightSeatsTable,
			Columns: []string{flight.FlightSeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flightseat.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFlightSeatsIDs(); len(nodes) > 0 && !_u.mutation.FlightSeatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flight.FlightSeatsTable,
			Columns: []string{flight.FlightSeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flightseat.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FlightSeatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flight.FlightSeatsTable,
			Columns: []string{flight.FlightSeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flightseat.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BookingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flight.BookingsTable,
			Columns: []string{flight.BookingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBookingsIDs(); len(nodes) > 0 && !_u.mutation.BookingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flight.BookingsTable,
			Columns: []string{flight.BookingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BookingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flight.BookingsTable,
			Columns: []string{flight.BookingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{flight.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FlightUpdateOne is the builder for updating a single Flight entity.
type FlightUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FlightMutation
}

// SetFlightNumber sets the "flight_number" field.
func (_u *FlightUpdateOne) SetFlightNumber(v string) *FlightUpdateOne {
	_u.mutation.SetFlightNumber(v)
	return _u
}

// SetNillableFlightNumber sets the "flight_number" field if the given value is not nil.
func (_u *FlightUpdateOne) SetNillableFlightNumber(v *string) *FlightUpdateOne {
	if v != nil {
		_u.SetFlightNumber(*v)
	}
	return _u
}

// SetDepartureTime sets the "departure_time" field.
func (_u *FlightUpdateOne) SetDepartureTime(v time.Time) *FlightUpdateOne {
	_u.mutation.SetDepartureTime(v)
	return _u
}

// SetNillableDepartureTime sets the "departure_time" field if the given value is not nil.
func (_u *FlightUpdateOne) SetNillableDepartureTime(v *time.Time) *FlightUpdateOne {
	if v != nil {
		_u.SetDepartureTime(*v)
	}
	return _u
}

// SetArrivalTime sets the "arrival_time" field.
func (_u *FlightUpdateOne) SetArrivalTime(v time.Time) *FlightUpdateOne {
	_u.mutation.SetArrivalTime(v)
	return _u
}

// SetNillableArrivalTime sets the "arrival_time" field if the given value is not nil.
func (_u *FlightUpdateOne) SetNillableArrivalTime(v *time.Time) *FlightUpdateOne {
	if v != nil {
		_u.SetArrivalTime(*v)
	}
	return _u
}

// SetBasePrice sets the "base_price" field.
func (_u *FlightUpdateOne) SetBasePrice(v float64) *FlightUpdateOne {
	_u.mutation.ResetBasePrice()
	_u.mutation.SetBasePrice(v)
	return _u
}

// SetNillableBasePrice sets the "base_price" field if the given value is not nil.
func (_u *FlightUpdateOne) SetNillableBasePrice(v *float64) *FlightUpdateOne {
	if v != nil {
		_u.SetBasePrice(*v)
	}
	return _u
}

// AddBasePrice adds value to the "base_price" field.
func (_u *FlightUpdateOne) AddBasePrice(v float64) *FlightUpdateOne {
	_u.mutation.AddBasePrice(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *FlightUpdateOne) SetStatus(v string) *FlightUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FlightUpdateOne) SetNillableStatus(v *string) *FlightUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *FlightUpdateOne) SetCreatedAt(v time.Time) *FlightUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *FlightUpdateOne) SetNillableCreatedAt(v *time.Time) *FlightUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetAircraftID sets the "aircraft" edge to the Aircraft entity by ID.
func (_u *FlightUpdateOne) SetAircraftID(id uuid.UUID) *FlightUpdateOne {
	_u.mutation.SetAircraftID(id)
	return _u
}

// SetAircraft sets the "aircraft" edge to the Aircraft entity.
func (_u *FlightUpdateOne) SetAircraft(v *Aircraft) *FlightUpdateOne {
	return _u.SetAircraftID(v.ID)
}

// SetDepartureAirportID sets the "departure_airport" edge to the Airport entity by ID.
func (_u *FlightUpdateOne) SetDepartureAirportID(id uuid.UUID) *FlightUpdateOne {
	_u.mutation.SetDepartureAirportID(id)
	return _u
}

// SetDepartureAirport sets the "departure_airport" edge to the Airport entity.
func (_u *FlightUpdateOne) SetDepartureAirport(v *Airport) *FlightUpdateOne {
	return _u.SetDepartureAirportID(v.ID)
}

// SetArrivalAirportID sets the "arrival_airport" edge to the Airport entity by ID.
func (_u *FlightUpdateOne) SetArrivalAirportID(id uuid.UUID) *FlightUpdateOne {
	_u.mutation.SetArrivalAirportID(id)
	return _u
}

// SetArrivalAirport sets the "arrival_airport" edge to the Airport entity.
func (_u *FlightUpdateOne) SetArrivalAirport(v *Airport) *FlightUpdateOne {
	return _u.SetArrivalAirportID(v.ID)
}

// AddFlightSeatIDs adds the "flight_seats" edge to the FlightSeat entity by IDs.
func (_u *FlightUpdateOne) AddFlightSeatIDs(ids ...uuid.UUID) *FlightUpdateOne {
	_u.mutation.AddFlightSeatIDs(ids...)
	return _u
}

// AddFlightSeats adds the "flight_seats" edges to the FlightSeat entity.
func (_u *FlightUpdateOne) AddFlightSeats(v ...*FlightSeat) *FlightUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFlightSeatIDs(ids...)
}

// AddBookingIDs adds the "bookings" edge to the Booking entity by IDs.
func (_u *FlightUpdateOne) AddBookingIDs(ids ...uuid.UUID) *FlightUpdateOne {
	_u.mutation.AddBookingIDs(ids...)
	return _u
}

// AddBookings adds the "bookings" edges to the Booking entity.
func (_u *FlightUpdateOne) AddBookings(v ...*Booking) *FlightUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBookingIDs(ids...)
}

// Mutation returns the FlightMutation object of the builder.
func (_u *FlightUpdateOne) Mutation() *FlightMutation {
	return _u.mutation
}

// ClearAircraft clears the "aircraft" edge to the Aircraft entity.
func (_u *FlightUpdateOne) ClearAircraft() *FlightUpdateOne {
	_u.mutation.ClearAircraft()
	return _u
}

// ClearDepartureAirport clears the "departure_airport" edge to the Airport entity.
func (_u *FlightUpdateOne) ClearDepartureAirport() *FlightUpdateOne {
	_u.mutation.ClearDepartureAirport()
	return _u
}

// ClearArrivalAirport clears the "arrival_airport" edge to the Airport entity.
func (_u *FlightUpdateOne) ClearArrivalAirport() *FlightUpdateOne {
	_u.mutation.ClearArrivalAirport()
	return _u
}

// ClearFlightSeats clears all "flight_seats" edges to the FlightSeat entity.
func (_u *FlightUpdateOne) ClearFlightSeats() *FlightUpdateOne {
	_u.mutation.ClearFlightSeats()
	return _u
}

// RemoveFlightSeatIDs removes the "flight_seats" edge to FlightSeat entities by IDs.
func (_u *FlightUpdateOne) RemoveFlightSeatIDs(ids ...uuid.UUID) *FlightUpdateOne {
	_u.mutation.RemoveFlightSeatIDs(ids...)
	return _u
}

// RemoveFlightSeats removes "flight_seats" edges to FlightSeat entities.
func (_u *FlightUpdateOne) RemoveFlightSeats(v ...*FlightSeat) *FlightUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFlightSeatIDs(ids...)
}

// ClearBookings clears all "bookings" edges to the Booking entity.
func (_u *FlightUpdateOne) ClearBookings() *FlightUpdateOne {
	_u.mutation.ClearBookings()
	return _u
}

// RemoveBookingIDs removes the "bookings" edge to Booking entities by IDs.
func (_u *FlightUpdateOne) RemoveBookingIDs(ids ...uuid.UUID) *FlightUpdateOne {
	_u.mutation.RemoveBookingIDs(ids...)
	return _u
}

// RemoveBookings removes "bookings" edges to Booking entities.
func (_u *FlightUpdateOne) RemoveBookings(v ...*Booking) *FlightUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBookingIDs(ids...)
}

// Where appends a list predicates to the FlightUpdate builder.
func (_u *FlightUpdateOne) Where(ps ...predicate.Flight) *FlightUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FlightUpdateOne) Select(field string, fields ...string) *FlightUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Flight entity.
func (_u *FlightUpdateOne) Save(ctx context.Context) (*Flight, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FlightUpdateOne) SaveX(ctx context.Context) *Flight {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FlightUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FlightUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FlightUpdateOne) check() error {
	if _u.mutation.AircraftCleared() && len(_u.mutation.AircraftIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Flight.aircraft"`)
	}
	if _u.mutation.DepartureAirportCleared() && len(_u.mutation.DepartureAirportIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Flight.departure_airport"`)
	}
	if _u.mutation.ArrivalAirportCleared() && len(_u.mutation.ArrivalAirportIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Flight.arrival_airport"`)
	}
	return nil
}

func (_u *FlightUpdateOne) sqlSave(ctx context.Context) (_node *Flight, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(flight.Table, flight.Columns, sqlgraph.NewFieldSpec(flight.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Flight.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, flight.FieldID)
		for _, f := range fields {
			if !flight.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != flight.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FlightNumber(); ok {
		_spec.SetField(flight.FieldFlightNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.DepartureTime(); ok {
		_spec.SetField(flight.FieldDepartureTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ArrivalTime(); ok {
		_spec.SetField(flight.FieldArrivalTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.BasePrice(); ok {
		_spec.SetField(flight.FieldBasePrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBasePrice(); ok {
		_spec.AddField(flight.FieldBasePrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(flight.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(flight.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.AircraftCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flight.AircraftTable,
			Columns: []string{flight.AircraftColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aircraft.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AircraftIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flight.AircraftTable,
			Columns: []string{flight.AircraftColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aircraft.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DepartureAirportCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flight.DepartureAirportTable,
			Columns: []string{flight.DepartureAirportColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(airport.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DepartureAirportIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flight.DepartureAirportTable,
			Columns: []string{flight.DepartureAirportColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(airport.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ArrivalAirportCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flight.ArrivalAirportTable,
			Columns: []string{flight.ArrivalAirportColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(airport.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArrivalAirportIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flight.ArrivalAirportTable,
			Columns: []string{flight.ArrivalAirportColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(airport.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FlightSeatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flight.FlightSeatsTable,
			Columns: []string{flight.FlightSeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flightseat.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFlightSeatsIDs(); len(nodes) > 0 && !_u.mutation.FlightSeatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flight.FlightSeatsTable,
			Columns: []string{flight.FlightSeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flightseat.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FlightSeatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flight.FlightSeatsTable,
			Columns: []string{flight.FlightSeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flightseat.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BookingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flight.BookingsTable,
			Columns: []string{flight.BookingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBookingsIDs(); len(nodes) > 0 && !_u.mutation.BookingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flight.BookingsTable,
			Columns: []string{flight.BookingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BookingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flight.BookingsTable,
			Columns: []string{flight.BookingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Flight{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{flight.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
