// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"pasengger_service/ent/aircraft"
	"pasengger_service/ent/airport"
	"pasengger_service/ent/flight"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Flight is the model entity for the Flight schema.
type Flight struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// FlightNumber holds the value of the "flight_number" field.
	FlightNumber string `json:"flight_number,omitempty"`
	// DepartureTime holds the value of the "departure_time" field.
	DepartureTime time.Time `json:"departure_time,omitempty"`
	// ArrivalTime holds the value of the "arrival_time" field.
	ArrivalTime time.Time `json:"arrival_time,omitempty"`
	// BasePrice holds the value of the "base_price" field.
	BasePrice float64 `json:"base_price,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FlightQuery when eager-loading is set.
	Edges              FlightEdges `json:"edges"`
	aircraft_flights   *uuid.UUID
	airport_departures *uuid.UUID
	airport_arrivals   *uuid.UUID
	selectValues       sql.SelectValues
}

// FlightEdges holds the relations/edges for other nodes in the graph.
type FlightEdges struct {
	// Aircraft holds the value of the aircraft edge.
	Aircraft *Aircraft `json:"aircraft,omitempty"`
	// DepartureAirport holds the value of the departure_airport edge.
	DepartureAirport *Airport `json:"departure_airport,omitempty"`
	// ArrivalAirport holds the value of the arrival_airport edge.
	ArrivalAirport *Airport `json:"arrival_airport,omitempty"`
	// FlightSeats holds the value of the flight_seats edge.
	FlightSeats []*FlightSeat `json:"flight_seats,omitempty"`
	// Bookings holds the value of the bookings edge.
	Bookings []*Booking `json:"bookings,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// AircraftOrErr returns the Aircraft value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FlightEdges) AircraftOrErr() (*Aircraft, error) {
	if e.Aircraft != nil {
		return e.Aircraft, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: aircraft.Label}
	}
	return nil, &NotLoadedError{edge: "aircraft"}
}

// DepartureAirportOrErr returns the DepartureAirport value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FlightEdges) DepartureAirportOrErr() (*Airport, error) {
	if e.DepartureAirport != nil {
		return e.DepartureAirport, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: airport.Label}
	}
	return nil, &NotLoadedError{edge: "departure_airport"}
}

// ArrivalAirportOrErr returns the ArrivalAirport value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FlightEdges) ArrivalAirportOrErr() (*Airport, error) {
	if e.ArrivalAirport != nil {
		return e.ArrivalAirport, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: airport.Label}
	}
	return nil, &NotLoadedError{edge: "arrival_airport"}
}

// FlightSeatsOrErr returns the FlightSeats value or an error if the edge
// was not loaded in eager-loading.
func (e FlightEdges) FlightSeatsOrErr() ([]*FlightSeat, error) {
	if e.loadedTypes[3] {
		return e.FlightSeats, nil
	}
	return nil, &NotLoadedError{edge: "flight_seats"}
}

// BookingsOrErr returns the Bookings value or an error if the edge
// was not loaded in eager-loading.
func (e FlightEdges) BookingsOrErr() ([]*Booking, error) {
	if e.loadedTypes[4] {
		return e.Bookings, nil
	}
	return nil, &NotLoadedError{edge: "bookings"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Flight) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case flight.FieldBasePrice:
			values[i] = new(sql.NullFloat64)
		case flight.FieldFlightNumber, flight.FieldStatus:
			values[i] = new(sql.NullString)
		case flight.FieldDepartureTime, flight.FieldArrivalTime, flight.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case flight.FieldID:
			values[i] = new(uuid.UUID)
		case flight.ForeignKeys[0]: // aircraft_flights
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case flight.ForeignKeys[1]: // airport_departures
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case flight.ForeignKeys[2]: // airport_arrivals
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Flight fields.
func (_m *Flight) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case flight.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case flight.FieldFlightNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field flight_number", values[i])
			} else if value.Valid {
				_m.FlightNumber = value.String
			}
		case flight.FieldDepartureTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field departure_time", values[i])
			} else if value.Valid {
				_m.DepartureTime = value.Time
			}
		case flight.FieldArrivalTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field arrival_time", values[i])
			} else if value.Valid {
				_m.ArrivalTime = value.Time
			}
		case flight.FieldBasePrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field base_price", values[i])
			} else if value.Valid {
				_m.BasePrice = value.Float64
			}
		case flight.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case flight.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case flight.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field aircraft_flights", values[i])
			} else if value.Valid {
				_m.aircraft_flights = new(uuid.UUID)
				*_m.aircraft_flights = *value.S.(*uuid.UUID)
			}
		case flight.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field airport_departures", values[i])
			} else if value.Valid {
				_m.airport_departures = new(uuid.UUID)
				*_m.airport_departures = *value.S.(*uuid.UUID)
			}
		case flight.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field airport_arrivals", values[i])
			} else if value.Valid {
				_m.airport_arrivals = new(uuid.UUID)
				*_m.airport_arrivals = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Flight.
// This includes values selected through modifiers, order, etc.
func (_m *Flight) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAircraft queries the "aircraft" edge of the Flight entity.
func (_m *Flight) QueryAircraft() *AircraftQuery {
	return NewFlightClient(_m.config).QueryAircraft(_m)
}

// QueryDepartureAirport queries the "departure_airport" edge of the Flight entity.
func (_m *Flight) QueryDepartureAirport() *AirportQuery {
	return NewFlightClient(_m.config).QueryDepartureAirport(_m)
}

// QueryArrivalAirport queries the "arrival_airport" edge of the Flight entity.
func (_m *Flight) QueryArrivalAirport() *AirportQuery {
	return NewFlightClient(_m.config).QueryArrivalAirport(_m)
}

// QueryFlightSeats queries the "flight_seats" edge of the Flight entity.
func (_m *Flight) QueryFlightSeats() *FlightSeatQuery {
	return NewFlightClient(_m.config).QueryFlightSeats(_m)
}

// QueryBookings queries the "bookings" edge of the Flight entity.
func (_m *Flight) QueryBookings() *BookingQuery {
	return NewFlightClient(_m.config).QueryBookings(_m)
}

// Update returns a builder for updating this Flight.
// Note that you need to call Flight.Unwrap() before calling this method if this Flight
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Flight) Update() *FlightUpdateOne {
	return NewFlightClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Flight entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Flight) Unwrap() *Flight {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Flight is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Flight) String() string {
	var builder strings.Builder
	builder.WriteString("Flight(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("flight_number=")
	builder.WriteString(_m.FlightNumber)
	builder.WriteString(", ")
	builder.WriteString("departure_time=")
	builder.WriteString(_m.DepartureTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("arrival_time=")
	builder.WriteString(_m.ArrivalTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("base_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.BasePrice))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Flights is a parsable slice of Flight.
type Flights []*Flight
