// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"pasengger_service/ent/bookingpassenger"
	"pasengger_service/ent/flight"
	"pasengger_service/ent/flightseat"
	"pasengger_service/ent/predicate"
	"pasengger_service/ent/seats"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// FlightSeatUpdate is the builder for updating FlightSeat entities.
type FlightSeatUpdate struct {
	config
	hooks    []Hook
	mutation *FlightSeatMutation
}

// Where appends a list predicates to the FlightSeatUpdate builder.
func (_u *FlightSeatUpdate) Where(ps ...predicate.FlightSeat) *FlightSeatUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *FlightSeatUpdate) SetStatus(v string) *FlightSeatUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FlightSeatUpdate) SetNillableStatus(v *string) *FlightSeatUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *FlightSeatUpdate) SetPrice(v float64) *FlightSeatUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *FlightSeatUpdate) SetNillablePrice(v *float64) *FlightSeatUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *FlightSeatUpdate) AddPrice(v float64) *FlightSeatUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// SetFlightID sets the "flight" edge to the Flight entity by ID.
func (_u *FlightSeatUpdate) SetFlightID(id uuid.UUID) *FlightSeatUpdate {
	_u.mutation.SetFlightID(id)
	return _u
}

// SetFlight sets the "flight" edge to the Flight entity.
func (_u *FlightSeatUpdate) SetFlight(v *Flight) *FlightSeatUpdate {
	return _u.SetFlightID(v.ID)
}

// SetSeatID sets the "seat" edge to the Seats entity by ID.
func (_u *FlightSeatUpdate) SetSeatID(id uuid.UUID) *FlightSeatUpdate {
	_u.mutation.SetSeatID(id)
	return _u
}

// SetSeat sets the "seat" edge to the Seats entity.
func (_u *FlightSeatUpdate) SetSeat(v *Seats) *FlightSeatUpdate {
	return _u.SetSeatID(v.ID)
}

// AddAssignedIDs adds the "assigned" edge to the BookingPassenger entity by IDs.
func (_u *FlightSeatUpdate) AddAssignedIDs(ids ...uuid.UUID) *FlightSeatUpdate {
	_u.mutation.AddAssignedIDs(ids...)
	return _u
}

// AddAssigned adds the "assigned" edges to the BookingPassenger entity.
func (_u *FlightSeatUpdate) AddAssigned(v ...*BookingPassenger) *FlightSeatUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAssignedIDs(ids...)
}

// Mutation returns the FlightSeatMutation object of the builder.
func (_u *FlightSeatUpdate) Mutation() *FlightSeatMutation {
	return _u.mutation
}

// ClearFlight clears the "flight" edge to the Flight entity.
func (_u *FlightSeatUpdate) ClearFlight() *FlightSeatUpdate {
	_u.mutation.ClearFlight()
	return _u
}

// ClearSeat clears the "seat" edge to the Seats entity.
func (_u *FlightSeatUpdate) ClearSeat() *FlightSeatUpdate {
	_u.mutation.ClearSeat()
	return _u
}

// ClearAssigned clears all "assigned" edges to the BookingPassenger entity.
func (_u *FlightSeatUpdate) ClearAssigned() *FlightSeatUpdate {
	_u.mutation.ClearAssigned()
	return _u
}

// RemoveAssignedIDs removes the "assigned" edge to BookingPassenger entities by IDs.
func (_u *FlightSeatUpdate) RemoveAssignedIDs(ids ...uuid.UUID) *FlightSeatUpdate {
	_u.mutation.RemoveAssignedIDs(ids...)
	return _u
}

// RemoveAssigned removes "assigned" edges to BookingPassenger entities.
func (_u *FlightSeatUpdate) RemoveAssigned(v ...*BookingPassenger) *FlightSeatUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAssignedIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FlightSeatUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FlightSeatUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FlightSeatUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FlightSeatUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FlightSeatUpdate) check() error {
	if _u.mutation.FlightCleared() && len(_u.mutation.FlightIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FlightSeat.flight"`)
	}
	if _u.mutation.SeatCleared() && len(_u.mutation.SeatIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FlightSeat.seat"`)
	}
	return nil
}

func (_u *FlightSeatUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(flightseat.Table, flightseat.Columns, sqlgraph.NewFieldSpec(flightseat.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(flightseat.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(flightseat.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(flightseat.FieldPrice, field.TypeFloat64, value)
	}
	if _u.mutation.FlightCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flightseat.FlightTable,
			Columns: []string{flightseat.FlightColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flight.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FlightIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flightseat.FlightTable,
			Columns: []string{flightseat.FlightColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flight.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SeatCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flightseat.SeatTable,
			Columns: []string{flightseat.SeatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seats.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SeatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flightseat.SeatTable,
			Columns: []string{flightseat.SeatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seats.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssignedCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flightseat.AssignedTable,
			Columns: []string{flightseat.AssignedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookingpassenger.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAssignedIDs(); len(nodes) > 0 && !_u.mutation.AssignedCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flightseat.AssignedTable,
			Columns: []string{flightseat.AssignedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookingpassenger.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssignedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flightseat.AssignedTable,
			Columns: []string{flightseat.AssignedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookingpassenger.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{flightseat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FlightSeatUpdateOne is the builder for updating a single FlightSeat entity.
type FlightSeatUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FlightSeatMutation
}

// SetStatus sets the "status" field.
func (_u *FlightSeatUpdateOne) SetStatus(v string) *FlightSeatUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FlightSeatUpdateOne) SetNillableStatus(v *string) *FlightSeatUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *FlightSeatUpdateOne) SetPrice(v float64) *FlightSeatUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *FlightSeatUpdateOne) SetNillablePrice(v *float64) *FlightSeatUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *FlightSeatUpdateOne) AddPrice(v float64) *FlightSeatUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// SetFlightID sets the "flight" edge to the Flight entity by ID.
func (_u *FlightSeatUpdateOne) SetFlightID(id uuid.UUID) *FlightSeatUpdateOne {
	_u.mutation.SetFlightID(id)
	return _u
}

// SetFlight sets the "flight" edge to the Flight entity.
func (_u *FlightSeatUpdateOne) SetFlight(v *Flight) *FlightSeatUpdateOne {
	return _u.SetFlightID(v.ID)
}

// SetSeatID sets the "seat" edge to the Seats entity by ID.
func (_u *FlightSeatUpdateOne) SetSeatID(id uuid.UUID) *FlightSeatUpdateOne {
	_u.mutation.SetSeatID(id)
	return _u
}

// SetSeat sets the "seat" edge to the Seats entity.
func (_u *FlightSeatUpdateOne) SetSeat(v *Seats) *FlightSeatUpdateOne {
	return _u.SetSeatID(v.ID)
}

// AddAssignedIDs adds the "assigned" edge to the BookingPassenger entity by IDs.
func (_u *FlightSeatUpdateOne) AddAssignedIDs(ids ...uuid.UUID) *FlightSeatUpdateOne {
	_u.mutation.AddAssignedIDs(ids...)
	return _u
}

// AddAssigned adds the "assigned" edges to the BookingPassenger entity.
func (_u *FlightSeatUpdateOne) AddAssigned(v ...*BookingPassenger) *FlightSeatUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAssignedIDs(ids...)
}

// Mutation returns the FlightSeatMutation object of the builder.
func (_u *FlightSeatUpdateOne) Mutation() *FlightSeatMutation {
	return _u.mutation
}

// ClearFlight clears the "flight" edge to the Flight entity.
func (_u *FlightSeatUpdateOne) ClearFlight() *FlightSeatUpdateOne {
	_u.mutation.ClearFlight()
	return _u
}

// ClearSeat clears the "seat" edge to the Seats entity.
func (_u *FlightSeatUpdateOne) ClearSeat() *FlightSeatUpdateOne {
	_u.mutation.ClearSeat()
	return _u
}

// ClearAssigned clears all "assigned" edges to the BookingPassenger entity.
func (_u *FlightSeatUpdateOne) ClearAssigned() *FlightSeatUpdateOne {
	_u.mutation.ClearAssigned()
	return _u
}

// RemoveAssignedIDs removes the "assigned" edge to BookingPassenger entities by IDs.
func (_u *FlightSeatUpdateOne) RemoveAssignedIDs(ids ...uuid.UUID) *FlightSeatUpdateOne {
	_u.mutation.RemoveAssignedIDs(ids...)
	return _u
}

// RemoveAssigned removes "assigned" edges to BookingPassenger entities.
func (_u *FlightSeatUpdateOne) RemoveAssigned(v ...*BookingPassenger) *FlightSeatUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAssignedIDs(ids...)
}

// Where appends a list predicates to the FlightSeatUpdate builder.
func (_u *FlightSeatUpdateOne) Where(ps ...predicate.FlightSeat) *FlightSeatUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FlightSeatUpdateOne) Select(field string, fields ...string) *FlightSeatUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FlightSeat entity.
func (_u *FlightSeatUpdateOne) Save(ctx context.Context) (*FlightSeat, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FlightSeatUpdateOne) SaveX(ctx context.Context) *FlightSeat {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FlightSeatUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FlightSeatUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FlightSeatUpdateOne) check() error {
	if _u.mutation.FlightCleared() && len(_u.mutation.FlightIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FlightSeat.flight"`)
	}
	if _u.mutation.SeatCleared() && len(_u.mutation.SeatIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FlightSeat.seat"`)
	}
	return nil
}

func (_u *FlightSeatUpdateOne) sqlSave(ctx context.Context) (_node *FlightSeat, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(flightseat.Table, flightseat.Columns, sqlgraph.NewFieldSpec(flightseat.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FlightSeat.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, flightseat.FieldID)
		for _, f := range fields {
			if !flightseat.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != flightseat.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(flightseat.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(flightseat.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(flightseat.FieldPrice, field.TypeFloat64, value)
	}
	if _u.mutation.FlightCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flightseat.FlightTable,
			Columns: []string{flightseat.FlightColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flight.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FlightIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flightseat.FlightTable,
			Columns: []string{flightseat.FlightColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flight.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SeatCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flightseat.SeatTable,
			Columns: []string{flightseat.SeatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seats.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SeatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flightseat.SeatTable,
			Columns: []string{flightseat.SeatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seats.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssignedCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flightseat.AssignedTable,
			Columns: []string{flightseat.AssignedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookingpassenger.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAssignedIDs(); len(nodes) > 0 && !_u.mutation.AssignedCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flightseat.AssignedTable,
			Columns: []string{flightseat.AssignedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookingpassenger.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssignedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flightseat.AssignedTable,
			Columns: []string{flightseat.AssignedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookingpassenger.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &FlightSeat{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{flightseat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
