// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"pasengger_service/ent/bookingpassenger"
	"pasengger_service/ent/flight"
	"pasengger_service/ent/flightseat"
	"pasengger_service/ent/seats"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// FlightSeatCreate is the builder for creating a FlightSeat entity.
type FlightSeatCreate struct {
	config
	mutation *FlightSeatMutation
	hooks    []Hook
}

// SetStatus sets the "status" field.
func (_c *FlightSeatCreate) SetStatus(v string) *FlightSeatCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *FlightSeatCreate) SetNillableStatus(v *string) *FlightSeatCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPrice sets the "price" field.
func (_c *FlightSeatCreate) SetPrice(v float64) *FlightSeatCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetID sets the "id" field.
func (_c *FlightSeatCreate) SetID(v uuid.UUID) *FlightSeatCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *FlightSeatCreate) SetNillableID(v *uuid.UUID) *FlightSeatCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetFlightID sets the "flight" edge to the Flight entity by ID.
func (_c *FlightSeatCreate) SetFlightID(id uuid.UUID) *FlightSeatCreate {
	_c.mutation.SetFlightID(id)
	return _c
}

// SetFlight sets the "flight" edge to the Flight entity.
func (_c *FlightSeatCreate) SetFlight(v *Flight) *FlightSeatCreate {
	return _c.SetFlightID(v.ID)
}

// SetSeatID sets the "seat" edge to the Seats entity by ID.
func (_c *FlightSeatCreate) SetSeatID(id uuid.UUID) *FlightSeatCreate {
	_c.mutation.SetSeatID(id)
	return _c
}

// SetSeat sets the "seat" edge to the Seats entity.
func (_c *FlightSeatCreate) SetSeat(v *Seats) *FlightSeatCreate {
	return _c.SetSeatID(v.ID)
}

// AddAssignedIDs adds the "assigned" edge to the BookingPassenger entity by IDs.
func (_c *FlightSeatCreate) AddAssignedIDs(ids ...uuid.UUID) *FlightSeatCreate {
	_c.mutation.AddAssignedIDs(ids...)
	return _c
}

// AddAssigned adds the "assigned" edges to the BookingPassenger entity.
func (_c *FlightSeatCreate) AddAssigned(v ...*BookingPassenger) *FlightSeatCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAssignedIDs(ids...)
}

// Mutation returns the FlightSeatMutation object of the builder.
func (_c *FlightSeatCreate) Mutation() *FlightSeatMutation {
	return _c.mutation
}

// Save creates the FlightSeat in the database.
func (_c *FlightSeatCreate) Save(ctx context.Context) (*FlightSeat, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FlightSeatCreate) SaveX(ctx context.Context) *FlightSeat {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FlightSeatCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FlightSeatCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FlightSeatCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := flightseat.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := flightseat.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FlightSeatCreate) check() error {
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "FlightSeat.status"`)}
	}
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "FlightSeat.price"`)}
	}
	if len(_c.mutation.FlightIDs()) == 0 {
		return &ValidationError{Name: "flight", err: errors.New(`ent: missing required edge "FlightSeat.flight"`)}
	}
	if len(_c.mutation.SeatIDs()) == 0 {
		return &ValidationError{Name: "seat", err: errors.New(`ent: missing required edge "FlightSeat.seat"`)}
	}
	return nil
}

func (_c *FlightSeatCreate) sqlSave(ctx context.Context) (*FlightSeat, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FlightSeatCreate) createSpec() (*FlightSeat, *sqlgraph.CreateSpec) {
	var (
		_node = &FlightSeat{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(flightseat.Table, sqlgraph.NewFieldSpec(flightseat.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(flightseat.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(flightseat.FieldPrice, field.TypeFloat64, value)
		_node.Price = value
	}
	if nodes := _c.mutation.FlightIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flightseat.FlightTable,
			Columns: []string{flightseat.FlightColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flight.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.flight_flight_seats = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SeatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flightseat.SeatTable,
			Columns: []string{flightseat.SeatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seats.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.seats_flight_instances = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AssignedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   flightseat.AssignedTable,
			Columns: []string{flightseat.AssignedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookingpassenger.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FlightSeatCreateBulk is the builder for creating many FlightSeat entities in bulk.
type FlightSeatCreateBulk struct {
	config
	err      error
	builders []*FlightSeatCreate
}

// Save creates the FlightSeat entities in the database.
func (_c *FlightSeatCreateBulk) Save(ctx context.Context) ([]*FlightSeat, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FlightSeat, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FlightSeatMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FlightSeatCreateBulk) SaveX(ctx context.Context) []*FlightSeat {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FlightSeatCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FlightSeatCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
