// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"pasengger_service/ent/aircraft"
	"pasengger_service/ent/airport"
	"pasengger_service/ent/booking"
	"pasengger_service/ent/flight"
	"pasengger_service/ent/flightseat"
	"pasengger_service/ent/predicate"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// FlightQuery is the builder for querying Flight entities.
type FlightQuery struct {
	config
	ctx                  *QueryContext
	order                []flight.OrderOption
	inters               []Interceptor
	predicates           []predicate.Flight
	withAircraft         *AircraftQuery
	withDepartureAirport *AirportQuery
	withArrivalAirport   *AirportQuery
	withFlightSeats      *FlightSeatQuery
	withBookings         *BookingQuery
	withFKs              bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FlightQuery builder.
func (_q *FlightQuery) Where(ps ...predicate.Flight) *FlightQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *FlightQuery) Limit(limit int) *FlightQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *FlightQuery) Offset(offset int) *FlightQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *FlightQuery) Unique(unique bool) *FlightQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *FlightQuery) Order(o ...flight.OrderOption) *FlightQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryAircraft chains the current query on the "aircraft" edge.
func (_q *FlightQuery) QueryAircraft() *AircraftQuery {
	query := (&AircraftClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(flight.Table, flight.FieldID, selector),
			sqlgraph.To(aircraft.Table, aircraft.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, flight.AircraftTable, flight.AircraftColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDepartureAirport chains the current query on the "departure_airport" edge.
func (_q *FlightQuery) QueryDepartureAirport() *AirportQuery {
	query := (&AirportClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(flight.Table, flight.FieldID, selector),
			sqlgraph.To(airport.Table, airport.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, flight.DepartureAirportTable, flight.DepartureAirportColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryArrivalAirport chains the current query on the "arrival_airport" edge.
func (_q *FlightQuery) QueryArrivalAirport() *AirportQuery {
	query := (&AirportClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(flight.Table, flight.FieldID, selector),
			sqlgraph.To(airport.Table, airport.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, flight.ArrivalAirportTable, flight.ArrivalAirportColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFlightSeats chains the current query on the "flight_seats" edge.
func (_q *FlightQuery) QueryFlightSeats() *FlightSeatQuery {
	query := (&FlightSeatClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(flight.Table, flight.FieldID, selector),
			sqlgraph.To(flightseat.Table, flightseat.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, flight.FlightSeatsTable, flight.FlightSeatsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryBookings chains the current query on the "bookings" edge.
func (_q *FlightQuery) QueryBookings() *BookingQuery {
	query := (&BookingClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(flight.Table, flight.FieldID, selector),
			sqlgraph.To(booking.Table, booking.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, flight.BookingsTable, flight.BookingsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Flight entity from the query.
// Returns a *NotFoundError when no Flight was found.
func (_q *FlightQuery) First(ctx context.Context) (*Flight, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{flight.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *FlightQuery) FirstX(ctx context.Context) *Flight {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Flight ID from the query.
// Returns a *NotFoundError when no Flight ID was found.
func (_q *FlightQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{flight.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *FlightQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Flight entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Flight entity is found.
// Returns a *NotFoundError when no Flight entities are found.
func (_q *FlightQuery) Only(ctx context.Context) (*Flight, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{flight.Label}
	default:
		return nil, &NotSingularError{flight.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *FlightQuery) OnlyX(ctx context.Context) *Flight {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Flight ID in the query.
// Returns a *NotSingularError when more than one Flight ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *FlightQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{flight.Label}
	default:
		err = &NotSingularError{flight.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *FlightQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Flights.
func (_q *FlightQuery) All(ctx context.Context) ([]*Flight, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Flight, *FlightQuery]()
	return withInterceptors[[]*Flight](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *FlightQuery) AllX(ctx context.Context) []*Flight {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Flight IDs.
func (_q *FlightQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(flight.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *FlightQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *FlightQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*FlightQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *FlightQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *FlightQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *FlightQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FlightQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *FlightQuery) Clone() *FlightQuery {
	if _q == nil {
		return nil
	}
	return &FlightQuery{
		config:               _q.config,
		ctx:                  _q.ctx.Clone(),
		order:                append([]flight.OrderOption{}, _q.order...),
		inters:               append([]Interceptor{}, _q.inters...),
		predicates:           append([]predicate.Flight{}, _q.predicates...),
		withAircraft:         _q.withAircraft.Clone(),
		withDepartureAirport: _q.withDepartureAirport.Clone(),
		withArrivalAirport:   _q.withArrivalAirport.Clone(),
		withFlightSeats:      _q.withFlightSeats.Clone(),
		withBookings:         _q.withBookings.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithAircraft tells the query-builder to eager-load the nodes that are connected to
// the "aircraft" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *FlightQuery) WithAircraft(opts ...func(*AircraftQuery)) *FlightQuery {
	query := (&AircraftClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAircraft = query
	return _q
}

// WithDepartureAirport tells the query-builder to eager-load the nodes that are connected to
// the "departure_airport" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *FlightQuery) WithDepartureAirport(opts ...func(*AirportQuery)) *FlightQuery {
	query := (&AirportClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDepartureAirport = query
	return _q
}

// WithArrivalAirport tells the query-builder to eager-load the nodes that are connected to
// the "arrival_airport" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *FlightQuery) WithArrivalAirport(opts ...func(*AirportQuery)) *FlightQuery {
	query := (&AirportClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withArrivalAirport = query
	return _q
}

// WithFlightSeats tells the query-builder to eager-load the nodes that are connected to
// the "flight_seats" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *FlightQuery) WithFlightSeats(opts ...func(*FlightSeatQuery)) *FlightQuery {
	query := (&FlightSeatClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withFlightSeats = query
	return _q
}

// WithBookings tells the query-builder to eager-load the nodes that are connected to
// the "bookings" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *FlightQuery) WithBookings(opts ...func(*BookingQuery)) *FlightQuery {
	query := (&BookingClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withBookings = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		FlightNumber string `json:"flight_number,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Flight.Query().
//		GroupBy(flight.FieldFlightNumber).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *FlightQuery) GroupBy(field string, fields ...string) *FlightGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FlightGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = flight.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		FlightNumber string `json:"flight_number,omitempty"`
//	}
//
//	client.Flight.Query().
//		Select(flight.FieldFlightNumber).
//		Scan(ctx, &v)
func (_q *FlightQuery) Select(fields ...string) *FlightSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &FlightSelect{FlightQuery: _q}
	sbuild.label = flight.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FlightSelect configured with the given aggregations.
func (_q *FlightQuery) Aggregate(fns ...AggregateFunc) *FlightSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *FlightQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !flight.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *FlightQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Flight, error) {
	var (
		nodes       = []*Flight{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [5]bool{
			_q.withAircraft != nil,
			_q.withDepartureAirport != nil,
			_q.withArrivalAirport != nil,
			_q.withFlightSeats != nil,
			_q.withBookings != nil,
		}
	)
	if _q.withAircraft != nil || _q.withDepartureAirport != nil || _q.withArrivalAirport != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, flight.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Flight).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Flight{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withAircraft; query != nil {
		if err := _q.loadAircraft(ctx, query, nodes, nil,
			func(n *Flight, e *Aircraft) { n.Edges.Aircraft = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withDepartureAirport; query != nil {
		if err := _q.loadDepartureAirport(ctx, query, nodes, nil,
			func(n *Flight, e *Airport) { n.Edges.DepartureAirport = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withArrivalAirport; query != nil {
		if err := _q.loadArrivalAirport(ctx, query, nodes, nil,
			func(n *Flight, e *Airport) { n.Edges.ArrivalAirport = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withFlightSeats; query != nil {
		if err := _q.loadFlightSeats(ctx, query, nodes,
			func(n *Flight) { n.Edges.FlightSeats = []*FlightSeat{} },
			func(n *Flight, e *FlightSeat) { n.Edges.FlightSeats = append(n.Edges.FlightSeats, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withBookings; query != nil {
		if err := _q.loadBookings(ctx, query, nodes,
			func(n *Flight) { n.Edges.Bookings = []*Booking{} },
			func(n *Flight, e *Booking) { n.Edges.Bookings = append(n.Edges.Bookings, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *FlightQuery) loadAircraft(ctx context.Context, query *AircraftQuery, nodes []*Flight, init func(*Flight), assign func(*Flight, *Aircraft)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Flight)
	for i := range nodes {
		if nodes[i].aircraft_flights == nil {
			continue
		}
		fk := *nodes[i].aircraft_flights
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(aircraft.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "aircraft_flights" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *FlightQuery) loadDepartureAirport(ctx context.Context, query *AirportQuery, nodes []*Flight, init func(*Flight), assign func(*Flight, *Airport)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Flight)
	for i := range nodes {
		if nodes[i].airport_departures == nil {
			continue
		}
		fk := *nodes[i].airport_departures
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(airport.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "airport_departures" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *FlightQuery) loadArrivalAirport(ctx context.Context, query *AirportQuery, nodes []*Flight, init func(*Flight), assign func(*Flight, *Airport)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Flight)
	for i := range nodes {
		if nodes[i].airport_arrivals == nil {
			continue
		}
		fk := *nodes[i].airport_arrivals
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(airport.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "airport_arrivals" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *FlightQuery) loadFlightSeats(ctx context.Context, query *FlightSeatQuery, nodes []*Flight, init func(*Flight), assign func(*Flight, *FlightSeat)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Flight)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.FlightSeat(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(flight.FlightSeatsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.flight_flight_seats
		if fk == nil {
			return fmt.Errorf(`foreign-key "flight_flight_seats" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "flight_flight_seats" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *FlightQuery) loadBookings(ctx context.Context, query *BookingQuery, nodes []*Flight, init func(*Flight), assign func(*Flight, *Booking)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Flight)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Booking(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(flight.BookingsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.flight_bookings
		if fk == nil {
			return fmt.Errorf(`foreign-key "flight_bookings" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "flight_bookings" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *FlightQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *FlightQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(flight.Table, flight.Columns, sqlgraph.NewFieldSpec(flight.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, flight.FieldID)
		for i := range fields {
			if fields[i] != flight.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *FlightQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(flight.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = flight.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FlightGroupBy is the group-by builder for Flight entities.
type FlightGroupBy struct {
	selector
	build *FlightQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *FlightGroupBy) Aggregate(fns ...AggregateFunc) *FlightGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *FlightGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FlightQuery, *FlightGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *FlightGroupBy) sqlScan(ctx context.Context, root *FlightQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FlightSelect is the builder for selecting fields of Flight entities.
type FlightSelect struct {
	*FlightQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *FlightSelect) Aggregate(fns ...AggregateFunc) *FlightSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *FlightSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FlightQuery, *FlightSelect](ctx, _s.FlightQuery, _s, _s.inters, v)
}

func (_s *FlightSelect) sqlScan(ctx context.Context, root *FlightQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
