// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"pasengger_service/ent/passenger"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Passenger is the model entity for the Passenger schema.
type Passenger struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// FirstName holds the value of the "first_name" field.
	FirstName string `json:"first_name,omitempty"`
	// LastName holds the value of the "last_name" field.
	LastName string `json:"last_name,omitempty"`
	// DateOfBirth holds the value of the "date_of_birth" field.
	DateOfBirth time.Time `json:"date_of_birth,omitempty"`
	// PassportNumber holds the value of the "passport_number" field.
	PassportNumber *string `json:"passport_number,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PassengerQuery when eager-loading is set.
	Edges        PassengerEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PassengerEdges holds the relations/edges for other nodes in the graph.
type PassengerEdges struct {
	// BookingEntries holds the value of the booking_entries edge.
	BookingEntries []*BookingPassenger `json:"booking_entries,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// BookingEntriesOrErr returns the BookingEntries value or an error if the edge
// was not loaded in eager-loading.
func (e PassengerEdges) BookingEntriesOrErr() ([]*BookingPassenger, error) {
	if e.loadedTypes[0] {
		return e.BookingEntries, nil
	}
	return nil, &NotLoadedError{edge: "booking_entries"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Passenger) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case passenger.FieldFirstName, passenger.FieldLastName, passenger.FieldPassportNumber:
			values[i] = new(sql.NullString)
		case passenger.FieldDateOfBirth, passenger.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case passenger.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Passenger fields.
func (_m *Passenger) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case passenger.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case passenger.FieldFirstName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field first_name", values[i])
			} else if value.Valid {
				_m.FirstName = value.String
			}
		case passenger.FieldLastName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_name", values[i])
			} else if value.Valid {
				_m.LastName = value.String
			}
		case passenger.FieldDateOfBirth:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_of_birth", values[i])
			} else if value.Valid {
				_m.DateOfBirth = value.Time
			}
		case passenger.FieldPassportNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field passport_number", values[i])
			} else if value.Valid {
				_m.PassportNumber = new(string)
				*_m.PassportNumber = value.String
			}
		case passenger.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Passenger.
// This includes values selected through modifiers, order, etc.
func (_m *Passenger) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryBookingEntries queries the "booking_entries" edge of the Passenger entity.
func (_m *Passenger) QueryBookingEntries() *BookingPassengerQuery {
	return NewPassengerClient(_m.config).QueryBookingEntries(_m)
}

// Update returns a builder for updating this Passenger.
// Note that you need to call Passenger.Unwrap() before calling this method if this Passenger
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Passenger) Update() *PassengerUpdateOne {
	return NewPassengerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Passenger entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Passenger) Unwrap() *Passenger {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Passenger is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Passenger) String() string {
	var builder strings.Builder
	builder.WriteString("Passenger(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("first_name=")
	builder.WriteString(_m.FirstName)
	builder.WriteString(", ")
	builder.WriteString("last_name=")
	builder.WriteString(_m.LastName)
	builder.WriteString(", ")
	builder.WriteString("date_of_birth=")
	builder.WriteString(_m.DateOfBirth.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.PassportNumber; v != nil {
		builder.WriteString("passport_number=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Passengers is a parsable slice of Passenger.
type Passengers []*Passenger
