// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"pasengger_service/ent/bookingpassenger"
	"pasengger_service/ent/passenger"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PassengerCreate is the builder for creating a Passenger entity.
type PassengerCreate struct {
	config
	mutation *PassengerMutation
	hooks    []Hook
}

// SetFirstName sets the "first_name" field.
func (_c *PassengerCreate) SetFirstName(v string) *PassengerCreate {
	_c.mutation.SetFirstName(v)
	return _c
}

// SetLastName sets the "last_name" field.
func (_c *PassengerCreate) SetLastName(v string) *PassengerCreate {
	_c.mutation.SetLastName(v)
	return _c
}

// SetDateOfBirth sets the "date_of_birth" field.
func (_c *PassengerCreate) SetDateOfBirth(v time.Time) *PassengerCreate {
	_c.mutation.SetDateOfBirth(v)
	return _c
}

// SetPassportNumber sets the "passport_number" field.
func (_c *PassengerCreate) SetPassportNumber(v string) *PassengerCreate {
	_c.mutation.SetPassportNumber(v)
	return _c
}

// SetNillablePassportNumber sets the "passport_number" field if the given value is not nil.
func (_c *PassengerCreate) SetNillablePassportNumber(v *string) *PassengerCreate {
	if v != nil {
		_c.SetPassportNumber(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PassengerCreate) SetCreatedAt(v time.Time) *PassengerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PassengerCreate) SetNillableCreatedAt(v *time.Time) *PassengerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PassengerCreate) SetID(v uuid.UUID) *PassengerCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PassengerCreate) SetNillableID(v *uuid.UUID) *PassengerCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddBookingEntryIDs adds the "booking_entries" edge to the BookingPassenger entity by IDs.
func (_c *PassengerCreate) AddBookingEntryIDs(ids ...uuid.UUID) *PassengerCreate {
	_c.mutation.AddBookingEntryIDs(ids...)
	return _c
}

// AddBookingEntries adds the "booking_entries" edges to the BookingPassenger entity.
func (_c *PassengerCreate) AddBookingEntries(v ...*BookingPassenger) *PassengerCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBookingEntryIDs(ids...)
}

// Mutation returns the PassengerMutation object of the builder.
func (_c *PassengerCreate) Mutation() *PassengerMutation {
	return _c.mutation
}

// Save creates the Passenger in the database.
func (_c *PassengerCreate) Save(ctx context.Context) (*Passenger, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PassengerCreate) SaveX(ctx context.Context) *Passenger {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PassengerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PassengerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PassengerCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := passenger.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := passenger.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PassengerCreate) check() error {
	if _, ok := _c.mutation.FirstName(); !ok {
		return &ValidationError{Name: "first_name", err: errors.New(`ent: missing required field "Passenger.first_name"`)}
	}
	if _, ok := _c.mutation.LastName(); !ok {
		return &ValidationError{Name: "last_name", err: errors.New(`ent: missing required field "Passenger.last_name"`)}
	}
	if _, ok := _c.mutation.DateOfBirth(); !ok {
		return &ValidationError{Name: "date_of_birth", err: errors.New(`ent: missing required field "Passenger.date_of_birth"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Passenger.created_at"`)}
	}
	return nil
}

func (_c *PassengerCreate) sqlSave(ctx context.Context) (*Passenger, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PassengerCreate) createSpec() (*Passenger, *sqlgraph.CreateSpec) {
	var (
		_node = &Passenger{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(passenger.Table, sqlgraph.NewFieldSpec(passenger.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.FirstName(); ok {
		_spec.SetField(passenger.FieldFirstName, field.TypeString, value)
		_node.FirstName = value
	}
	if value, ok := _c.mutation.LastName(); ok {
		_spec.SetField(passenger.FieldLastName, field.TypeString, value)
		_node.LastName = value
	}
	if value, ok := _c.mutation.DateOfBirth(); ok {
		_spec.SetField(passenger.FieldDateOfBirth, field.TypeTime, value)
		_node.DateOfBirth = value
	}
	if value, ok := _c.mutation.PassportNumber(); ok {
		_spec.SetField(passenger.FieldPassportNumber, field.TypeString, value)
		_node.PassportNumber = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(passenger.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.BookingEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   passenger.BookingEntriesTable,
			Columns: []string{passenger.BookingEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookingpassenger.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PassengerCreateBulk is the builder for creating many Passenger entities in bulk.
type PassengerCreateBulk struct {
	config
	err      error
	builders []*PassengerCreate
}

// Save creates the Passenger entities in the database.
func (_c *PassengerCreateBulk) Save(ctx context.Context) ([]*Passenger, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Passenger, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PassengerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PassengerCreateBulk) SaveX(ctx context.Context) []*Passenger {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PassengerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PassengerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
