// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"pasengger_service/ent/booking"
	"pasengger_service/ent/payment"
	"pasengger_service/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PaymentUpdate is the builder for updating Payment entities.
type PaymentUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentMutation
}

// Where appends a list predicates to the PaymentUpdate builder.
func (_u *PaymentUpdate) Where(ps ...predicate.Payment) *PaymentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *PaymentUpdate) SetAmount(v float64) *PaymentUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableAmount(v *float64) *PaymentUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *PaymentUpdate) AddAmount(v float64) *PaymentUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *PaymentUpdate) SetProvider(v string) *PaymentUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableProvider(v *string) *PaymentUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentUpdate) SetStatus(v string) *PaymentUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableStatus(v *string) *PaymentUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *PaymentUpdate) SetPaidAt(v time.Time) *PaymentUpdate {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillablePaidAt(v *time.Time) *PaymentUpdate {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *PaymentUpdate) ClearPaidAt() *PaymentUpdate {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PaymentUpdate) SetCreatedAt(v time.Time) *PaymentUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableCreatedAt(v *time.Time) *PaymentUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetBookingID sets the "booking" edge to the Booking entity by ID.
func (_u *PaymentUpdate) SetBookingID(id uuid.UUID) *PaymentUpdate {
	_u.mutation.SetBookingID(id)
	return _u
}

// SetBooking sets the "booking" edge to the Booking entity.
func (_u *PaymentUpdate) SetBooking(v *Booking) *PaymentUpdate {
	return _u.SetBookingID(v.ID)
}

// Mutation returns the PaymentMutation object of the builder.
func (_u *PaymentUpdate) Mutation() *PaymentMutation {
	return _u.mutation
}

// ClearBooking clears the "booking" edge to the Booking entity.
func (_u *PaymentUpdate) ClearBooking() *PaymentUpdate {
	_u.mutation.ClearBooking()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentUpdate) check() error {
	if _u.mutation.BookingCleared() && len(_u.mutation.BookingIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Payment.booking"`)
	}
	return nil
}

func (_u *PaymentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(payment.Table, payment.Columns, sqlgraph.NewFieldSpec(payment.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(payment.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(payment.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(payment.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(payment.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(payment.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(payment.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(payment.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.BookingCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.BookingTable,
			Columns: []string{payment.BookingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BookingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.BookingTable,
			Columns: []string{payment.BookingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentUpdateOne is the builder for updating a single Payment entity.
type PaymentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentMutation
}

// SetAmount sets the "amount" field.
func (_u *PaymentUpdateOne) SetAmount(v float64) *PaymentUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableAmount(v *float64) *PaymentUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *PaymentUpdateOne) AddAmount(v float64) *PaymentUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *PaymentUpdateOne) SetProvider(v string) *PaymentUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableProvider(v *string) *PaymentUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentUpdateOne) SetStatus(v string) *PaymentUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableStatus(v *string) *PaymentUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *PaymentUpdateOne) SetPaidAt(v time.Time) *PaymentUpdateOne {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillablePaidAt(v *time.Time) *PaymentUpdateOne {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *PaymentUpdateOne) ClearPaidAt() *PaymentUpdateOne {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PaymentUpdateOne) SetCreatedAt(v time.Time) *PaymentUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableCreatedAt(v *time.Time) *PaymentUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetBookingID sets the "booking" edge to the Booking entity by ID.
func (_u *PaymentUpdateOne) SetBookingID(id uuid.UUID) *PaymentUpdateOne {
	_u.mutation.SetBookingID(id)
	return _u
}

// SetBooking sets the "booking" edge to the Booking entity.
func (_u *PaymentUpdateOne) SetBooking(v *Booking) *PaymentUpdateOne {
	return _u.SetBookingID(v.ID)
}

// Mutation returns the PaymentMutation object of the builder.
func (_u *PaymentUpdateOne) Mutation() *PaymentMutation {
	return _u.mutation
}

// ClearBooking clears the "booking" edge to the Booking entity.
func (_u *PaymentUpdateOne) ClearBooking() *PaymentUpdateOne {
	_u.mutation.ClearBooking()
	return _u
}

// Where appends a list predicates to the PaymentUpdate builder.
func (_u *PaymentUpdateOne) Where(ps ...predicate.Payment) *PaymentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentUpdateOne) Select(field string, fields ...string) *PaymentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Payment entity.
func (_u *PaymentUpdateOne) Save(ctx context.Context) (*Payment, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentUpdateOne) SaveX(ctx context.Context) *Payment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentUpdateOne) check() error {
	if _u.mutation.BookingCleared() && len(_u.mutation.BookingIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Payment.booking"`)
	}
	return nil
}

func (_u *PaymentUpdateOne) sqlSave(ctx context.Context) (_node *Payment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(payment.Table, payment.Columns, sqlgraph.NewFieldSpec(payment.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Payment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, payment.FieldID)
		for _, f := range fields {
			if !payment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != payment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(payment.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(payment.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(payment.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(payment.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(payment.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(payment.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(payment.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.BookingCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.BookingTable,
			Columns: []string{payment.BookingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BookingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.BookingTable,
			Columns: []string{payment.BookingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Payment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
