// Code generated by ent, DO NOT EDIT.

package ent

import (
	"pasengger_service/ent/aircraft"
	"pasengger_service/ent/airport"
	"pasengger_service/ent/booking"
	"pasengger_service/ent/bookingpassenger"
	"pasengger_service/ent/flight"
	"pasengger_service/ent/flightseat"
	"pasengger_service/ent/passenger"
	"pasengger_service/ent/payment"
	"pasengger_service/ent/schema"
	"pasengger_service/ent/seats"
	"pasengger_service/ent/user"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	aircraftFields := schema.Aircraft{}.Fields()
	_ = aircraftFields
	// aircraftDescCreatedAt is the schema descriptor for created_at field.
	aircraftDescCreatedAt := aircraftFields[4].Descriptor()
	// aircraft.DefaultCreatedAt holds the default value on creation for the created_at field.
	aircraft.DefaultCreatedAt = aircraftDescCreatedAt.Default.(func() time.Time)
	// aircraftDescID is the schema descriptor for id field.
	aircraftDescID := aircraftFields[0].Descriptor()
	// aircraft.DefaultID holds the default value on creation for the id field.
	aircraft.DefaultID = aircraftDescID.Default.(func() uuid.UUID)
	airportFields := schema.Airport{}.Fields()
	_ = airportFields
	// airportDescCode is the schema descriptor for code field.
	airportDescCode := airportFields[1].Descriptor()
	// airport.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	airport.CodeValidator = airportDescCode.Validators[0].(func(string) error)
	// airportDescCreatedAt is the schema descriptor for created_at field.
	airportDescCreatedAt := airportFields[5].Descriptor()
	// airport.DefaultCreatedAt holds the default value on creation for the created_at field.
	airport.DefaultCreatedAt = airportDescCreatedAt.Default.(func() time.Time)
	// airportDescID is the schema descriptor for id field.
	airportDescID := airportFields[0].Descriptor()
	// airport.DefaultID holds the default value on creation for the id field.
	airport.DefaultID = airportDescID.Default.(func() uuid.UUID)
	bookingFields := schema.Booking{}.Fields()
	_ = bookingFields
	// bookingDescStatus is the schema descriptor for status field.
	bookingDescStatus := bookingFields[3].Descriptor()
	// booking.DefaultStatus holds the default value on creation for the status field.
	booking.DefaultStatus = bookingDescStatus.Default.(string)
	// bookingDescCreatedAt is the schema descriptor for created_at field.
	bookingDescCreatedAt := bookingFields[5].Descriptor()
	// booking.DefaultCreatedAt holds the default value on creation for the created_at field.
	booking.DefaultCreatedAt = bookingDescCreatedAt.Default.(func() time.Time)
	// bookingDescID is the schema descriptor for id field.
	bookingDescID := bookingFields[0].Descriptor()
	// booking.DefaultID holds the default value on creation for the id field.
	booking.DefaultID = bookingDescID.Default.(func() uuid.UUID)
	bookingpassengerFields := schema.BookingPassenger{}.Fields()
	_ = bookingpassengerFields
	// bookingpassengerDescID is the schema descriptor for id field.
	bookingpassengerDescID := bookingpassengerFields[0].Descriptor()
	// bookingpassenger.DefaultID holds the default value on creation for the id field.
	bookingpassenger.DefaultID = bookingpassengerDescID.Default.(func() uuid.UUID)
	flightFields := schema.Flight{}.Fields()
	_ = flightFields
	// flightDescStatus is the schema descriptor for status field.
	flightDescStatus := flightFields[5].Descriptor()
	// flight.DefaultStatus holds the default value on creation for the status field.
	flight.DefaultStatus = flightDescStatus.Default.(string)
	// flightDescCreatedAt is the schema descriptor for created_at field.
	flightDescCreatedAt := flightFields[6].Descriptor()
	// flight.DefaultCreatedAt holds the default value on creation for the created_at field.
	flight.DefaultCreatedAt = flightDescCreatedAt.Default.(func() time.Time)
	// flightDescID is the schema descriptor for id field.
	flightDescID := flightFields[0].Descriptor()
	// flight.DefaultID holds the default value on creation for the id field.
	flight.DefaultID = flightDescID.Default.(func() uuid.UUID)
	flightseatFields := schema.FlightSeat{}.Fields()
	_ = flightseatFields
	// flightseatDescStatus is the schema descriptor for status field.
	flightseatDescStatus := flightseatFields[1].Descriptor()
	// flightseat.DefaultStatus holds the default value on creation for the status field.
	flightseat.DefaultStatus = flightseatDescStatus.Default.(string)
	// flightseatDescID is the schema descriptor for id field.
	flightseatDescID := flightseatFields[0].Descriptor()
	// flightseat.DefaultID holds the default value on creation for the id field.
	flightseat.DefaultID = flightseatDescID.Default.(func() uuid.UUID)
	passengerFields := schema.Passenger{}.Fields()
	_ = passengerFields
	// passengerDescCreatedAt is the schema descriptor for created_at field.
	passengerDescCreatedAt := passengerFields[5].Descriptor()
	// passenger.DefaultCreatedAt holds the default value on creation for the created_at field.
	passenger.DefaultCreatedAt = passengerDescCreatedAt.Default.(func() time.Time)
	// passengerDescID is the schema descriptor for id field.
	passengerDescID := passengerFields[0].Descriptor()
	// passenger.DefaultID holds the default value on creation for the id field.
	passenger.DefaultID = passengerDescID.Default.(func() uuid.UUID)
	paymentFields := schema.Payment{}.Fields()
	_ = paymentFields
	// paymentDescStatus is the schema descriptor for status field.
	paymentDescStatus := paymentFields[3].Descriptor()
	// payment.DefaultStatus holds the default value on creation for the status field.
	payment.DefaultStatus = paymentDescStatus.Default.(string)
	// paymentDescCreatedAt is the schema descriptor for created_at field.
	paymentDescCreatedAt := paymentFields[5].Descriptor()
	// payment.DefaultCreatedAt holds the default value on creation for the created_at field.
	payment.DefaultCreatedAt = paymentDescCreatedAt.Default.(func() time.Time)
	// paymentDescID is the schema descriptor for id field.
	paymentDescID := paymentFields[0].Descriptor()
	// payment.DefaultID holds the default value on creation for the id field.
	payment.DefaultID = paymentDescID.Default.(func() uuid.UUID)
	seatsFields := schema.Seats{}.Fields()
	_ = seatsFields
	// seatsDescSeatClass is the schema descriptor for seat_class field.
	seatsDescSeatClass := seatsFields[2].Descriptor()
	// seats.DefaultSeatClass holds the default value on creation for the seat_class field.
	seats.DefaultSeatClass = seatsDescSeatClass.Default.(string)
	// seatsDescID is the schema descriptor for id field.
	seatsDescID := seatsFields[0].Descriptor()
	// seats.DefaultID holds the default value on creation for the id field.
	seats.DefaultID = seatsDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[2].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescFullName is the schema descriptor for full_name field.
	userDescFullName := userFields[3].Descriptor()
	// user.FullNameValidator is a validator for the "full_name" field. It is called by the builders before save.
	user.FullNameValidator = userDescFullName.Validators[0].(func(string) error)
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[4].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[6].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
