// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"pasengger_service/ent/aircraft"
	"pasengger_service/ent/seats"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Seats is the model entity for the Seats schema.
type Seats struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// SeatNumber holds the value of the "seat_number" field.
	SeatNumber string `json:"seat_number,omitempty"`
	// SeatClass holds the value of the "seat_class" field.
	SeatClass string `json:"seat_class,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SeatsQuery when eager-loading is set.
	Edges          SeatsEdges `json:"edges"`
	aircraft_seats *uuid.UUID
	selectValues   sql.SelectValues
}

// SeatsEdges holds the relations/edges for other nodes in the graph.
type SeatsEdges struct {
	// Aircraft holds the value of the aircraft edge.
	Aircraft *Aircraft `json:"aircraft,omitempty"`
	// FlightInstances holds the value of the flight_instances edge.
	FlightInstances []*FlightSeat `json:"flight_instances,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AircraftOrErr returns the Aircraft value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SeatsEdges) AircraftOrErr() (*Aircraft, error) {
	if e.Aircraft != nil {
		return e.Aircraft, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: aircraft.Label}
	}
	return nil, &NotLoadedError{edge: "aircraft"}
}

// FlightInstancesOrErr returns the FlightInstances value or an error if the edge
// was not loaded in eager-loading.
func (e SeatsEdges) FlightInstancesOrErr() ([]*FlightSeat, error) {
	if e.loadedTypes[1] {
		return e.FlightInstances, nil
	}
	return nil, &NotLoadedError{edge: "flight_instances"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Seats) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case seats.FieldSeatNumber, seats.FieldSeatClass:
			values[i] = new(sql.NullString)
		case seats.FieldID:
			values[i] = new(uuid.UUID)
		case seats.ForeignKeys[0]: // aircraft_seats
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Seats fields.
func (_m *Seats) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case seats.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case seats.FieldSeatNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field seat_number", values[i])
			} else if value.Valid {
				_m.SeatNumber = value.String
			}
		case seats.FieldSeatClass:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field seat_class", values[i])
			} else if value.Valid {
				_m.SeatClass = value.String
			}
		case seats.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field aircraft_seats", values[i])
			} else if value.Valid {
				_m.aircraft_seats = new(uuid.UUID)
				*_m.aircraft_seats = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Seats.
// This includes values selected through modifiers, order, etc.
func (_m *Seats) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAircraft queries the "aircraft" edge of the Seats entity.
func (_m *Seats) QueryAircraft() *AircraftQuery {
	return NewSeatsClient(_m.config).QueryAircraft(_m)
}

// QueryFlightInstances queries the "flight_instances" edge of the Seats entity.
func (_m *Seats) QueryFlightInstances() *FlightSeatQuery {
	return NewSeatsClient(_m.config).QueryFlightInstances(_m)
}

// Update returns a builder for updating this Seats.
// Note that you need to call Seats.Unwrap() before calling this method if this Seats
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Seats) Update() *SeatsUpdateOne {
	return NewSeatsClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Seats entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Seats) Unwrap() *Seats {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Seats is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Seats) String() string {
	var builder strings.Builder
	builder.WriteString("Seats(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("seat_number=")
	builder.WriteString(_m.SeatNumber)
	builder.WriteString(", ")
	builder.WriteString("seat_class=")
	builder.WriteString(_m.SeatClass)
	builder.WriteByte(')')
	return builder.String()
}

// SeatsSlice is a parsable slice of Seats.
type SeatsSlice []*Seats
