// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"pasengger_service/ent/aircraft"
	"pasengger_service/ent/flightseat"
	"pasengger_service/ent/seats"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// SeatsCreate is the builder for creating a Seats entity.
type SeatsCreate struct {
	config
	mutation *SeatsMutation
	hooks    []Hook
}

// SetSeatNumber sets the "seat_number" field.
func (_c *SeatsCreate) SetSeatNumber(v string) *SeatsCreate {
	_c.mutation.SetSeatNumber(v)
	return _c
}

// SetSeatClass sets the "seat_class" field.
func (_c *SeatsCreate) SetSeatClass(v string) *SeatsCreate {
	_c.mutation.SetSeatClass(v)
	return _c
}

// SetNillableSeatClass sets the "seat_class" field if the given value is not nil.
func (_c *SeatsCreate) SetNillableSeatClass(v *string) *SeatsCreate {
	if v != nil {
		_c.SetSeatClass(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SeatsCreate) SetID(v uuid.UUID) *SeatsCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SeatsCreate) SetNillableID(v *uuid.UUID) *SeatsCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetAircraftID sets the "aircraft" edge to the Aircraft entity by ID.
func (_c *SeatsCreate) SetAircraftID(id uuid.UUID) *SeatsCreate {
	_c.mutation.SetAircraftID(id)
	return _c
}

// SetAircraft sets the "aircraft" edge to the Aircraft entity.
func (_c *SeatsCreate) SetAircraft(v *Aircraft) *SeatsCreate {
	return _c.SetAircraftID(v.ID)
}

// AddFlightInstanceIDs adds the "flight_instances" edge to the FlightSeat entity by IDs.
func (_c *SeatsCreate) AddFlightInstanceIDs(ids ...uuid.UUID) *SeatsCreate {
	_c.mutation.AddFlightInstanceIDs(ids...)
	return _c
}

// AddFlightInstances adds the "flight_instances" edges to the FlightSeat entity.
func (_c *SeatsCreate) AddFlightInstances(v ...*FlightSeat) *SeatsCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddFlightInstanceIDs(ids...)
}

// Mutation returns the SeatsMutation object of the builder.
func (_c *SeatsCreate) Mutation() *SeatsMutation {
	return _c.mutation
}

// Save creates the Seats in the database.
func (_c *SeatsCreate) Save(ctx context.Context) (*Seats, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SeatsCreate) SaveX(ctx context.Context) *Seats {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SeatsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SeatsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SeatsCreate) defaults() {
	if _, ok := _c.mutation.SeatClass(); !ok {
		v := seats.DefaultSeatClass
		_c.mutation.SetSeatClass(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := seats.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SeatsCreate) check() error {
	if _, ok := _c.mutation.SeatNumber(); !ok {
		return &ValidationError{Name: "seat_number", err: errors.New(`ent: missing required field "Seats.seat_number"`)}
	}
	if _, ok := _c.mutation.SeatClass(); !ok {
		return &ValidationError{Name: "seat_class", err: errors.New(`ent: missing required field "Seats.seat_class"`)}
	}
	if len(_c.mutation.AircraftIDs()) == 0 {
		return &ValidationError{Name: "aircraft", err: errors.New(`ent: missing required edge "Seats.aircraft"`)}
	}
	return nil
}

func (_c *SeatsCreate) sqlSave(ctx context.Context) (*Seats, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SeatsCreate) createSpec() (*Seats, *sqlgraph.CreateSpec) {
	var (
		_node = &Seats{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(seats.Table, sqlgraph.NewFieldSpec(seats.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.SeatNumber(); ok {
		_spec.SetField(seats.FieldSeatNumber, field.TypeString, value)
		_node.SeatNumber = value
	}
	if value, ok := _c.mutation.SeatClass(); ok {
		_spec.SetField(seats.FieldSeatClass, field.TypeString, value)
		_node.SeatClass = value
	}
	if nodes := _c.mutation.AircraftIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   seats.AircraftTable,
			Columns: []string{seats.AircraftColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(aircraft.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.aircraft_seats = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.FlightInstancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   seats.FlightInstancesTable,
			Columns: []string{seats.FlightInstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flightseat.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SeatsCreateBulk is the builder for creating many Seats entities in bulk.
type SeatsCreateBulk struct {
	config
	err      error
	builders []*SeatsCreate
}

// Save creates the Seats entities in the database.
func (_c *SeatsCreateBulk) Save(ctx context.Context) ([]*Seats, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Seats, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SeatsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SeatsCreateBulk) SaveX(ctx context.Context) []*Seats {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SeatsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SeatsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
