// Code generated by ent, DO NOT EDIT.

package bookingpassenger

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the bookingpassenger type in the database.
	Label = "booking_passenger"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// EdgeBooking holds the string denoting the booking edge name in mutations.
	EdgeBooking = "booking"
	// EdgePassenger holds the string denoting the passenger edge name in mutations.
	EdgePassenger = "passenger"
	// EdgeFlightSeat holds the string denoting the flight_seat edge name in mutations.
	EdgeFlightSeat = "flight_seat"
	// Table holds the table name of the bookingpassenger in the database.
	Table = "booking_passengers"
	// BookingTable is the table that holds the booking relation/edge.
	BookingTable = "booking_passengers"
	// BookingInverseTable is the table name for the Booking entity.
	// It exists in this package in order to avoid circular dependency with the "booking" package.
	BookingInverseTable = "bookings"
	// BookingColumn is the table column denoting the booking relation/edge.
	BookingColumn = "booking_booking_passengers"
	// PassengerTable is the table that holds the passenger relation/edge.
	PassengerTable = "booking_passengers"
	// PassengerInverseTable is the table name for the Passenger entity.
	// It exists in this package in order to avoid circular dependency with the "passenger" package.
	PassengerInverseTable = "passengers"
	// PassengerColumn is the table column denoting the passenger relation/edge.
	PassengerColumn = "passenger_booking_entries"
	// FlightSeatTable is the table that holds the flight_seat relation/edge.
	FlightSeatTable = "booking_passengers"
	// FlightSeatInverseTable is the table name for the FlightSeat entity.
	// It exists in this package in order to avoid circular dependency with the "flightseat" package.
	FlightSeatInverseTable = "flight_seats"
	// FlightSeatColumn is the table column denoting the flight_seat relation/edge.
	FlightSeatColumn = "flight_seat_assigned"
)

// Columns holds all SQL columns for bookingpassenger fields.
var Columns = []string{
	FieldID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "booking_passengers"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"booking_booking_passengers",
	"flight_seat_assigned",
	"passenger_booking_entries",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the BookingPassenger queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBookingField orders the results by booking field.
func ByBookingField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBookingStep(), sql.OrderByField(field, opts...))
	}
}

// ByPassengerField orders the results by passenger field.
func ByPassengerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPassengerStep(), sql.OrderByField(field, opts...))
	}
}

// ByFlightSeatField orders the results by flight_seat field.
func ByFlightSeatField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFlightSeatStep(), sql.OrderByField(field, opts...))
	}
}
func newBookingStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BookingInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, BookingTable, BookingColumn),
	)
}
func newPassengerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PassengerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PassengerTable, PassengerColumn),
	)
}
func newFlightSeatStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FlightSeatInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, FlightSeatTable, FlightSeatColumn),
	)
}
