// Code generated by ent, DO NOT EDIT.

package bookingpassenger

import (
	"pasengger_service/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.BookingPassenger {
	return predicate.BookingPassenger(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.BookingPassenger {
	return predicate.BookingPassenger(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.BookingPassenger {
	return predicate.BookingPassenger(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.BookingPassenger {
	return predicate.BookingPassenger(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.BookingPassenger {
	return predicate.BookingPassenger(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.BookingPassenger {
	return predicate.BookingPassenger(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.BookingPassenger {
	return predicate.BookingPassenger(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.BookingPassenger {
	return predicate.BookingPassenger(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.BookingPassenger {
	return predicate.BookingPassenger(sql.FieldLTE(FieldID, id))
}

// HasBooking applies the HasEdge predicate on the "booking" edge.
func HasBooking() predicate.BookingPassenger {
	return predicate.BookingPassenger(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, BookingTable, BookingColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBookingWith applies the HasEdge predicate on the "booking" edge with a given conditions (other predicates).
func HasBookingWith(preds ...predicate.Booking) predicate.BookingPassenger {
	return predicate.BookingPassenger(func(s *sql.Selector) {
		step := newBookingStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPassenger applies the HasEdge predicate on the "passenger" edge.
func HasPassenger() predicate.BookingPassenger {
	return predicate.BookingPassenger(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PassengerTable, PassengerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPassengerWith applies the HasEdge predicate on the "passenger" edge with a given conditions (other predicates).
func HasPassengerWith(preds ...predicate.Passenger) predicate.BookingPassenger {
	return predicate.BookingPassenger(func(s *sql.Selector) {
		step := newPassengerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasFlightSeat applies the HasEdge predicate on the "flight_seat" edge.
func HasFlightSeat() predicate.BookingPassenger {
	return predicate.BookingPassenger(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FlightSeatTable, FlightSeatColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFlightSeatWith applies the HasEdge predicate on the "flight_seat" edge with a given conditions (other predicates).
func HasFlightSeatWith(preds ...predicate.FlightSeat) predicate.BookingPassenger {
	return predicate.BookingPassenger(func(s *sql.Selector) {
		step := newFlightSeatStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BookingPassenger) predicate.BookingPassenger {
	return predicate.BookingPassenger(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BookingPassenger) predicate.BookingPassenger {
	return predicate.BookingPassenger(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BookingPassenger) predicate.BookingPassenger {
	return predicate.BookingPassenger(sql.NotPredicates(p))
}
